// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AccountBalancesColumns holds the columns for the "account_balances" table.
	AccountBalancesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "account", Type: field.TypeString},
		{Name: "asset", Type: field.TypeString},
		{Name: "balance", Type: field.TypeString, Default: "0", SchemaType: map[string]string{"postgres": "numeric(78,0)"}},
		{Name: "flagged", Type: field.TypeBool, Default: false},
		{Name: "version", Type: field.TypeInt, Default: 0},
	}
	// AccountBalancesTable holds the schema information for the "account_balances" table.
	AccountBalancesTable = &schema.Table{
		Name:       "account_balances",
		Columns:    AccountBalancesColumns,
		PrimaryKey: []*schema.Column{AccountBalancesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "accountbalance_account_asset",
				Unique:  true,
				Columns: []*schema.Column{AccountBalancesColumns[1], AccountBalancesColumns[2]},
			},
		},
	}
	// AssetConfigsColumns holds the columns for the "asset_configs" table.
	AssetConfigsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "chain", Type: field.TypeString},
		{Name: "asset", Type: field.TypeString},
		{Name: "decimals", Type: field.TypeInt},
		{Name: "mode", Type: field.TypeEnum, Enums: []string{"self_built", "custodian"}},
		{Name: "min_amount", Type: field.TypeString, Default: "0", SchemaType: map[string]string{"postgres": "numeric(78,0)"}},
		{Name: "n_credit", Type: field.TypeInt},
		{Name: "n_finalize", Type: field.TypeInt},
		{Name: "reorg_window", Type: field.TypeInt},
	}
	// AssetConfigsTable holds the schema information for the "asset_configs" table.
	AssetConfigsTable = &schema.Table{
		Name:       "asset_configs",
		Columns:    AssetConfigsColumns,
		PrimaryKey: []*schema.Column{AssetConfigsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "assetconfig_chain_asset",
				Unique:  true,
				Columns: []*schema.Column{AssetConfigsColumns[1], AssetConfigsColumns[2]},
			},
		},
	}
	// DepositsColumns holds the columns for the "deposits" table.
	DepositsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "transfer_id", Type: field.TypeString, Unique: true},
		{Name: "chain", Type: field.TypeString},
		{Name: "asset", Type: field.TypeString},
		{Name: "account", Type: field.TypeString},
		{Name: "address", Type: field.TypeString},
		{Name: "amount", Type: field.TypeString, SchemaType: map[string]string{"postgres": "numeric(78,0)"}},
		{Name: "mode", Type: field.TypeEnum, Enums: []string{"self_built", "custodian"}},
		{Name: "state", Type: field.TypeEnum, Enums: []string{"PENDING", "CREDITED", "FINALIZED", "REORGED", "DROPPED", "REVERSED", "BELOW_MINIMUM"}, Default: "PENDING"},
		{Name: "credit_cycle", Type: field.TypeInt, Default: 0},
		{Name: "block_height", Type: field.TypeInt64, Nullable: true},
		{Name: "block_hash", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// DepositsTable holds the schema information for the "deposits" table.
	DepositsTable = &schema.Table{
		Name:       "deposits",
		Columns:    DepositsColumns,
		PrimaryKey: []*schema.Column{DepositsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "deposit_account_asset",
				Unique:  false,
				Columns: []*schema.Column{DepositsColumns[4], DepositsColumns[3]},
			},
			{
				Name:    "deposit_state",
				Unique:  false,
				Columns: []*schema.Column{DepositsColumns[8]},
			},
		},
	}
	// DepositAddressesColumns holds the columns for the "deposit_addresses" table.
	DepositAddressesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "account", Type: field.TypeString},
		{Name: "chain", Type: field.TypeString},
		{Name: "address", Type: field.TypeString},
		{Name: "mode", Type: field.TypeEnum, Enums: []string{"self_built", "custodian"}},
		{Name: "active", Type: field.TypeBool, Default: true},
	}
	// DepositAddressesTable holds the schema information for the "deposit_addresses" table.
	DepositAddressesTable = &schema.Table{
		Name:       "deposit_addresses",
		Columns:    DepositAddressesColumns,
		PrimaryKey: []*schema.Column{DepositAddressesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "depositaddress_chain_address",
				Unique:  true,
				Columns: []*schema.Column{DepositAddressesColumns[2], DepositAddressesColumns[3]},
			},
		},
	}
	// LedgerEntriesColumns holds the columns for the "ledger_entries" table.
	LedgerEntriesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "account", Type: field.TypeString},
		{Name: "asset", Type: field.TypeString},
		{Name: "type", Type: field.TypeEnum, Enums: []string{"credit", "debit", "reversal"}},
		{Name: "amount", Type: field.TypeString, SchemaType: map[string]string{"postgres": "numeric(78,0)"}},
		{Name: "ref", Type: field.TypeString, Unique: true},
		{Name: "created_at", Type: field.TypeTime},
	}
	// LedgerEntriesTable holds the schema information for the "ledger_entries" table.
	LedgerEntriesTable = &schema.Table{
		Name:       "ledger_entries",
		Columns:    LedgerEntriesColumns,
		PrimaryKey: []*schema.Column{LedgerEntriesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "ledgerentry_account_asset",
				Unique:  false,
				Columns: []*schema.Column{LedgerEntriesColumns[1], LedgerEntriesColumns[2]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AccountBalancesTable,
		AssetConfigsTable,
		DepositsTable,
		DepositAddressesTable,
		LedgerEntriesTable,
	}
)

func init() {
}
