// Code generated by ent, DO NOT EDIT.

package deposit

import (
	"deposit-crediting/internal/store/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Deposit {
	return predicate.Deposit(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Deposit {
	return predicate.Deposit(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Deposit {
	return predicate.Deposit(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Deposit {
	return predicate.Deposit(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Deposit {
	return predicate.Deposit(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Deposit {
	return predicate.Deposit(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Deposit {
	return predicate.Deposit(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Deposit {
	return predicate.Deposit(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Deposit {
	return predicate.Deposit(sql.FieldLTE(FieldID, id))
}

// TransferID applies equality check predicate on the "transfer_id" field. It's identical to TransferIDEQ.
func TransferID(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldEQ(FieldTransferID, v))
}

// Chain applies equality check predicate on the "chain" field. It's identical to ChainEQ.
func Chain(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldEQ(FieldChain, v))
}

// Asset applies equality check predicate on the "asset" field. It's identical to AssetEQ.
func Asset(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldEQ(FieldAsset, v))
}

// Account applies equality check predicate on the "account" field. It's identical to AccountEQ.
func Account(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldEQ(FieldAccount, v))
}

// Address applies equality check predicate on the "address" field. It's identical to AddressEQ.
func Address(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldEQ(FieldAddress, v))
}

// Amount applies equality check predicate on the "amount" field. It's identical to AmountEQ.
func Amount(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldEQ(FieldAmount, v))
}

// CreditCycle applies equality check predicate on the "credit_cycle" field. It's identical to CreditCycleEQ.
func CreditCycle(v int) predicate.Deposit {
	return predicate.Deposit(sql.FieldEQ(FieldCreditCycle, v))
}

// BlockHeight applies equality check predicate on the "block_height" field. It's identical to BlockHeightEQ.
func BlockHeight(v int64) predicate.Deposit {
	return predicate.Deposit(sql.FieldEQ(FieldBlockHeight, v))
}

// BlockHash applies equality check predicate on the "block_hash" field. It's identical to BlockHashEQ.
func BlockHash(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldEQ(FieldBlockHash, v))
}

// ReorgedHeight applies equality check predicate on the "reorged_height" field. It's identical to ReorgedHeightEQ.
func ReorgedHeight(v int64) predicate.Deposit {
	return predicate.Deposit(sql.FieldEQ(FieldReorgedHeight, v))
}

// TxHash applies equality check predicate on the "tx_hash" field. It's identical to TxHashEQ.
func TxHash(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldEQ(FieldTxHash, v))
}

// SourceEvent applies equality check predicate on the "source_event" field. It's identical to SourceEventEQ.
func SourceEvent(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldEQ(FieldSourceEvent, v))
}

// Held applies equality check predicate on the "held" field. It's identical to HeldEQ.
func Held(v bool) predicate.Deposit {
	return predicate.Deposit(sql.FieldEQ(FieldHeld, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Deposit {
	return predicate.Deposit(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Deposit {
	return predicate.Deposit(sql.FieldEQ(FieldUpdatedAt, v))
}

// TransferIDEQ applies the EQ predicate on the "transfer_id" field.
func TransferIDEQ(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldEQ(FieldTransferID, v))
}

// TransferIDNEQ applies the NEQ predicate on the "transfer_id" field.
func TransferIDNEQ(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldNEQ(FieldTransferID, v))
}

// TransferIDIn applies the In predicate on the "transfer_id" field.
func TransferIDIn(vs ...string) predicate.Deposit {
	return predicate.Deposit(sql.FieldIn(FieldTransferID, vs...))
}

// TransferIDNotIn applies the NotIn predicate on the "transfer_id" field.
func TransferIDNotIn(vs ...string) predicate.Deposit {
	return predicate.Deposit(sql.FieldNotIn(FieldTransferID, vs...))
}

// TransferIDGT applies the GT predicate on the "transfer_id" field.
func TransferIDGT(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldGT(FieldTransferID, v))
}

// TransferIDGTE applies the GTE predicate on the "transfer_id" field.
func TransferIDGTE(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldGTE(FieldTransferID, v))
}

// TransferIDLT applies the LT predicate on the "transfer_id" field.
func TransferIDLT(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldLT(FieldTransferID, v))
}

// TransferIDLTE applies the LTE predicate on the "transfer_id" field.
func TransferIDLTE(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldLTE(FieldTransferID, v))
}

// TransferIDContains applies the Contains predicate on the "transfer_id" field.
func TransferIDContains(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldContains(FieldTransferID, v))
}

// TransferIDHasPrefix applies the HasPrefix predicate on the "transfer_id" field.
func TransferIDHasPrefix(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldHasPrefix(FieldTransferID, v))
}

// TransferIDHasSuffix applies the HasSuffix predicate on the "transfer_id" field.
func TransferIDHasSuffix(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldHasSuffix(FieldTransferID, v))
}

// TransferIDEqualFold applies the EqualFold predicate on the "transfer_id" field.
func TransferIDEqualFold(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldEqualFold(FieldTransferID, v))
}

// TransferIDContainsFold applies the ContainsFold predicate on the "transfer_id" field.
func TransferIDContainsFold(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldContainsFold(FieldTransferID, v))
}

// ChainEQ applies the EQ predicate on the "chain" field.
func ChainEQ(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldEQ(FieldChain, v))
}

// ChainNEQ applies the NEQ predicate on the "chain" field.
func ChainNEQ(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldNEQ(FieldChain, v))
}

// ChainIn applies the In predicate on the "chain" field.
func ChainIn(vs ...string) predicate.Deposit {
	return predicate.Deposit(sql.FieldIn(FieldChain, vs...))
}

// ChainNotIn applies the NotIn predicate on the "chain" field.
func ChainNotIn(vs ...string) predicate.Deposit {
	return predicate.Deposit(sql.FieldNotIn(FieldChain, vs...))
}

// ChainGT applies the GT predicate on the "chain" field.
func ChainGT(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldGT(FieldChain, v))
}

// ChainGTE applies the GTE predicate on the "chain" field.
func ChainGTE(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldGTE(FieldChain, v))
}

// ChainLT applies the LT predicate on the "chain" field.
func ChainLT(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldLT(FieldChain, v))
}

// ChainLTE applies the LTE predicate on the "chain" field.
func ChainLTE(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldLTE(FieldChain, v))
}

// ChainContains applies the Contains predicate on the "chain" field.
func ChainContains(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldContains(FieldChain, v))
}

// ChainHasPrefix applies the HasPrefix predicate on the "chain" field.
func ChainHasPrefix(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldHasPrefix(FieldChain, v))
}

// ChainHasSuffix applies the HasSuffix predicate on the "chain" field.
func ChainHasSuffix(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldHasSuffix(FieldChain, v))
}

// ChainEqualFold applies the EqualFold predicate on the "chain" field.
func ChainEqualFold(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldEqualFold(FieldChain, v))
}

// ChainContainsFold applies the ContainsFold predicate on the "chain" field.
func ChainContainsFold(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldContainsFold(FieldChain, v))
}

// AssetEQ applies the EQ predicate on the "asset" field.
func AssetEQ(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldEQ(FieldAsset, v))
}

// AssetNEQ applies the NEQ predicate on the "asset" field.
func AssetNEQ(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldNEQ(FieldAsset, v))
}

// AssetIn applies the In predicate on the "asset" field.
func AssetIn(vs ...string) predicate.Deposit {
	return predicate.Deposit(sql.FieldIn(FieldAsset, vs...))
}

// AssetNotIn applies the NotIn predicate on the "asset" field.
func AssetNotIn(vs ...string) predicate.Deposit {
	return predicate.Deposit(sql.FieldNotIn(FieldAsset, vs...))
}

// AssetGT applies the GT predicate on the "asset" field.
func AssetGT(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldGT(FieldAsset, v))
}

// AssetGTE applies the GTE predicate on the "asset" field.
func AssetGTE(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldGTE(FieldAsset, v))
}

// AssetLT applies the LT predicate on the "asset" field.
func AssetLT(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldLT(FieldAsset, v))
}

// AssetLTE applies the LTE predicate on the "asset" field.
func AssetLTE(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldLTE(FieldAsset, v))
}

// AssetContains applies the Contains predicate on the "asset" field.
func AssetContains(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldContains(FieldAsset, v))
}

// AssetHasPrefix applies the HasPrefix predicate on the "asset" field.
func AssetHasPrefix(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldHasPrefix(FieldAsset, v))
}

// AssetHasSuffix applies the HasSuffix predicate on the "asset" field.
func AssetHasSuffix(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldHasSuffix(FieldAsset, v))
}

// AssetEqualFold applies the EqualFold predicate on the "asset" field.
func AssetEqualFold(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldEqualFold(FieldAsset, v))
}

// AssetContainsFold applies the ContainsFold predicate on the "asset" field.
func AssetContainsFold(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldContainsFold(FieldAsset, v))
}

// AccountEQ applies the EQ predicate on the "account" field.
func AccountEQ(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldEQ(FieldAccount, v))
}

// AccountNEQ applies the NEQ predicate on the "account" field.
func AccountNEQ(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldNEQ(FieldAccount, v))
}

// AccountIn applies the In predicate on the "account" field.
func AccountIn(vs ...string) predicate.Deposit {
	return predicate.Deposit(sql.FieldIn(FieldAccount, vs...))
}

// AccountNotIn applies the NotIn predicate on the "account" field.
func AccountNotIn(vs ...string) predicate.Deposit {
	return predicate.Deposit(sql.FieldNotIn(FieldAccount, vs...))
}

// AccountGT applies the GT predicate on the "account" field.
func AccountGT(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldGT(FieldAccount, v))
}

// AccountGTE applies the GTE predicate on the "account" field.
func AccountGTE(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldGTE(FieldAccount, v))
}

// AccountLT applies the LT predicate on the "account" field.
func AccountLT(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldLT(FieldAccount, v))
}

// AccountLTE applies the LTE predicate on the "account" field.
func AccountLTE(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldLTE(FieldAccount, v))
}

// AccountContains applies the Contains predicate on the "account" field.
func AccountContains(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldContains(FieldAccount, v))
}

// AccountHasPrefix applies the HasPrefix predicate on the "account" field.
func AccountHasPrefix(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldHasPrefix(FieldAccount, v))
}

// AccountHasSuffix applies the HasSuffix predicate on the "account" field.
func AccountHasSuffix(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldHasSuffix(FieldAccount, v))
}

// AccountEqualFold applies the EqualFold predicate on the "account" field.
func AccountEqualFold(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldEqualFold(FieldAccount, v))
}

// AccountContainsFold applies the ContainsFold predicate on the "account" field.
func AccountContainsFold(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldContainsFold(FieldAccount, v))
}

// AddressEQ applies the EQ predicate on the "address" field.
func AddressEQ(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldEQ(FieldAddress, v))
}

// AddressNEQ applies the NEQ predicate on the "address" field.
func AddressNEQ(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldNEQ(FieldAddress, v))
}

// AddressIn applies the In predicate on the "address" field.
func AddressIn(vs ...string) predicate.Deposit {
	return predicate.Deposit(sql.FieldIn(FieldAddress, vs...))
}

// AddressNotIn applies the NotIn predicate on the "address" field.
func AddressNotIn(vs ...string) predicate.Deposit {
	return predicate.Deposit(sql.FieldNotIn(FieldAddress, vs...))
}

// AddressGT applies the GT predicate on the "address" field.
func AddressGT(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldGT(FieldAddress, v))
}

// AddressGTE applies the GTE predicate on the "address" field.
func AddressGTE(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldGTE(FieldAddress, v))
}

// AddressLT applies the LT predicate on the "address" field.
func AddressLT(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldLT(FieldAddress, v))
}

// AddressLTE applies the LTE predicate on the "address" field.
func AddressLTE(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldLTE(FieldAddress, v))
}

// AddressContains applies the Contains predicate on the "address" field.
func AddressContains(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldContains(FieldAddress, v))
}

// AddressHasPrefix applies the HasPrefix predicate on the "address" field.
func AddressHasPrefix(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldHasPrefix(FieldAddress, v))
}

// AddressHasSuffix applies the HasSuffix predicate on the "address" field.
func AddressHasSuffix(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldHasSuffix(FieldAddress, v))
}

// AddressEqualFold applies the EqualFold predicate on the "address" field.
func AddressEqualFold(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldEqualFold(FieldAddress, v))
}

// AddressContainsFold applies the ContainsFold predicate on the "address" field.
func AddressContainsFold(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldContainsFold(FieldAddress, v))
}

// AmountEQ applies the EQ predicate on the "amount" field.
func AmountEQ(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldEQ(FieldAmount, v))
}

// AmountNEQ applies the NEQ predicate on the "amount" field.
func AmountNEQ(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldNEQ(FieldAmount, v))
}

// AmountIn applies the In predicate on the "amount" field.
func AmountIn(vs ...string) predicate.Deposit {
	return predicate.Deposit(sql.FieldIn(FieldAmount, vs...))
}

// AmountNotIn applies the NotIn predicate on the "amount" field.
func AmountNotIn(vs ...string) predicate.Deposit {
	return predicate.Deposit(sql.FieldNotIn(FieldAmount, vs...))
}

// AmountGT applies the GT predicate on the "amount" field.
func AmountGT(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldGT(FieldAmount, v))
}

// AmountGTE applies the GTE predicate on the "amount" field.
func AmountGTE(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldGTE(FieldAmount, v))
}

// AmountLT applies the LT predicate on the "amount" field.
func AmountLT(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldLT(FieldAmount, v))
}

// AmountLTE applies the LTE predicate on the "amount" field.
func AmountLTE(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldLTE(FieldAmount, v))
}

// AmountContains applies the Contains predicate on the "amount" field.
func AmountContains(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldContains(FieldAmount, v))
}

// AmountHasPrefix applies the HasPrefix predicate on the "amount" field.
func AmountHasPrefix(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldHasPrefix(FieldAmount, v))
}

// AmountHasSuffix applies the HasSuffix predicate on the "amount" field.
func AmountHasSuffix(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldHasSuffix(FieldAmount, v))
}

// AmountEqualFold applies the EqualFold predicate on the "amount" field.
func AmountEqualFold(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldEqualFold(FieldAmount, v))
}

// AmountContainsFold applies the ContainsFold predicate on the "amount" field.
func AmountContainsFold(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldContainsFold(FieldAmount, v))
}

// ModeEQ applies the EQ predicate on the "mode" field.
func ModeEQ(v Mode) predicate.Deposit {
	return predicate.Deposit(sql.FieldEQ(FieldMode, v))
}

// ModeNEQ applies the NEQ predicate on the "mode" field.
func ModeNEQ(v Mode) predicate.Deposit {
	return predicate.Deposit(sql.FieldNEQ(FieldMode, v))
}

// ModeIn applies the In predicate on the "mode" field.
func ModeIn(vs ...Mode) predicate.Deposit {
	return predicate.Deposit(sql.FieldIn(FieldMode, vs...))
}

// ModeNotIn applies the NotIn predicate on the "mode" field.
func ModeNotIn(vs ...Mode) predicate.Deposit {
	return predicate.Deposit(sql.FieldNotIn(FieldMode, vs...))
}

// StateEQ applies the EQ predicate on the "state" field.
func StateEQ(v State) predicate.Deposit {
	return predicate.Deposit(sql.FieldEQ(FieldState, v))
}

// StateNEQ applies the NEQ predicate on the "state" field.
func StateNEQ(v State) predicate.Deposit {
	return predicate.Deposit(sql.FieldNEQ(FieldState, v))
}

// StateIn applies the In predicate on the "state" field.
func StateIn(vs ...State) predicate.Deposit {
	return predicate.Deposit(sql.FieldIn(FieldState, vs...))
}

// StateNotIn applies the NotIn predicate on the "state" field.
func StateNotIn(vs ...State) predicate.Deposit {
	return predicate.Deposit(sql.FieldNotIn(FieldState, vs...))
}

// CreditCycleEQ applies the EQ predicate on the "credit_cycle" field.
func CreditCycleEQ(v int) predicate.Deposit {
	return predicate.Deposit(sql.FieldEQ(FieldCreditCycle, v))
}

// CreditCycleNEQ applies the NEQ predicate on the "credit_cycle" field.
func CreditCycleNEQ(v int) predicate.Deposit {
	return predicate.Deposit(sql.FieldNEQ(FieldCreditCycle, v))
}

// CreditCycleIn applies the In predicate on the "credit_cycle" field.
func CreditCycleIn(vs ...int) predicate.Deposit {
	return predicate.Deposit(sql.FieldIn(FieldCreditCycle, vs...))
}

// CreditCycleNotIn applies the NotIn predicate on the "credit_cycle" field.
func CreditCycleNotIn(vs ...int) predicate.Deposit {
	return predicate.Deposit(sql.FieldNotIn(FieldCreditCycle, vs...))
}

// CreditCycleGT applies the GT predicate on the "credit_cycle" field.
func CreditCycleGT(v int) predicate.Deposit {
	return predicate.Deposit(sql.FieldGT(FieldCreditCycle, v))
}

// CreditCycleGTE applies the GTE predicate on the "credit_cycle" field.
func CreditCycleGTE(v int) predicate.Deposit {
	return predicate.Deposit(sql.FieldGTE(FieldCreditCycle, v))
}

// CreditCycleLT applies the LT predicate on the "credit_cycle" field.
func CreditCycleLT(v int) predicate.Deposit {
	return predicate.Deposit(sql.FieldLT(FieldCreditCycle, v))
}

// CreditCycleLTE applies the LTE predicate on the "credit_cycle" field.
func CreditCycleLTE(v int) predicate.Deposit {
	return predicate.Deposit(sql.FieldLTE(FieldCreditCycle, v))
}

// BlockHeightEQ applies the EQ predicate on the "block_height" field.
func BlockHeightEQ(v int64) predicate.Deposit {
	return predicate.Deposit(sql.FieldEQ(FieldBlockHeight, v))
}

// BlockHeightNEQ applies the NEQ predicate on the "block_height" field.
func BlockHeightNEQ(v int64) predicate.Deposit {
	return predicate.Deposit(sql.FieldNEQ(FieldBlockHeight, v))
}

// BlockHeightIn applies the In predicate on the "block_height" field.
func BlockHeightIn(vs ...int64) predicate.Deposit {
	return predicate.Deposit(sql.FieldIn(FieldBlockHeight, vs...))
}

// BlockHeightNotIn applies the NotIn predicate on the "block_height" field.
func BlockHeightNotIn(vs ...int64) predicate.Deposit {
	return predicate.Deposit(sql.FieldNotIn(FieldBlockHeight, vs...))
}

// BlockHeightGT applies the GT predicate on the "block_height" field.
func BlockHeightGT(v int64) predicate.Deposit {
	return predicate.Deposit(sql.FieldGT(FieldBlockHeight, v))
}

// BlockHeightGTE applies the GTE predicate on the "block_height" field.
func BlockHeightGTE(v int64) predicate.Deposit {
	return predicate.Deposit(sql.FieldGTE(FieldBlockHeight, v))
}

// BlockHeightLT applies the LT predicate on the "block_height" field.
func BlockHeightLT(v int64) predicate.Deposit {
	return predicate.Deposit(sql.FieldLT(FieldBlockHeight, v))
}

// BlockHeightLTE applies the LTE predicate on the "block_height" field.
func BlockHeightLTE(v int64) predicate.Deposit {
	return predicate.Deposit(sql.FieldLTE(FieldBlockHeight, v))
}

// BlockHeightIsNil applies the IsNil predicate on the "block_height" field.
func BlockHeightIsNil() predicate.Deposit {
	return predicate.Deposit(sql.FieldIsNull(FieldBlockHeight))
}

// BlockHeightNotNil applies the NotNil predicate on the "block_height" field.
func BlockHeightNotNil() predicate.Deposit {
	return predicate.Deposit(sql.FieldNotNull(FieldBlockHeight))
}

// BlockHashEQ applies the EQ predicate on the "block_hash" field.
func BlockHashEQ(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldEQ(FieldBlockHash, v))
}

// BlockHashNEQ applies the NEQ predicate on the "block_hash" field.
func BlockHashNEQ(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldNEQ(FieldBlockHash, v))
}

// BlockHashIn applies the In predicate on the "block_hash" field.
func BlockHashIn(vs ...string) predicate.Deposit {
	return predicate.Deposit(sql.FieldIn(FieldBlockHash, vs...))
}

// BlockHashNotIn applies the NotIn predicate on the "block_hash" field.
func BlockHashNotIn(vs ...string) predicate.Deposit {
	return predicate.Deposit(sql.FieldNotIn(FieldBlockHash, vs...))
}

// BlockHashGT applies the GT predicate on the "block_hash" field.
func BlockHashGT(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldGT(FieldBlockHash, v))
}

// BlockHashGTE applies the GTE predicate on the "block_hash" field.
func BlockHashGTE(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldGTE(FieldBlockHash, v))
}

// BlockHashLT applies the LT predicate on the "block_hash" field.
func BlockHashLT(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldLT(FieldBlockHash, v))
}

// BlockHashLTE applies the LTE predicate on the "block_hash" field.
func BlockHashLTE(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldLTE(FieldBlockHash, v))
}

// BlockHashContains applies the Contains predicate on the "block_hash" field.
func BlockHashContains(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldContains(FieldBlockHash, v))
}

// BlockHashHasPrefix applies the HasPrefix predicate on the "block_hash" field.
func BlockHashHasPrefix(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldHasPrefix(FieldBlockHash, v))
}

// BlockHashHasSuffix applies the HasSuffix predicate on the "block_hash" field.
func BlockHashHasSuffix(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldHasSuffix(FieldBlockHash, v))
}

// BlockHashIsNil applies the IsNil predicate on the "block_hash" field.
func BlockHashIsNil() predicate.Deposit {
	return predicate.Deposit(sql.FieldIsNull(FieldBlockHash))
}

// BlockHashNotNil applies the NotNil predicate on the "block_hash" field.
func BlockHashNotNil() predicate.Deposit {
	return predicate.Deposit(sql.FieldNotNull(FieldBlockHash))
}

// BlockHashEqualFold applies the EqualFold predicate on the "block_hash" field.
func BlockHashEqualFold(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldEqualFold(FieldBlockHash, v))
}

// BlockHashContainsFold applies the ContainsFold predicate on the "block_hash" field.
func BlockHashContainsFold(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldContainsFold(FieldBlockHash, v))
}

// ReorgedHeightEQ applies the EQ predicate on the "reorged_height" field.
func ReorgedHeightEQ(v int64) predicate.Deposit {
	return predicate.Deposit(sql.FieldEQ(FieldReorgedHeight, v))
}

// ReorgedHeightNEQ applies the NEQ predicate on the "reorged_height" field.
func ReorgedHeightNEQ(v int64) predicate.Deposit {
	return predicate.Deposit(sql.FieldNEQ(FieldReorgedHeight, v))
}

// ReorgedHeightIn applies the In predicate on the "reorged_height" field.
func ReorgedHeightIn(vs ...int64) predicate.Deposit {
	return predicate.Deposit(sql.FieldIn(FieldReorgedHeight, vs...))
}

// ReorgedHeightNotIn applies the NotIn predicate on the "reorged_height" field.
func ReorgedHeightNotIn(vs ...int64) predicate.Deposit {
	return predicate.Deposit(sql.FieldNotIn(FieldReorgedHeight, vs...))
}

// ReorgedHeightGT applies the GT predicate on the "reorged_height" field.
func ReorgedHeightGT(v int64) predicate.Deposit {
	return predicate.Deposit(sql.FieldGT(FieldReorgedHeight, v))
}

// ReorgedHeightGTE applies the GTE predicate on the "reorged_height" field.
func ReorgedHeightGTE(v int64) predicate.Deposit {
	return predicate.Deposit(sql.FieldGTE(FieldReorgedHeight, v))
}

// ReorgedHeightLT applies the LT predicate on the "reorged_height" field.
func ReorgedHeightLT(v int64) predicate.Deposit {
	return predicate.Deposit(sql.FieldLT(FieldReorgedHeight, v))
}

// ReorgedHeightLTE applies the LTE predicate on the "reorged_height" field.
func ReorgedHeightLTE(v int64) predicate.Deposit {
	return predicate.Deposit(sql.FieldLTE(FieldReorgedHeight, v))
}

// ReorgedHeightIsNil applies the IsNil predicate on the "reorged_height" field.
func ReorgedHeightIsNil() predicate.Deposit {
	return predicate.Deposit(sql.FieldIsNull(FieldReorgedHeight))
}

// ReorgedHeightNotNil applies the NotNil predicate on the "reorged_height" field.
func ReorgedHeightNotNil() predicate.Deposit {
	return predicate.Deposit(sql.FieldNotNull(FieldReorgedHeight))
}

// TxHashEQ applies the EQ predicate on the "tx_hash" field.
func TxHashEQ(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldEQ(FieldTxHash, v))
}

// TxHashNEQ applies the NEQ predicate on the "tx_hash" field.
func TxHashNEQ(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldNEQ(FieldTxHash, v))
}

// TxHashIn applies the In predicate on the "tx_hash" field.
func TxHashIn(vs ...string) predicate.Deposit {
	return predicate.Deposit(sql.FieldIn(FieldTxHash, vs...))
}

// TxHashNotIn applies the NotIn predicate on the "tx_hash" field.
func TxHashNotIn(vs ...string) predicate.Deposit {
	return predicate.Deposit(sql.FieldNotIn(FieldTxHash, vs...))
}

// TxHashGT applies the GT predicate on the "tx_hash" field.
func TxHashGT(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldGT(FieldTxHash, v))
}

// TxHashGTE applies the GTE predicate on the "tx_hash" field.
func TxHashGTE(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldGTE(FieldTxHash, v))
}

// TxHashLT applies the LT predicate on the "tx_hash" field.
func TxHashLT(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldLT(FieldTxHash, v))
}

// TxHashLTE applies the LTE predicate on the "tx_hash" field.
func TxHashLTE(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldLTE(FieldTxHash, v))
}

// TxHashContains applies the Contains predicate on the "tx_hash" field.
func TxHashContains(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldContains(FieldTxHash, v))
}

// TxHashHasPrefix applies the HasPrefix predicate on the "tx_hash" field.
func TxHashHasPrefix(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldHasPrefix(FieldTxHash, v))
}

// TxHashHasSuffix applies the HasSuffix predicate on the "tx_hash" field.
func TxHashHasSuffix(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldHasSuffix(FieldTxHash, v))
}

// TxHashIsNil applies the IsNil predicate on the "tx_hash" field.
func TxHashIsNil() predicate.Deposit {
	return predicate.Deposit(sql.FieldIsNull(FieldTxHash))
}

// TxHashNotNil applies the NotNil predicate on the "tx_hash" field.
func TxHashNotNil() predicate.Deposit {
	return predicate.Deposit(sql.FieldNotNull(FieldTxHash))
}

// TxHashEqualFold applies the EqualFold predicate on the "tx_hash" field.
func TxHashEqualFold(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldEqualFold(FieldTxHash, v))
}

// TxHashContainsFold applies the ContainsFold predicate on the "tx_hash" field.
func TxHashContainsFold(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldContainsFold(FieldTxHash, v))
}

// SourceEventEQ applies the EQ predicate on the "source_event" field.
func SourceEventEQ(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldEQ(FieldSourceEvent, v))
}

// SourceEventNEQ applies the NEQ predicate on the "source_event" field.
func SourceEventNEQ(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldNEQ(FieldSourceEvent, v))
}

// SourceEventIn applies the In predicate on the "source_event" field.
func SourceEventIn(vs ...string) predicate.Deposit {
	return predicate.Deposit(sql.FieldIn(FieldSourceEvent, vs...))
}

// SourceEventNotIn applies the NotIn predicate on the "source_event" field.
func SourceEventNotIn(vs ...string) predicate.Deposit {
	return predicate.Deposit(sql.FieldNotIn(FieldSourceEvent, vs...))
}

// SourceEventGT applies the GT predicate on the "source_event" field.
func SourceEventGT(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldGT(FieldSourceEvent, v))
}

// SourceEventGTE applies the GTE predicate on the "source_event" field.
func SourceEventGTE(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldGTE(FieldSourceEvent, v))
}

// SourceEventLT applies the LT predicate on the "source_event" field.
func SourceEventLT(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldLT(FieldSourceEvent, v))
}

// SourceEventLTE applies the LTE predicate on the "source_event" field.
func SourceEventLTE(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldLTE(FieldSourceEvent, v))
}

// SourceEventContains applies the Contains predicate on the "source_event" field.
func SourceEventContains(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldContains(FieldSourceEvent, v))
}

// SourceEventHasPrefix applies the HasPrefix predicate on the "source_event" field.
func SourceEventHasPrefix(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldHasPrefix(FieldSourceEvent, v))
}

// SourceEventHasSuffix applies the HasSuffix predicate on the "source_event" field.
func SourceEventHasSuffix(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldHasSuffix(FieldSourceEvent, v))
}

// SourceEventIsNil applies the IsNil predicate on the "source_event" field.
func SourceEventIsNil() predicate.Deposit {
	return predicate.Deposit(sql.FieldIsNull(FieldSourceEvent))
}

// SourceEventNotNil applies the NotNil predicate on the "source_event" field.
func SourceEventNotNil() predicate.Deposit {
	return predicate.Deposit(sql.FieldNotNull(FieldSourceEvent))
}

// SourceEventEqualFold applies the EqualFold predicate on the "source_event" field.
func SourceEventEqualFold(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldEqualFold(FieldSourceEvent, v))
}

// SourceEventContainsFold applies the ContainsFold predicate on the "source_event" field.
func SourceEventContainsFold(v string) predicate.Deposit {
	return predicate.Deposit(sql.FieldContainsFold(FieldSourceEvent, v))
}

// HeldEQ applies the EQ predicate on the "held" field.
func HeldEQ(v bool) predicate.Deposit {
	return predicate.Deposit(sql.FieldEQ(FieldHeld, v))
}

// HeldNEQ applies the NEQ predicate on the "held" field.
func HeldNEQ(v bool) predicate.Deposit {
	return predicate.Deposit(sql.FieldNEQ(FieldHeld, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Deposit {
	return predicate.Deposit(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Deposit {
	return predicate.Deposit(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Deposit {
	return predicate.Deposit(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Deposit {
	return predicate.Deposit(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Deposit {
	return predicate.Deposit(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Deposit {
	return predicate.Deposit(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Deposit {
	return predicate.Deposit(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Deposit {
	return predicate.Deposit(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Deposit {
	return predicate.Deposit(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Deposit {
	return predicate.Deposit(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Deposit {
	return predicate.Deposit(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Deposit {
	return predicate.Deposit(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Deposit {
	return predicate.Deposit(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Deposit {
	return predicate.Deposit(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Deposit {
	return predicate.Deposit(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Deposit {
	return predicate.Deposit(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Deposit) predicate.Deposit {
	return predicate.Deposit(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Deposit) predicate.Deposit {
	return predicate.Deposit(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Deposit) predicate.Deposit {
	return predicate.Deposit(sql.NotPredicates(p))
}
