// Code generated by ent, DO NOT EDIT.

package chaincursor

import (
	"deposit-crediting/internal/store/ent/predicate"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.ChainCursor {
	return predicate.ChainCursor(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.ChainCursor {
	return predicate.ChainCursor(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.ChainCursor {
	return predicate.ChainCursor(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.ChainCursor {
	return predicate.ChainCursor(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.ChainCursor {
	return predicate.ChainCursor(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.ChainCursor {
	return predicate.ChainCursor(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.ChainCursor {
	return predicate.ChainCursor(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.ChainCursor {
	return predicate.ChainCursor(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.ChainCursor {
	return predicate.ChainCursor(sql.FieldLTE(FieldID, id))
}

// Chain applies equality check predicate on the "chain" field. It's identical to ChainEQ.
func Chain(v string) predicate.ChainCursor {
	return predicate.ChainCursor(sql.FieldEQ(FieldChain, v))
}

// Height applies equality check predicate on the "height" field. It's identical to HeightEQ.
func Height(v int64) predicate.ChainCursor {
	return predicate.ChainCursor(sql.FieldEQ(FieldHeight, v))
}

// Hash applies equality check predicate on the "hash" field. It's identical to HashEQ.
func Hash(v string) predicate.ChainCursor {
	return predicate.ChainCursor(sql.FieldEQ(FieldHash, v))
}

// ChainEQ applies the EQ predicate on the "chain" field.
func ChainEQ(v string) predicate.ChainCursor {
	return predicate.ChainCursor(sql.FieldEQ(FieldChain, v))
}

// ChainNEQ applies the NEQ predicate on the "chain" field.
func ChainNEQ(v string) predicate.ChainCursor {
	return predicate.ChainCursor(sql.FieldNEQ(FieldChain, v))
}

// ChainIn applies the In predicate on the "chain" field.
func ChainIn(vs ...string) predicate.ChainCursor {
	return predicate.ChainCursor(sql.FieldIn(FieldChain, vs...))
}

// ChainNotIn applies the NotIn predicate on the "chain" field.
func ChainNotIn(vs ...string) predicate.ChainCursor {
	return predicate.ChainCursor(sql.FieldNotIn(FieldChain, vs...))
}

// ChainGT applies the GT predicate on the "chain" field.
func ChainGT(v string) predicate.ChainCursor {
	return predicate.ChainCursor(sql.FieldGT(FieldChain, v))
}

// ChainGTE applies the GTE predicate on the "chain" field.
func ChainGTE(v string) predicate.ChainCursor {
	return predicate.ChainCursor(sql.FieldGTE(FieldChain, v))
}

// ChainLT applies the LT predicate on the "chain" field.
func ChainLT(v string) predicate.ChainCursor {
	return predicate.ChainCursor(sql.FieldLT(FieldChain, v))
}

// ChainLTE applies the LTE predicate on the "chain" field.
func ChainLTE(v string) predicate.ChainCursor {
	return predicate.ChainCursor(sql.FieldLTE(FieldChain, v))
}

// ChainContains applies the Contains predicate on the "chain" field.
func ChainContains(v string) predicate.ChainCursor {
	return predicate.ChainCursor(sql.FieldContains(FieldChain, v))
}

// ChainHasPrefix applies the HasPrefix predicate on the "chain" field.
func ChainHasPrefix(v string) predicate.ChainCursor {
	return predicate.ChainCursor(sql.FieldHasPrefix(FieldChain, v))
}

// ChainHasSuffix applies the HasSuffix predicate on the "chain" field.
func ChainHasSuffix(v string) predicate.ChainCursor {
	return predicate.ChainCursor(sql.FieldHasSuffix(FieldChain, v))
}

// ChainEqualFold applies the EqualFold predicate on the "chain" field.
func ChainEqualFold(v string) predicate.ChainCursor {
	return predicate.ChainCursor(sql.FieldEqualFold(FieldChain, v))
}

// ChainContainsFold applies the ContainsFold predicate on the "chain" field.
func ChainContainsFold(v string) predicate.ChainCursor {
	return predicate.ChainCursor(sql.FieldContainsFold(FieldChain, v))
}

// HeightEQ applies the EQ predicate on the "height" field.
func HeightEQ(v int64) predicate.ChainCursor {
	return predicate.ChainCursor(sql.FieldEQ(FieldHeight, v))
}

// HeightNEQ applies the NEQ predicate on the "height" field.
func HeightNEQ(v int64) predicate.ChainCursor {
	return predicate.ChainCursor(sql.FieldNEQ(FieldHeight, v))
}

// HeightIn applies the In predicate on the "height" field.
func HeightIn(vs ...int64) predicate.ChainCursor {
	return predicate.ChainCursor(sql.FieldIn(FieldHeight, vs...))
}

// HeightNotIn applies the NotIn predicate on the "height" field.
func HeightNotIn(vs ...int64) predicate.ChainCursor {
	return predicate.ChainCursor(sql.FieldNotIn(FieldHeight, vs...))
}

// HeightGT applies the GT predicate on the "height" field.
func HeightGT(v int64) predicate.ChainCursor {
	return predicate.ChainCursor(sql.FieldGT(FieldHeight, v))
}

// HeightGTE applies the GTE predicate on the "height" field.
func HeightGTE(v int64) predicate.ChainCursor {
	return predicate.ChainCursor(sql.FieldGTE(FieldHeight, v))
}

// HeightLT applies the LT predicate on the "height" field.
func HeightLT(v int64) predicate.ChainCursor {
	return predicate.ChainCursor(sql.FieldLT(FieldHeight, v))
}

// HeightLTE applies the LTE predicate on the "height" field.
func HeightLTE(v int64) predicate.ChainCursor {
	return predicate.ChainCursor(sql.FieldLTE(FieldHeight, v))
}

// HashEQ applies the EQ predicate on the "hash" field.
func HashEQ(v string) predicate.ChainCursor {
	return predicate.ChainCursor(sql.FieldEQ(FieldHash, v))
}

// HashNEQ applies the NEQ predicate on the "hash" field.
func HashNEQ(v string) predicate.ChainCursor {
	return predicate.ChainCursor(sql.FieldNEQ(FieldHash, v))
}

// HashIn applies the In predicate on the "hash" field.
func HashIn(vs ...string) predicate.ChainCursor {
	return predicate.ChainCursor(sql.FieldIn(FieldHash, vs...))
}

// HashNotIn applies the NotIn predicate on the "hash" field.
func HashNotIn(vs ...string) predicate.ChainCursor {
	return predicate.ChainCursor(sql.FieldNotIn(FieldHash, vs...))
}

// HashGT applies the GT predicate on the "hash" field.
func HashGT(v string) predicate.ChainCursor {
	return predicate.ChainCursor(sql.FieldGT(FieldHash, v))
}

// HashGTE applies the GTE predicate on the "hash" field.
func HashGTE(v string) predicate.ChainCursor {
	return predicate.ChainCursor(sql.FieldGTE(FieldHash, v))
}

// HashLT applies the LT predicate on the "hash" field.
func HashLT(v string) predicate.ChainCursor {
	return predicate.ChainCursor(sql.FieldLT(FieldHash, v))
}

// HashLTE applies the LTE predicate on the "hash" field.
func HashLTE(v string) predicate.ChainCursor {
	return predicate.ChainCursor(sql.FieldLTE(FieldHash, v))
}

// HashContains applies the Contains predicate on the "hash" field.
func HashContains(v string) predicate.ChainCursor {
	return predicate.ChainCursor(sql.FieldContains(FieldHash, v))
}

// HashHasPrefix applies the HasPrefix predicate on the "hash" field.
func HashHasPrefix(v string) predicate.ChainCursor {
	return predicate.ChainCursor(sql.FieldHasPrefix(FieldHash, v))
}

// HashHasSuffix applies the HasSuffix predicate on the "hash" field.
func HashHasSuffix(v string) predicate.ChainCursor {
	return predicate.ChainCursor(sql.FieldHasSuffix(FieldHash, v))
}

// HashEqualFold applies the EqualFold predicate on the "hash" field.
func HashEqualFold(v string) predicate.ChainCursor {
	return predicate.ChainCursor(sql.FieldEqualFold(FieldHash, v))
}

// HashContainsFold applies the ContainsFold predicate on the "hash" field.
func HashContainsFold(v string) predicate.ChainCursor {
	return predicate.ChainCursor(sql.FieldContainsFold(FieldHash, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ChainCursor) predicate.ChainCursor {
	return predicate.ChainCursor(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ChainCursor) predicate.ChainCursor {
	return predicate.ChainCursor(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ChainCursor) predicate.ChainCursor {
	return predicate.ChainCursor(sql.NotPredicates(p))
}
