// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"deposit-crediting/internal/store/ent/accountbalance"
	"deposit-crediting/internal/store/ent/predicate"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AccountBalanceUpdate is the builder for updating AccountBalance entities.
type AccountBalanceUpdate struct {
	config
	hooks    []Hook
	mutation *AccountBalanceMutation
}

// Where appends a list predicates to the AccountBalanceUpdate builder.
func (_u *AccountBalanceUpdate) Where(ps ...predicate.AccountBalance) *AccountBalanceUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetAccount sets the "account" field.
func (_u *AccountBalanceUpdate) SetAccount(v string) *AccountBalanceUpdate {
	_u.mutation.SetAccount(v)
	return _u
}

// SetNillableAccount sets the "account" field if the given value is not nil.
func (_u *AccountBalanceUpdate) SetNillableAccount(v *string) *AccountBalanceUpdate {
	if v != nil {
		_u.SetAccount(*v)
	}
	return _u
}

// SetAsset sets the "asset" field.
func (_u *AccountBalanceUpdate) SetAsset(v string) *AccountBalanceUpdate {
	_u.mutation.SetAsset(v)
	return _u
}

// SetNillableAsset sets the "asset" field if the given value is not nil.
func (_u *AccountBalanceUpdate) SetNillableAsset(v *string) *AccountBalanceUpdate {
	if v != nil {
		_u.SetAsset(*v)
	}
	return _u
}

// SetBalance sets the "balance" field.
func (_u *AccountBalanceUpdate) SetBalance(v string) *AccountBalanceUpdate {
	_u.mutation.SetBalance(v)
	return _u
}

// SetNillableBalance sets the "balance" field if the given value is not nil.
func (_u *AccountBalanceUpdate) SetNillableBalance(v *string) *AccountBalanceUpdate {
	if v != nil {
		_u.SetBalance(*v)
	}
	return _u
}

// SetFlagged sets the "flagged" field.
func (_u *AccountBalanceUpdate) SetFlagged(v bool) *AccountBalanceUpdate {
	_u.mutation.SetFlagged(v)
	return _u
}

// SetNillableFlagged sets the "flagged" field if the given value is not nil.
func (_u *AccountBalanceUpdate) SetNillableFlagged(v *bool) *AccountBalanceUpdate {
	if v != nil {
		_u.SetFlagged(*v)
	}
	return _u
}

// SetVersion sets the "version" field.
func (_u *AccountBalanceUpdate) SetVersion(v int) *AccountBalanceUpdate {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *AccountBalanceUpdate) SetNillableVersion(v *int) *AccountBalanceUpdate {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *AccountBalanceUpdate) AddVersion(v int) *AccountBalanceUpdate {
	_u.mutation.AddVersion(v)
	return _u
}

// Mutation returns the AccountBalanceMutation object of the builder.
func (_u *AccountBalanceUpdate) Mutation() *AccountBalanceMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AccountBalanceUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AccountBalanceUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AccountBalanceUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AccountBalanceUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AccountBalanceUpdate) check() error {
	if v, ok := _u.mutation.Account(); ok {
		if err := accountbalance.AccountValidator(v); err != nil {
			return &ValidationError{Name: "account", err: fmt.Errorf(`ent: validator failed for field "AccountBalance.account": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Asset(); ok {
		if err := accountbalance.AssetValidator(v); err != nil {
			return &ValidationError{Name: "asset", err: fmt.Errorf(`ent: validator failed for field "AccountBalance.asset": %w`, err)}
		}
	}
	return nil
}

func (_u *AccountBalanceUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(accountbalance.Table, accountbalance.Columns, sqlgraph.NewFieldSpec(accountbalance.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Account(); ok {
		_spec.SetField(accountbalance.FieldAccount, field.TypeString, value)
	}
	if value, ok := _u.mutation.Asset(); ok {
		_spec.SetField(accountbalance.FieldAsset, field.TypeString, value)
	}
	if value, ok := _u.mutation.Balance(); ok {
		_spec.SetField(accountbalance.FieldBalance, field.TypeString, value)
	}
	if value, ok := _u.mutation.Flagged(); ok {
		_spec.SetField(accountbalance.FieldFlagged, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(accountbalance.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(accountbalance.FieldVersion, field.TypeInt, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{accountbalance.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AccountBalanceUpdateOne is the builder for updating a single AccountBalance entity.
type AccountBalanceUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AccountBalanceMutation
}

// SetAccount sets the "account" field.
func (_u *AccountBalanceUpdateOne) SetAccount(v string) *AccountBalanceUpdateOne {
	_u.mutation.SetAccount(v)
	return _u
}

// SetNillableAccount sets the "account" field if the given value is not nil.
func (_u *AccountBalanceUpdateOne) SetNillableAccount(v *string) *AccountBalanceUpdateOne {
	if v != nil {
		_u.SetAccount(*v)
	}
	return _u
}

// SetAsset sets the "asset" field.
func (_u *AccountBalanceUpdateOne) SetAsset(v string) *AccountBalanceUpdateOne {
	_u.mutation.SetAsset(v)
	return _u
}

// SetNillableAsset sets the "asset" field if the given value is not nil.
func (_u *AccountBalanceUpdateOne) SetNillableAsset(v *string) *AccountBalanceUpdateOne {
	if v != nil {
		_u.SetAsset(*v)
	}
	return _u
}

// SetBalance sets the "balance" field.
func (_u *AccountBalanceUpdateOne) SetBalance(v string) *AccountBalanceUpdateOne {
	_u.mutation.SetBalance(v)
	return _u
}

// SetNillableBalance sets the "balance" field if the given value is not nil.
func (_u *AccountBalanceUpdateOne) SetNillableBalance(v *string) *AccountBalanceUpdateOne {
	if v != nil {
		_u.SetBalance(*v)
	}
	return _u
}

// SetFlagged sets the "flagged" field.
func (_u *AccountBalanceUpdateOne) SetFlagged(v bool) *AccountBalanceUpdateOne {
	_u.mutation.SetFlagged(v)
	return _u
}

// SetNillableFlagged sets the "flagged" field if the given value is not nil.
func (_u *AccountBalanceUpdateOne) SetNillableFlagged(v *bool) *AccountBalanceUpdateOne {
	if v != nil {
		_u.SetFlagged(*v)
	}
	return _u
}

// SetVersion sets the "version" field.
func (_u *AccountBalanceUpdateOne) SetVersion(v int) *AccountBalanceUpdateOne {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *AccountBalanceUpdateOne) SetNillableVersion(v *int) *AccountBalanceUpdateOne {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *AccountBalanceUpdateOne) AddVersion(v int) *AccountBalanceUpdateOne {
	_u.mutation.AddVersion(v)
	return _u
}

// Mutation returns the AccountBalanceMutation object of the builder.
func (_u *AccountBalanceUpdateOne) Mutation() *AccountBalanceMutation {
	return _u.mutation
}

// Where appends a list predicates to the AccountBalanceUpdate builder.
func (_u *AccountBalanceUpdateOne) Where(ps ...predicate.AccountBalance) *AccountBalanceUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AccountBalanceUpdateOne) Select(field string, fields ...string) *AccountBalanceUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AccountBalance entity.
func (_u *AccountBalanceUpdateOne) Save(ctx context.Context) (*AccountBalance, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AccountBalanceUpdateOne) SaveX(ctx context.Context) *AccountBalance {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AccountBalanceUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AccountBalanceUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AccountBalanceUpdateOne) check() error {
	if v, ok := _u.mutation.Account(); ok {
		if err := accountbalance.AccountValidator(v); err != nil {
			return &ValidationError{Name: "account", err: fmt.Errorf(`ent: validator failed for field "AccountBalance.account": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Asset(); ok {
		if err := accountbalance.AssetValidator(v); err != nil {
			return &ValidationError{Name: "asset", err: fmt.Errorf(`ent: validator failed for field "AccountBalance.asset": %w`, err)}
		}
	}
	return nil
}

func (_u *AccountBalanceUpdateOne) sqlSave(ctx context.Context) (_node *AccountBalance, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(accountbalance.Table, accountbalance.Columns, sqlgraph.NewFieldSpec(accountbalance.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AccountBalance.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, accountbalance.FieldID)
		for _, f := range fields {
			if !accountbalance.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != accountbalance.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Account(); ok {
		_spec.SetField(accountbalance.FieldAccount, field.TypeString, value)
	}
	if value, ok := _u.mutation.Asset(); ok {
		_spec.SetField(accountbalance.FieldAsset, field.TypeString, value)
	}
	if value, ok := _u.mutation.Balance(); ok {
		_spec.SetField(accountbalance.FieldBalance, field.TypeString, value)
	}
	if value, ok := _u.mutation.Flagged(); ok {
		_spec.SetField(accountbalance.FieldFlagged, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(accountbalance.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(accountbalance.FieldVersion, field.TypeInt, value)
	}
	_node = &AccountBalance{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{accountbalance.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
