// Code generated by ent, DO NOT EDIT.

package ent

import (
	"deposit-crediting/internal/store/ent/assetconfig"
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// AssetConfig is the model entity for the AssetConfig schema.
type AssetConfig struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Chain holds the value of the "chain" field.
	Chain string `json:"chain,omitempty"`
	// Asset holds the value of the "asset" field.
	Asset string `json:"asset,omitempty"`
	// Decimals holds the value of the "decimals" field.
	Decimals int `json:"decimals,omitempty"`
	// Mode holds the value of the "mode" field.
	Mode assetconfig.Mode `json:"mode,omitempty"`
	// MinAmount holds the value of the "min_amount" field.
	MinAmount string `json:"min_amount,omitempty"`
	// NCredit holds the value of the "n_credit" field.
	NCredit int `json:"n_credit,omitempty"`
	// NFinalize holds the value of the "n_finalize" field.
	NFinalize int `json:"n_finalize,omitempty"`
	// ReorgWindow holds the value of the "reorg_window" field.
	ReorgWindow int `json:"reorg_window,omitempty"`
	// ExposureCap holds the value of the "exposure_cap" field.
	ExposureCap *string `json:"exposure_cap,omitempty"`
	// TierAmount holds the value of the "tier_amount" field.
	TierAmount   *string `json:"tier_amount,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AssetConfig) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case assetconfig.FieldID, assetconfig.FieldDecimals, assetconfig.FieldNCredit, assetconfig.FieldNFinalize, assetconfig.FieldReorgWindow:
			values[i] = new(sql.NullInt64)
		case assetconfig.FieldChain, assetconfig.FieldAsset, assetconfig.FieldMode, assetconfig.FieldMinAmount, assetconfig.FieldExposureCap, assetconfig.FieldTierAmount:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AssetConfig fields.
func (_m *AssetConfig) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case assetconfig.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case assetconfig.FieldChain:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field chain", values[i])
			} else if value.Valid {
				_m.Chain = value.String
			}
		case assetconfig.FieldAsset:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field asset", values[i])
			} else if value.Valid {
				_m.Asset = value.String
			}
		case assetconfig.FieldDecimals:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field decimals", values[i])
			} else if value.Valid {
				_m.Decimals = int(value.Int64)
			}
		case assetconfig.FieldMode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field mode", values[i])
			} else if value.Valid {
				_m.Mode = assetconfig.Mode(value.String)
			}
		case assetconfig.FieldMinAmount:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field min_amount", values[i])
			} else if value.Valid {
				_m.MinAmount = value.String
			}
		case assetconfig.FieldNCredit:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field n_credit", values[i])
			} else if value.Valid {
				_m.NCredit = int(value.Int64)
			}
		case assetconfig.FieldNFinalize:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field n_finalize", values[i])
			} else if value.Valid {
				_m.NFinalize = int(value.Int64)
			}
		case assetconfig.FieldReorgWindow:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field reorg_window", values[i])
			} else if value.Valid {
				_m.ReorgWindow = int(value.Int64)
			}
		case assetconfig.FieldExposureCap:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field exposure_cap", values[i])
			} else if value.Valid {
				_m.ExposureCap = new(string)
				*_m.ExposureCap = value.String
			}
		case assetconfig.FieldTierAmount:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field tier_amount", values[i])
			} else if value.Valid {
				_m.TierAmount = new(string)
				*_m.TierAmount = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AssetConfig.
// This includes values selected through modifiers, order, etc.
func (_m *AssetConfig) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this AssetConfig.
// Note that you need to call AssetConfig.Unwrap() before calling this method if this AssetConfig
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *AssetConfig) Update() *AssetConfigUpdateOne {
	return NewAssetConfigClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the AssetConfig entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AssetConfig) Unwrap() *AssetConfig {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: AssetConfig is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AssetConfig) String() string {
	var builder strings.Builder
	builder.WriteString("AssetConfig(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("chain=")
	builder.WriteString(_m.Chain)
	builder.WriteString(", ")
	builder.WriteString("asset=")
	builder.WriteString(_m.Asset)
	builder.WriteString(", ")
	builder.WriteString("decimals=")
	builder.WriteString(fmt.Sprintf("%v", _m.Decimals))
	builder.WriteString(", ")
	builder.WriteString("mode=")
	builder.WriteString(fmt.Sprintf("%v", _m.Mode))
	builder.WriteString(", ")
	builder.WriteString("min_amount=")
	builder.WriteString(_m.MinAmount)
	builder.WriteString(", ")
	builder.WriteString("n_credit=")
	builder.WriteString(fmt.Sprintf("%v", _m.NCredit))
	builder.WriteString(", ")
	builder.WriteString("n_finalize=")
	builder.WriteString(fmt.Sprintf("%v", _m.NFinalize))
	builder.WriteString(", ")
	builder.WriteString("reorg_window=")
	builder.WriteString(fmt.Sprintf("%v", _m.ReorgWindow))
	builder.WriteString(", ")
	if v := _m.ExposureCap; v != nil {
		builder.WriteString("exposure_cap=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.TierAmount; v != nil {
		builder.WriteString("tier_amount=")
		builder.WriteString(*v)
	}
	builder.WriteByte(')')
	return builder.String()
}

// AssetConfigs is a parsable slice of AssetConfig.
type AssetConfigs []*AssetConfig
