// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"deposit-crediting/internal/store/ent/assetconfig"
	"deposit-crediting/internal/store/ent/predicate"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AssetConfigUpdate is the builder for updating AssetConfig entities.
type AssetConfigUpdate struct {
	config
	hooks    []Hook
	mutation *AssetConfigMutation
}

// Where appends a list predicates to the AssetConfigUpdate builder.
func (_u *AssetConfigUpdate) Where(ps ...predicate.AssetConfig) *AssetConfigUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetChain sets the "chain" field.
func (_u *AssetConfigUpdate) SetChain(v string) *AssetConfigUpdate {
	_u.mutation.SetChain(v)
	return _u
}

// SetNillableChain sets the "chain" field if the given value is not nil.
func (_u *AssetConfigUpdate) SetNillableChain(v *string) *AssetConfigUpdate {
	if v != nil {
		_u.SetChain(*v)
	}
	return _u
}

// SetAsset sets the "asset" field.
func (_u *AssetConfigUpdate) SetAsset(v string) *AssetConfigUpdate {
	_u.mutation.SetAsset(v)
	return _u
}

// SetNillableAsset sets the "asset" field if the given value is not nil.
func (_u *AssetConfigUpdate) SetNillableAsset(v *string) *AssetConfigUpdate {
	if v != nil {
		_u.SetAsset(*v)
	}
	return _u
}

// SetDecimals sets the "decimals" field.
func (_u *AssetConfigUpdate) SetDecimals(v int) *AssetConfigUpdate {
	_u.mutation.ResetDecimals()
	_u.mutation.SetDecimals(v)
	return _u
}

// SetNillableDecimals sets the "decimals" field if the given value is not nil.
func (_u *AssetConfigUpdate) SetNillableDecimals(v *int) *AssetConfigUpdate {
	if v != nil {
		_u.SetDecimals(*v)
	}
	return _u
}

// AddDecimals adds value to the "decimals" field.
func (_u *AssetConfigUpdate) AddDecimals(v int) *AssetConfigUpdate {
	_u.mutation.AddDecimals(v)
	return _u
}

// SetMode sets the "mode" field.
func (_u *AssetConfigUpdate) SetMode(v assetconfig.Mode) *AssetConfigUpdate {
	_u.mutation.SetMode(v)
	return _u
}

// SetNillableMode sets the "mode" field if the given value is not nil.
func (_u *AssetConfigUpdate) SetNillableMode(v *assetconfig.Mode) *AssetConfigUpdate {
	if v != nil {
		_u.SetMode(*v)
	}
	return _u
}

// SetMinAmount sets the "min_amount" field.
func (_u *AssetConfigUpdate) SetMinAmount(v string) *AssetConfigUpdate {
	_u.mutation.SetMinAmount(v)
	return _u
}

// SetNillableMinAmount sets the "min_amount" field if the given value is not nil.
func (_u *AssetConfigUpdate) SetNillableMinAmount(v *string) *AssetConfigUpdate {
	if v != nil {
		_u.SetMinAmount(*v)
	}
	return _u
}

// SetNCredit sets the "n_credit" field.
func (_u *AssetConfigUpdate) SetNCredit(v int) *AssetConfigUpdate {
	_u.mutation.ResetNCredit()
	_u.mutation.SetNCredit(v)
	return _u
}

// SetNillableNCredit sets the "n_credit" field if the given value is not nil.
func (_u *AssetConfigUpdate) SetNillableNCredit(v *int) *AssetConfigUpdate {
	if v != nil {
		_u.SetNCredit(*v)
	}
	return _u
}

// AddNCredit adds value to the "n_credit" field.
func (_u *AssetConfigUpdate) AddNCredit(v int) *AssetConfigUpdate {
	_u.mutation.AddNCredit(v)
	return _u
}

// SetNFinalize sets the "n_finalize" field.
func (_u *AssetConfigUpdate) SetNFinalize(v int) *AssetConfigUpdate {
	_u.mutation.ResetNFinalize()
	_u.mutation.SetNFinalize(v)
	return _u
}

// SetNillableNFinalize sets the "n_finalize" field if the given value is not nil.
func (_u *AssetConfigUpdate) SetNillableNFinalize(v *int) *AssetConfigUpdate {
	if v != nil {
		_u.SetNFinalize(*v)
	}
	return _u
}

// AddNFinalize adds value to the "n_finalize" field.
func (_u *AssetConfigUpdate) AddNFinalize(v int) *AssetConfigUpdate {
	_u.mutation.AddNFinalize(v)
	return _u
}

// SetReorgWindow sets the "reorg_window" field.
func (_u *AssetConfigUpdate) SetReorgWindow(v int) *AssetConfigUpdate {
	_u.mutation.ResetReorgWindow()
	_u.mutation.SetReorgWindow(v)
	return _u
}

// SetNillableReorgWindow sets the "reorg_window" field if the given value is not nil.
func (_u *AssetConfigUpdate) SetNillableReorgWindow(v *int) *AssetConfigUpdate {
	if v != nil {
		_u.SetReorgWindow(*v)
	}
	return _u
}

// AddReorgWindow adds value to the "reorg_window" field.
func (_u *AssetConfigUpdate) AddReorgWindow(v int) *AssetConfigUpdate {
	_u.mutation.AddReorgWindow(v)
	return _u
}

// SetExposureCap sets the "exposure_cap" field.
func (_u *AssetConfigUpdate) SetExposureCap(v string) *AssetConfigUpdate {
	_u.mutation.SetExposureCap(v)
	return _u
}

// SetNillableExposureCap sets the "exposure_cap" field if the given value is not nil.
func (_u *AssetConfigUpdate) SetNillableExposureCap(v *string) *AssetConfigUpdate {
	if v != nil {
		_u.SetExposureCap(*v)
	}
	return _u
}

// ClearExposureCap clears the value of the "exposure_cap" field.
func (_u *AssetConfigUpdate) ClearExposureCap() *AssetConfigUpdate {
	_u.mutation.ClearExposureCap()
	return _u
}

// SetTierAmount sets the "tier_amount" field.
func (_u *AssetConfigUpdate) SetTierAmount(v string) *AssetConfigUpdate {
	_u.mutation.SetTierAmount(v)
	return _u
}

// SetNillableTierAmount sets the "tier_amount" field if the given value is not nil.
func (_u *AssetConfigUpdate) SetNillableTierAmount(v *string) *AssetConfigUpdate {
	if v != nil {
		_u.SetTierAmount(*v)
	}
	return _u
}

// ClearTierAmount clears the value of the "tier_amount" field.
func (_u *AssetConfigUpdate) ClearTierAmount() *AssetConfigUpdate {
	_u.mutation.ClearTierAmount()
	return _u
}

// Mutation returns the AssetConfigMutation object of the builder.
func (_u *AssetConfigUpdate) Mutation() *AssetConfigMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AssetConfigUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AssetConfigUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AssetConfigUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AssetConfigUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AssetConfigUpdate) check() error {
	if v, ok := _u.mutation.Chain(); ok {
		if err := assetconfig.ChainValidator(v); err != nil {
			return &ValidationError{Name: "chain", err: fmt.Errorf(`ent: validator failed for field "AssetConfig.chain": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Asset(); ok {
		if err := assetconfig.AssetValidator(v); err != nil {
			return &ValidationError{Name: "asset", err: fmt.Errorf(`ent: validator failed for field "AssetConfig.asset": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Decimals(); ok {
		if err := assetconfig.DecimalsValidator(v); err != nil {
			return &ValidationError{Name: "decimals", err: fmt.Errorf(`ent: validator failed for field "AssetConfig.decimals": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Mode(); ok {
		if err := assetconfig.ModeValidator(v); err != nil {
			return &ValidationError{Name: "mode", err: fmt.Errorf(`ent: validator failed for field "AssetConfig.mode": %w`, err)}
		}
	}
	if v, ok := _u.mutation.NCredit(); ok {
		if err := assetconfig.NCreditValidator(v); err != nil {
			return &ValidationError{Name: "n_credit", err: fmt.Errorf(`ent: validator failed for field "AssetConfig.n_credit": %w`, err)}
		}
	}
	if v, ok := _u.mutation.NFinalize(); ok {
		if err := assetconfig.NFinalizeValidator(v); err != nil {
			return &ValidationError{Name: "n_finalize", err: fmt.Errorf(`ent: validator failed for field "AssetConfig.n_finalize": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ReorgWindow(); ok {
		if err := assetconfig.ReorgWindowValidator(v); err != nil {
			return &ValidationError{Name: "reorg_window", err: fmt.Errorf(`ent: validator failed for field "AssetConfig.reorg_window": %w`, err)}
		}
	}
	return nil
}

func (_u *AssetConfigUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(assetconfig.Table, assetconfig.Columns, sqlgraph.NewFieldSpec(assetconfig.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Chain(); ok {
		_spec.SetField(assetconfig.FieldChain, field.TypeString, value)
	}
	if value, ok := _u.mutation.Asset(); ok {
		_spec.SetField(assetconfig.FieldAsset, field.TypeString, value)
	}
	if value, ok := _u.mutation.Decimals(); ok {
		_spec.SetField(assetconfig.FieldDecimals, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDecimals(); ok {
		_spec.AddField(assetconfig.FieldDecimals, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Mode(); ok {
		_spec.SetField(assetconfig.FieldMode, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.MinAmount(); ok {
		_spec.SetField(assetconfig.FieldMinAmount, field.TypeString, value)
	}
	if value, ok := _u.mutation.NCredit(); ok {
		_spec.SetField(assetconfig.FieldNCredit, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedNCredit(); ok {
		_spec.AddField(assetconfig.FieldNCredit, field.TypeInt, value)
	}
	if value, ok := _u.mutation.NFinalize(); ok {
		_spec.SetField(assetconfig.FieldNFinalize, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedNFinalize(); ok {
		_spec.AddField(assetconfig.FieldNFinalize, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ReorgWindow(); ok {
		_spec.SetField(assetconfig.FieldReorgWindow, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedReorgWindow(); ok {
		_spec.AddField(assetconfig.FieldReorgWindow, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ExposureCap(); ok {
		_spec.SetField(assetconfig.FieldExposureCap, field.TypeString, value)
	}
	if _u.mutation.ExposureCapCleared() {
		_spec.ClearField(assetconfig.FieldExposureCap, field.TypeString)
	}
	if value, ok := _u.mutation.TierAmount(); ok {
		_spec.SetField(assetconfig.FieldTierAmount, field.TypeString, value)
	}
	if _u.mutation.TierAmountCleared() {
		_spec.ClearField(assetconfig.FieldTierAmount, field.TypeString)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{assetconfig.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AssetConfigUpdateOne is the builder for updating a single AssetConfig entity.
type AssetConfigUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AssetConfigMutation
}

// SetChain sets the "chain" field.
func (_u *AssetConfigUpdateOne) SetChain(v string) *AssetConfigUpdateOne {
	_u.mutation.SetChain(v)
	return _u
}

// SetNillableChain sets the "chain" field if the given value is not nil.
func (_u *AssetConfigUpdateOne) SetNillableChain(v *string) *AssetConfigUpdateOne {
	if v != nil {
		_u.SetChain(*v)
	}
	return _u
}

// SetAsset sets the "asset" field.
func (_u *AssetConfigUpdateOne) SetAsset(v string) *AssetConfigUpdateOne {
	_u.mutation.SetAsset(v)
	return _u
}

// SetNillableAsset sets the "asset" field if the given value is not nil.
func (_u *AssetConfigUpdateOne) SetNillableAsset(v *string) *AssetConfigUpdateOne {
	if v != nil {
		_u.SetAsset(*v)
	}
	return _u
}

// SetDecimals sets the "decimals" field.
func (_u *AssetConfigUpdateOne) SetDecimals(v int) *AssetConfigUpdateOne {
	_u.mutation.ResetDecimals()
	_u.mutation.SetDecimals(v)
	return _u
}

// SetNillableDecimals sets the "decimals" field if the given value is not nil.
func (_u *AssetConfigUpdateOne) SetNillableDecimals(v *int) *AssetConfigUpdateOne {
	if v != nil {
		_u.SetDecimals(*v)
	}
	return _u
}

// AddDecimals adds value to the "decimals" field.
func (_u *AssetConfigUpdateOne) AddDecimals(v int) *AssetConfigUpdateOne {
	_u.mutation.AddDecimals(v)
	return _u
}

// SetMode sets the "mode" field.
func (_u *AssetConfigUpdateOne) SetMode(v assetconfig.Mode) *AssetConfigUpdateOne {
	_u.mutation.SetMode(v)
	return _u
}

// SetNillableMode sets the "mode" field if the given value is not nil.
func (_u *AssetConfigUpdateOne) SetNillableMode(v *assetconfig.Mode) *AssetConfigUpdateOne {
	if v != nil {
		_u.SetMode(*v)
	}
	return _u
}

// SetMinAmount sets the "min_amount" field.
func (_u *AssetConfigUpdateOne) SetMinAmount(v string) *AssetConfigUpdateOne {
	_u.mutation.SetMinAmount(v)
	return _u
}

// SetNillableMinAmount sets the "min_amount" field if the given value is not nil.
func (_u *AssetConfigUpdateOne) SetNillableMinAmount(v *string) *AssetConfigUpdateOne {
	if v != nil {
		_u.SetMinAmount(*v)
	}
	return _u
}

// SetNCredit sets the "n_credit" field.
func (_u *AssetConfigUpdateOne) SetNCredit(v int) *AssetConfigUpdateOne {
	_u.mutation.ResetNCredit()
	_u.mutation.SetNCredit(v)
	return _u
}

// SetNillableNCredit sets the "n_credit" field if the given value is not nil.
func (_u *AssetConfigUpdateOne) SetNillableNCredit(v *int) *AssetConfigUpdateOne {
	if v != nil {
		_u.SetNCredit(*v)
	}
	return _u
}

// AddNCredit adds value to the "n_credit" field.
func (_u *AssetConfigUpdateOne) AddNCredit(v int) *AssetConfigUpdateOne {
	_u.mutation.AddNCredit(v)
	return _u
}

// SetNFinalize sets the "n_finalize" field.
func (_u *AssetConfigUpdateOne) SetNFinalize(v int) *AssetConfigUpdateOne {
	_u.mutation.ResetNFinalize()
	_u.mutation.SetNFinalize(v)
	return _u
}

// SetNillableNFinalize sets the "n_finalize" field if the given value is not nil.
func (_u *AssetConfigUpdateOne) SetNillableNFinalize(v *int) *AssetConfigUpdateOne {
	if v != nil {
		_u.SetNFinalize(*v)
	}
	return _u
}

// AddNFinalize adds value to the "n_finalize" field.
func (_u *AssetConfigUpdateOne) AddNFinalize(v int) *AssetConfigUpdateOne {
	_u.mutation.AddNFinalize(v)
	return _u
}

// SetReorgWindow sets the "reorg_window" field.
func (_u *AssetConfigUpdateOne) SetReorgWindow(v int) *AssetConfigUpdateOne {
	_u.mutation.ResetReorgWindow()
	_u.mutation.SetReorgWindow(v)
	return _u
}

// SetNillableReorgWindow sets the "reorg_window" field if the given value is not nil.
func (_u *AssetConfigUpdateOne) SetNillableReorgWindow(v *int) *AssetConfigUpdateOne {
	if v != nil {
		_u.SetReorgWindow(*v)
	}
	return _u
}

// AddReorgWindow adds value to the "reorg_window" field.
func (_u *AssetConfigUpdateOne) AddReorgWindow(v int) *AssetConfigUpdateOne {
	_u.mutation.AddReorgWindow(v)
	return _u
}

// SetExposureCap sets the "exposure_cap" field.
func (_u *AssetConfigUpdateOne) SetExposureCap(v string) *AssetConfigUpdateOne {
	_u.mutation.SetExposureCap(v)
	return _u
}

// SetNillableExposureCap sets the "exposure_cap" field if the given value is not nil.
func (_u *AssetConfigUpdateOne) SetNillableExposureCap(v *string) *AssetConfigUpdateOne {
	if v != nil {
		_u.SetExposureCap(*v)
	}
	return _u
}

// ClearExposureCap clears the value of the "exposure_cap" field.
func (_u *AssetConfigUpdateOne) ClearExposureCap() *AssetConfigUpdateOne {
	_u.mutation.ClearExposureCap()
	return _u
}

// SetTierAmount sets the "tier_amount" field.
func (_u *AssetConfigUpdateOne) SetTierAmount(v string) *AssetConfigUpdateOne {
	_u.mutation.SetTierAmount(v)
	return _u
}

// SetNillableTierAmount sets the "tier_amount" field if the given value is not nil.
func (_u *AssetConfigUpdateOne) SetNillableTierAmount(v *string) *AssetConfigUpdateOne {
	if v != nil {
		_u.SetTierAmount(*v)
	}
	return _u
}

// ClearTierAmount clears the value of the "tier_amount" field.
func (_u *AssetConfigUpdateOne) ClearTierAmount() *AssetConfigUpdateOne {
	_u.mutation.ClearTierAmount()
	return _u
}

// Mutation returns the AssetConfigMutation object of the builder.
func (_u *AssetConfigUpdateOne) Mutation() *AssetConfigMutation {
	return _u.mutation
}

// Where appends a list predicates to the AssetConfigUpdate builder.
func (_u *AssetConfigUpdateOne) Where(ps ...predicate.AssetConfig) *AssetConfigUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AssetConfigUpdateOne) Select(field string, fields ...string) *AssetConfigUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AssetConfig entity.
func (_u *AssetConfigUpdateOne) Save(ctx context.Context) (*AssetConfig, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AssetConfigUpdateOne) SaveX(ctx context.Context) *AssetConfig {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AssetConfigUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AssetConfigUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AssetConfigUpdateOne) check() error {
	if v, ok := _u.mutation.Chain(); ok {
		if err := assetconfig.ChainValidator(v); err != nil {
			return &ValidationError{Name: "chain", err: fmt.Errorf(`ent: validator failed for field "AssetConfig.chain": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Asset(); ok {
		if err := assetconfig.AssetValidator(v); err != nil {
			return &ValidationError{Name: "asset", err: fmt.Errorf(`ent: validator failed for field "AssetConfig.asset": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Decimals(); ok {
		if err := assetconfig.DecimalsValidator(v); err != nil {
			return &ValidationError{Name: "decimals", err: fmt.Errorf(`ent: validator failed for field "AssetConfig.decimals": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Mode(); ok {
		if err := assetconfig.ModeValidator(v); err != nil {
			return &ValidationError{Name: "mode", err: fmt.Errorf(`ent: validator failed for field "AssetConfig.mode": %w`, err)}
		}
	}
	if v, ok := _u.mutation.NCredit(); ok {
		if err := assetconfig.NCreditValidator(v); err != nil {
			return &ValidationError{Name: "n_credit", err: fmt.Errorf(`ent: validator failed for field "AssetConfig.n_credit": %w`, err)}
		}
	}
	if v, ok := _u.mutation.NFinalize(); ok {
		if err := assetconfig.NFinalizeValidator(v); err != nil {
			return &ValidationError{Name: "n_finalize", err: fmt.Errorf(`ent: validator failed for field "AssetConfig.n_finalize": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ReorgWindow(); ok {
		if err := assetconfig.ReorgWindowValidator(v); err != nil {
			return &ValidationError{Name: "reorg_window", err: fmt.Errorf(`ent: validator failed for field "AssetConfig.reorg_window": %w`, err)}
		}
	}
	return nil
}

func (_u *AssetConfigUpdateOne) sqlSave(ctx context.Context) (_node *AssetConfig, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(assetconfig.Table, assetconfig.Columns, sqlgraph.NewFieldSpec(assetconfig.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AssetConfig.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, assetconfig.FieldID)
		for _, f := range fields {
			if !assetconfig.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != assetconfig.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Chain(); ok {
		_spec.SetField(assetconfig.FieldChain, field.TypeString, value)
	}
	if value, ok := _u.mutation.Asset(); ok {
		_spec.SetField(assetconfig.FieldAsset, field.TypeString, value)
	}
	if value, ok := _u.mutation.Decimals(); ok {
		_spec.SetField(assetconfig.FieldDecimals, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDecimals(); ok {
		_spec.AddField(assetconfig.FieldDecimals, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Mode(); ok {
		_spec.SetField(assetconfig.FieldMode, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.MinAmount(); ok {
		_spec.SetField(assetconfig.FieldMinAmount, field.TypeString, value)
	}
	if value, ok := _u.mutation.NCredit(); ok {
		_spec.SetField(assetconfig.FieldNCredit, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedNCredit(); ok {
		_spec.AddField(assetconfig.FieldNCredit, field.TypeInt, value)
	}
	if value, ok := _u.mutation.NFinalize(); ok {
		_spec.SetField(assetconfig.FieldNFinalize, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedNFinalize(); ok {
		_spec.AddField(assetconfig.FieldNFinalize, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ReorgWindow(); ok {
		_spec.SetField(assetconfig.FieldReorgWindow, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedReorgWindow(); ok {
		_spec.AddField(assetconfig.FieldReorgWindow, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ExposureCap(); ok {
		_spec.SetField(assetconfig.FieldExposureCap, field.TypeString, value)
	}
	if _u.mutation.ExposureCapCleared() {
		_spec.ClearField(assetconfig.FieldExposureCap, field.TypeString)
	}
	if value, ok := _u.mutation.TierAmount(); ok {
		_spec.SetField(assetconfig.FieldTierAmount, field.TypeString, value)
	}
	if _u.mutation.TierAmountCleared() {
		_spec.ClearField(assetconfig.FieldTierAmount, field.TypeString)
	}
	_node = &AssetConfig{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{assetconfig.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
