// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"deposit-crediting/internal/store/ent/assetconfig"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AssetConfigCreate is the builder for creating a AssetConfig entity.
type AssetConfigCreate struct {
	config
	mutation *AssetConfigMutation
	hooks    []Hook
}

// SetChain sets the "chain" field.
func (_c *AssetConfigCreate) SetChain(v string) *AssetConfigCreate {
	_c.mutation.SetChain(v)
	return _c
}

// SetAsset sets the "asset" field.
func (_c *AssetConfigCreate) SetAsset(v string) *AssetConfigCreate {
	_c.mutation.SetAsset(v)
	return _c
}

// SetDecimals sets the "decimals" field.
func (_c *AssetConfigCreate) SetDecimals(v int) *AssetConfigCreate {
	_c.mutation.SetDecimals(v)
	return _c
}

// SetMode sets the "mode" field.
func (_c *AssetConfigCreate) SetMode(v assetconfig.Mode) *AssetConfigCreate {
	_c.mutation.SetMode(v)
	return _c
}

// SetMinAmount sets the "min_amount" field.
func (_c *AssetConfigCreate) SetMinAmount(v string) *AssetConfigCreate {
	_c.mutation.SetMinAmount(v)
	return _c
}

// SetNillableMinAmount sets the "min_amount" field if the given value is not nil.
func (_c *AssetConfigCreate) SetNillableMinAmount(v *string) *AssetConfigCreate {
	if v != nil {
		_c.SetMinAmount(*v)
	}
	return _c
}

// SetNCredit sets the "n_credit" field.
func (_c *AssetConfigCreate) SetNCredit(v int) *AssetConfigCreate {
	_c.mutation.SetNCredit(v)
	return _c
}

// SetNFinalize sets the "n_finalize" field.
func (_c *AssetConfigCreate) SetNFinalize(v int) *AssetConfigCreate {
	_c.mutation.SetNFinalize(v)
	return _c
}

// SetReorgWindow sets the "reorg_window" field.
func (_c *AssetConfigCreate) SetReorgWindow(v int) *AssetConfigCreate {
	_c.mutation.SetReorgWindow(v)
	return _c
}

// SetExposureCap sets the "exposure_cap" field.
func (_c *AssetConfigCreate) SetExposureCap(v string) *AssetConfigCreate {
	_c.mutation.SetExposureCap(v)
	return _c
}

// SetNillableExposureCap sets the "exposure_cap" field if the given value is not nil.
func (_c *AssetConfigCreate) SetNillableExposureCap(v *string) *AssetConfigCreate {
	if v != nil {
		_c.SetExposureCap(*v)
	}
	return _c
}

// SetTierAmount sets the "tier_amount" field.
func (_c *AssetConfigCreate) SetTierAmount(v string) *AssetConfigCreate {
	_c.mutation.SetTierAmount(v)
	return _c
}

// SetNillableTierAmount sets the "tier_amount" field if the given value is not nil.
func (_c *AssetConfigCreate) SetNillableTierAmount(v *string) *AssetConfigCreate {
	if v != nil {
		_c.SetTierAmount(*v)
	}
	return _c
}

// Mutation returns the AssetConfigMutation object of the builder.
func (_c *AssetConfigCreate) Mutation() *AssetConfigMutation {
	return _c.mutation
}

// Save creates the AssetConfig in the database.
func (_c *AssetConfigCreate) Save(ctx context.Context) (*AssetConfig, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AssetConfigCreate) SaveX(ctx context.Context) *AssetConfig {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AssetConfigCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AssetConfigCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AssetConfigCreate) defaults() {
	if _, ok := _c.mutation.MinAmount(); !ok {
		v := assetconfig.DefaultMinAmount
		_c.mutation.SetMinAmount(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AssetConfigCreate) check() error {
	if _, ok := _c.mutation.Chain(); !ok {
		return &ValidationError{Name: "chain", err: errors.New(`ent: missing required field "AssetConfig.chain"`)}
	}
	if v, ok := _c.mutation.Chain(); ok {
		if err := assetconfig.ChainValidator(v); err != nil {
			return &ValidationError{Name: "chain", err: fmt.Errorf(`ent: validator failed for field "AssetConfig.chain": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Asset(); !ok {
		return &ValidationError{Name: "asset", err: errors.New(`ent: missing required field "AssetConfig.asset"`)}
	}
	if v, ok := _c.mutation.Asset(); ok {
		if err := assetconfig.AssetValidator(v); err != nil {
			return &ValidationError{Name: "asset", err: fmt.Errorf(`ent: validator failed for field "AssetConfig.asset": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Decimals(); !ok {
		return &ValidationError{Name: "decimals", err: errors.New(`ent: missing required field "AssetConfig.decimals"`)}
	}
	if v, ok := _c.mutation.Decimals(); ok {
		if err := assetconfig.DecimalsValidator(v); err != nil {
			return &ValidationError{Name: "decimals", err: fmt.Errorf(`ent: validator failed for field "AssetConfig.decimals": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Mode(); !ok {
		return &ValidationError{Name: "mode", err: errors.New(`ent: missing required field "AssetConfig.mode"`)}
	}
	if v, ok := _c.mutation.Mode(); ok {
		if err := assetconfig.ModeValidator(v); err != nil {
			return &ValidationError{Name: "mode", err: fmt.Errorf(`ent: validator failed for field "AssetConfig.mode": %w`, err)}
		}
	}
	if _, ok := _c.mutation.MinAmount(); !ok {
		return &ValidationError{Name: "min_amount", err: errors.New(`ent: missing required field "AssetConfig.min_amount"`)}
	}
	if _, ok := _c.mutation.NCredit(); !ok {
		return &ValidationError{Name: "n_credit", err: errors.New(`ent: missing required field "AssetConfig.n_credit"`)}
	}
	if v, ok := _c.mutation.NCredit(); ok {
		if err := assetconfig.NCreditValidator(v); err != nil {
			return &ValidationError{Name: "n_credit", err: fmt.Errorf(`ent: validator failed for field "AssetConfig.n_credit": %w`, err)}
		}
	}
	if _, ok := _c.mutation.NFinalize(); !ok {
		return &ValidationError{Name: "n_finalize", err: errors.New(`ent: missing required field "AssetConfig.n_finalize"`)}
	}
	if v, ok := _c.mutation.NFinalize(); ok {
		if err := assetconfig.NFinalizeValidator(v); err != nil {
			return &ValidationError{Name: "n_finalize", err: fmt.Errorf(`ent: validator failed for field "AssetConfig.n_finalize": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ReorgWindow(); !ok {
		return &ValidationError{Name: "reorg_window", err: errors.New(`ent: missing required field "AssetConfig.reorg_window"`)}
	}
	if v, ok := _c.mutation.ReorgWindow(); ok {
		if err := assetconfig.ReorgWindowValidator(v); err != nil {
			return &ValidationError{Name: "reorg_window", err: fmt.Errorf(`ent: validator failed for field "AssetConfig.reorg_window": %w`, err)}
		}
	}
	return nil
}

func (_c *AssetConfigCreate) sqlSave(ctx context.Context) (*AssetConfig, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AssetConfigCreate) createSpec() (*AssetConfig, *sqlgraph.CreateSpec) {
	var (
		_node = &AssetConfig{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(assetconfig.Table, sqlgraph.NewFieldSpec(assetconfig.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Chain(); ok {
		_spec.SetField(assetconfig.FieldChain, field.TypeString, value)
		_node.Chain = value
	}
	if value, ok := _c.mutation.Asset(); ok {
		_spec.SetField(assetconfig.FieldAsset, field.TypeString, value)
		_node.Asset = value
	}
	if value, ok := _c.mutation.Decimals(); ok {
		_spec.SetField(assetconfig.FieldDecimals, field.TypeInt, value)
		_node.Decimals = value
	}
	if value, ok := _c.mutation.Mode(); ok {
		_spec.SetField(assetconfig.FieldMode, field.TypeEnum, value)
		_node.Mode = value
	}
	if value, ok := _c.mutation.MinAmount(); ok {
		_spec.SetField(assetconfig.FieldMinAmount, field.TypeString, value)
		_node.MinAmount = value
	}
	if value, ok := _c.mutation.NCredit(); ok {
		_spec.SetField(assetconfig.FieldNCredit, field.TypeInt, value)
		_node.NCredit = value
	}
	if value, ok := _c.mutation.NFinalize(); ok {
		_spec.SetField(assetconfig.FieldNFinalize, field.TypeInt, value)
		_node.NFinalize = value
	}
	if value, ok := _c.mutation.ReorgWindow(); ok {
		_spec.SetField(assetconfig.FieldReorgWindow, field.TypeInt, value)
		_node.ReorgWindow = value
	}
	if value, ok := _c.mutation.ExposureCap(); ok {
		_spec.SetField(assetconfig.FieldExposureCap, field.TypeString, value)
		_node.ExposureCap = &value
	}
	if value, ok := _c.mutation.TierAmount(); ok {
		_spec.SetField(assetconfig.FieldTierAmount, field.TypeString, value)
		_node.TierAmount = &value
	}
	return _node, _spec
}

// AssetConfigCreateBulk is the builder for creating many AssetConfig entities in bulk.
type AssetConfigCreateBulk struct {
	config
	err      error
	builders []*AssetConfigCreate
}

// Save creates the AssetConfig entities in the database.
func (_c *AssetConfigCreateBulk) Save(ctx context.Context) ([]*AssetConfig, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AssetConfig, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AssetConfigMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AssetConfigCreateBulk) SaveX(ctx context.Context) []*AssetConfig {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AssetConfigCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AssetConfigCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
