// Code generated by ent, DO NOT EDIT.

package ent

import (
	"deposit-crediting/internal/store/ent/canonicalblock"
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// CanonicalBlock is the model entity for the CanonicalBlock schema.
type CanonicalBlock struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Chain holds the value of the "chain" field.
	Chain string `json:"chain,omitempty"`
	// Height holds the value of the "height" field.
	Height int64 `json:"height,omitempty"`
	// Hash holds the value of the "hash" field.
	Hash         string `json:"hash,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*CanonicalBlock) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case canonicalblock.FieldID, canonicalblock.FieldHeight:
			values[i] = new(sql.NullInt64)
		case canonicalblock.FieldChain, canonicalblock.FieldHash:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the CanonicalBlock fields.
func (_m *CanonicalBlock) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case canonicalblock.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case canonicalblock.FieldChain:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field chain", values[i])
			} else if value.Valid {
				_m.Chain = value.String
			}
		case canonicalblock.FieldHeight:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field height", values[i])
			} else if value.Valid {
				_m.Height = value.Int64
			}
		case canonicalblock.FieldHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field hash", values[i])
			} else if value.Valid {
				_m.Hash = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the CanonicalBlock.
// This includes values selected through modifiers, order, etc.
func (_m *CanonicalBlock) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this CanonicalBlock.
// Note that you need to call CanonicalBlock.Unwrap() before calling this method if this CanonicalBlock
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *CanonicalBlock) Update() *CanonicalBlockUpdateOne {
	return NewCanonicalBlockClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the CanonicalBlock entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *CanonicalBlock) Unwrap() *CanonicalBlock {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: CanonicalBlock is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *CanonicalBlock) String() string {
	var builder strings.Builder
	builder.WriteString("CanonicalBlock(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("chain=")
	builder.WriteString(_m.Chain)
	builder.WriteString(", ")
	builder.WriteString("height=")
	builder.WriteString(fmt.Sprintf("%v", _m.Height))
	builder.WriteString(", ")
	builder.WriteString("hash=")
	builder.WriteString(_m.Hash)
	builder.WriteByte(')')
	return builder.String()
}

// CanonicalBlocks is a parsable slice of CanonicalBlock.
type CanonicalBlocks []*CanonicalBlock
