// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"deposit-crediting/internal/store/ent/canonicalblock"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CanonicalBlockCreate is the builder for creating a CanonicalBlock entity.
type CanonicalBlockCreate struct {
	config
	mutation *CanonicalBlockMutation
	hooks    []Hook
}

// SetChain sets the "chain" field.
func (_c *CanonicalBlockCreate) SetChain(v string) *CanonicalBlockCreate {
	_c.mutation.SetChain(v)
	return _c
}

// SetHeight sets the "height" field.
func (_c *CanonicalBlockCreate) SetHeight(v int64) *CanonicalBlockCreate {
	_c.mutation.SetHeight(v)
	return _c
}

// SetHash sets the "hash" field.
func (_c *CanonicalBlockCreate) SetHash(v string) *CanonicalBlockCreate {
	_c.mutation.SetHash(v)
	return _c
}

// Mutation returns the CanonicalBlockMutation object of the builder.
func (_c *CanonicalBlockCreate) Mutation() *CanonicalBlockMutation {
	return _c.mutation
}

// Save creates the CanonicalBlock in the database.
func (_c *CanonicalBlockCreate) Save(ctx context.Context) (*CanonicalBlock, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CanonicalBlockCreate) SaveX(ctx context.Context) *CanonicalBlock {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CanonicalBlockCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CanonicalBlockCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CanonicalBlockCreate) check() error {
	if _, ok := _c.mutation.Chain(); !ok {
		return &ValidationError{Name: "chain", err: errors.New(`ent: missing required field "CanonicalBlock.chain"`)}
	}
	if v, ok := _c.mutation.Chain(); ok {
		if err := canonicalblock.ChainValidator(v); err != nil {
			return &ValidationError{Name: "chain", err: fmt.Errorf(`ent: validator failed for field "CanonicalBlock.chain": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Height(); !ok {
		return &ValidationError{Name: "height", err: errors.New(`ent: missing required field "CanonicalBlock.height"`)}
	}
	if v, ok := _c.mutation.Height(); ok {
		if err := canonicalblock.HeightValidator(v); err != nil {
			return &ValidationError{Name: "height", err: fmt.Errorf(`ent: validator failed for field "CanonicalBlock.height": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Hash(); !ok {
		return &ValidationError{Name: "hash", err: errors.New(`ent: missing required field "CanonicalBlock.hash"`)}
	}
	if v, ok := _c.mutation.Hash(); ok {
		if err := canonicalblock.HashValidator(v); err != nil {
			return &ValidationError{Name: "hash", err: fmt.Errorf(`ent: validator failed for field "CanonicalBlock.hash": %w`, err)}
		}
	}
	return nil
}

func (_c *CanonicalBlockCreate) sqlSave(ctx context.Context) (*CanonicalBlock, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CanonicalBlockCreate) createSpec() (*CanonicalBlock, *sqlgraph.CreateSpec) {
	var (
		_node = &CanonicalBlock{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(canonicalblock.Table, sqlgraph.NewFieldSpec(canonicalblock.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Chain(); ok {
		_spec.SetField(canonicalblock.FieldChain, field.TypeString, value)
		_node.Chain = value
	}
	if value, ok := _c.mutation.Height(); ok {
		_spec.SetField(canonicalblock.FieldHeight, field.TypeInt64, value)
		_node.Height = value
	}
	if value, ok := _c.mutation.Hash(); ok {
		_spec.SetField(canonicalblock.FieldHash, field.TypeString, value)
		_node.Hash = value
	}
	return _node, _spec
}

// CanonicalBlockCreateBulk is the builder for creating many CanonicalBlock entities in bulk.
type CanonicalBlockCreateBulk struct {
	config
	err      error
	builders []*CanonicalBlockCreate
}

// Save creates the CanonicalBlock entities in the database.
func (_c *CanonicalBlockCreateBulk) Save(ctx context.Context) ([]*CanonicalBlock, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*CanonicalBlock, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CanonicalBlockMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CanonicalBlockCreateBulk) SaveX(ctx context.Context) []*CanonicalBlock {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CanonicalBlockCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CanonicalBlockCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
