// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"deposit-crediting/internal/store/ent/canonicalblock"
	"deposit-crediting/internal/store/ent/predicate"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CanonicalBlockUpdate is the builder for updating CanonicalBlock entities.
type CanonicalBlockUpdate struct {
	config
	hooks    []Hook
	mutation *CanonicalBlockMutation
}

// Where appends a list predicates to the CanonicalBlockUpdate builder.
func (_u *CanonicalBlockUpdate) Where(ps ...predicate.CanonicalBlock) *CanonicalBlockUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetChain sets the "chain" field.
func (_u *CanonicalBlockUpdate) SetChain(v string) *CanonicalBlockUpdate {
	_u.mutation.SetChain(v)
	return _u
}

// SetNillableChain sets the "chain" field if the given value is not nil.
func (_u *CanonicalBlockUpdate) SetNillableChain(v *string) *CanonicalBlockUpdate {
	if v != nil {
		_u.SetChain(*v)
	}
	return _u
}

// SetHeight sets the "height" field.
func (_u *CanonicalBlockUpdate) SetHeight(v int64) *CanonicalBlockUpdate {
	_u.mutation.ResetHeight()
	_u.mutation.SetHeight(v)
	return _u
}

// SetNillableHeight sets the "height" field if the given value is not nil.
func (_u *CanonicalBlockUpdate) SetNillableHeight(v *int64) *CanonicalBlockUpdate {
	if v != nil {
		_u.SetHeight(*v)
	}
	return _u
}

// AddHeight adds value to the "height" field.
func (_u *CanonicalBlockUpdate) AddHeight(v int64) *CanonicalBlockUpdate {
	_u.mutation.AddHeight(v)
	return _u
}

// SetHash sets the "hash" field.
func (_u *CanonicalBlockUpdate) SetHash(v string) *CanonicalBlockUpdate {
	_u.mutation.SetHash(v)
	return _u
}

// SetNillableHash sets the "hash" field if the given value is not nil.
func (_u *CanonicalBlockUpdate) SetNillableHash(v *string) *CanonicalBlockUpdate {
	if v != nil {
		_u.SetHash(*v)
	}
	return _u
}

// Mutation returns the CanonicalBlockMutation object of the builder.
func (_u *CanonicalBlockUpdate) Mutation() *CanonicalBlockMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CanonicalBlockUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CanonicalBlockUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CanonicalBlockUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CanonicalBlockUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CanonicalBlockUpdate) check() error {
	if v, ok := _u.mutation.Chain(); ok {
		if err := canonicalblock.ChainValidator(v); err != nil {
			return &ValidationError{Name: "chain", err: fmt.Errorf(`ent: validator failed for field "CanonicalBlock.chain": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Height(); ok {
		if err := canonicalblock.HeightValidator(v); err != nil {
			return &ValidationError{Name: "height", err: fmt.Errorf(`ent: validator failed for field "CanonicalBlock.height": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Hash(); ok {
		if err := canonicalblock.HashValidator(v); err != nil {
			return &ValidationError{Name: "hash", err: fmt.Errorf(`ent: validator failed for field "CanonicalBlock.hash": %w`, err)}
		}
	}
	return nil
}

func (_u *CanonicalBlockUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(canonicalblock.Table, canonicalblock.Columns, sqlgraph.NewFieldSpec(canonicalblock.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Chain(); ok {
		_spec.SetField(canonicalblock.FieldChain, field.TypeString, value)
	}
	if value, ok := _u.mutation.Height(); ok {
		_spec.SetField(canonicalblock.FieldHeight, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedHeight(); ok {
		_spec.AddField(canonicalblock.FieldHeight, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Hash(); ok {
		_spec.SetField(canonicalblock.FieldHash, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{canonicalblock.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CanonicalBlockUpdateOne is the builder for updating a single CanonicalBlock entity.
type CanonicalBlockUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CanonicalBlockMutation
}

// SetChain sets the "chain" field.
func (_u *CanonicalBlockUpdateOne) SetChain(v string) *CanonicalBlockUpdateOne {
	_u.mutation.SetChain(v)
	return _u
}

// SetNillableChain sets the "chain" field if the given value is not nil.
func (_u *CanonicalBlockUpdateOne) SetNillableChain(v *string) *CanonicalBlockUpdateOne {
	if v != nil {
		_u.SetChain(*v)
	}
	return _u
}

// SetHeight sets the "height" field.
func (_u *CanonicalBlockUpdateOne) SetHeight(v int64) *CanonicalBlockUpdateOne {
	_u.mutation.ResetHeight()
	_u.mutation.SetHeight(v)
	return _u
}

// SetNillableHeight sets the "height" field if the given value is not nil.
func (_u *CanonicalBlockUpdateOne) SetNillableHeight(v *int64) *CanonicalBlockUpdateOne {
	if v != nil {
		_u.SetHeight(*v)
	}
	return _u
}

// AddHeight adds value to the "height" field.
func (_u *CanonicalBlockUpdateOne) AddHeight(v int64) *CanonicalBlockUpdateOne {
	_u.mutation.AddHeight(v)
	return _u
}

// SetHash sets the "hash" field.
func (_u *CanonicalBlockUpdateOne) SetHash(v string) *CanonicalBlockUpdateOne {
	_u.mutation.SetHash(v)
	return _u
}

// SetNillableHash sets the "hash" field if the given value is not nil.
func (_u *CanonicalBlockUpdateOne) SetNillableHash(v *string) *CanonicalBlockUpdateOne {
	if v != nil {
		_u.SetHash(*v)
	}
	return _u
}

// Mutation returns the CanonicalBlockMutation object of the builder.
func (_u *CanonicalBlockUpdateOne) Mutation() *CanonicalBlockMutation {
	return _u.mutation
}

// Where appends a list predicates to the CanonicalBlockUpdate builder.
func (_u *CanonicalBlockUpdateOne) Where(ps ...predicate.CanonicalBlock) *CanonicalBlockUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CanonicalBlockUpdateOne) Select(field string, fields ...string) *CanonicalBlockUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated CanonicalBlock entity.
func (_u *CanonicalBlockUpdateOne) Save(ctx context.Context) (*CanonicalBlock, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CanonicalBlockUpdateOne) SaveX(ctx context.Context) *CanonicalBlock {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CanonicalBlockUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CanonicalBlockUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CanonicalBlockUpdateOne) check() error {
	if v, ok := _u.mutation.Chain(); ok {
		if err := canonicalblock.ChainValidator(v); err != nil {
			return &ValidationError{Name: "chain", err: fmt.Errorf(`ent: validator failed for field "CanonicalBlock.chain": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Height(); ok {
		if err := canonicalblock.HeightValidator(v); err != nil {
			return &ValidationError{Name: "height", err: fmt.Errorf(`ent: validator failed for field "CanonicalBlock.height": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Hash(); ok {
		if err := canonicalblock.HashValidator(v); err != nil {
			return &ValidationError{Name: "hash", err: fmt.Errorf(`ent: validator failed for field "CanonicalBlock.hash": %w`, err)}
		}
	}
	return nil
}

func (_u *CanonicalBlockUpdateOne) sqlSave(ctx context.Context) (_node *CanonicalBlock, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(canonicalblock.Table, canonicalblock.Columns, sqlgraph.NewFieldSpec(canonicalblock.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "CanonicalBlock.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, canonicalblock.FieldID)
		for _, f := range fields {
			if !canonicalblock.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != canonicalblock.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Chain(); ok {
		_spec.SetField(canonicalblock.FieldChain, field.TypeString, value)
	}
	if value, ok := _u.mutation.Height(); ok {
		_spec.SetField(canonicalblock.FieldHeight, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedHeight(); ok {
		_spec.AddField(canonicalblock.FieldHeight, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Hash(); ok {
		_spec.SetField(canonicalblock.FieldHash, field.TypeString, value)
	}
	_node = &CanonicalBlock{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{canonicalblock.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
