// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"deposit-crediting/internal/store/ent/migrate"

	"deposit-crediting/internal/store/ent/accountbalance"
	"deposit-crediting/internal/store/ent/assetconfig"
	"deposit-crediting/internal/store/ent/canonicalblock"
	"deposit-crediting/internal/store/ent/chaincursor"
	"deposit-crediting/internal/store/ent/deposit"
	"deposit-crediting/internal/store/ent/depositaddress"
	"deposit-crediting/internal/store/ent/exposurestate"
	"deposit-crediting/internal/store/ent/ledgerentry"
	"deposit-crediting/internal/store/ent/sourceevent"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// AccountBalance is the client for interacting with the AccountBalance builders.
	AccountBalance *AccountBalanceClient
	// AssetConfig is the client for interacting with the AssetConfig builders.
	AssetConfig *AssetConfigClient
	// CanonicalBlock is the client for interacting with the CanonicalBlock builders.
	CanonicalBlock *CanonicalBlockClient
	// ChainCursor is the client for interacting with the ChainCursor builders.
	ChainCursor *ChainCursorClient
	// Deposit is the client for interacting with the Deposit builders.
	Deposit *DepositClient
	// DepositAddress is the client for interacting with the DepositAddress builders.
	DepositAddress *DepositAddressClient
	// ExposureState is the client for interacting with the ExposureState builders.
	ExposureState *ExposureStateClient
	// LedgerEntry is the client for interacting with the LedgerEntry builders.
	LedgerEntry *LedgerEntryClient
	// SourceEvent is the client for interacting with the SourceEvent builders.
	SourceEvent *SourceEventClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.AccountBalance = NewAccountBalanceClient(c.config)
	c.AssetConfig = NewAssetConfigClient(c.config)
	c.CanonicalBlock = NewCanonicalBlockClient(c.config)
	c.ChainCursor = NewChainCursorClient(c.config)
	c.Deposit = NewDepositClient(c.config)
	c.DepositAddress = NewDepositAddressClient(c.config)
	c.ExposureState = NewExposureStateClient(c.config)
	c.LedgerEntry = NewLedgerEntryClient(c.config)
	c.SourceEvent = NewSourceEventClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:            ctx,
		config:         cfg,
		AccountBalance: NewAccountBalanceClient(cfg),
		AssetConfig:    NewAssetConfigClient(cfg),
		CanonicalBlock: NewCanonicalBlockClient(cfg),
		ChainCursor:    NewChainCursorClient(cfg),
		Deposit:        NewDepositClient(cfg),
		DepositAddress: NewDepositAddressClient(cfg),
		ExposureState:  NewExposureStateClient(cfg),
		LedgerEntry:    NewLedgerEntryClient(cfg),
		SourceEvent:    NewSourceEventClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:            ctx,
		config:         cfg,
		AccountBalance: NewAccountBalanceClient(cfg),
		AssetConfig:    NewAssetConfigClient(cfg),
		CanonicalBlock: NewCanonicalBlockClient(cfg),
		ChainCursor:    NewChainCursorClient(cfg),
		Deposit:        NewDepositClient(cfg),
		DepositAddress: NewDepositAddressClient(cfg),
		ExposureState:  NewExposureStateClient(cfg),
		LedgerEntry:    NewLedgerEntryClient(cfg),
		SourceEvent:    NewSourceEventClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		AccountBalance.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	for _, n := range []interface{ Use(...Hook) }{
		c.AccountBalance, c.AssetConfig, c.CanonicalBlock, c.ChainCursor, c.Deposit,
		c.DepositAddress, c.ExposureState, c.LedgerEntry, c.SourceEvent,
	} {
		n.Use(hooks...)
	}
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	for _, n := range []interface{ Intercept(...Interceptor) }{
		c.AccountBalance, c.AssetConfig, c.CanonicalBlock, c.ChainCursor, c.Deposit,
		c.DepositAddress, c.ExposureState, c.LedgerEntry, c.SourceEvent,
	} {
		n.Intercept(interceptors...)
	}
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *AccountBalanceMutation:
		return c.AccountBalance.mutate(ctx, m)
	case *AssetConfigMutation:
		return c.AssetConfig.mutate(ctx, m)
	case *CanonicalBlockMutation:
		return c.CanonicalBlock.mutate(ctx, m)
	case *ChainCursorMutation:
		return c.ChainCursor.mutate(ctx, m)
	case *DepositMutation:
		return c.Deposit.mutate(ctx, m)
	case *DepositAddressMutation:
		return c.DepositAddress.mutate(ctx, m)
	case *ExposureStateMutation:
		return c.ExposureState.mutate(ctx, m)
	case *LedgerEntryMutation:
		return c.LedgerEntry.mutate(ctx, m)
	case *SourceEventMutation:
		return c.SourceEvent.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// AccountBalanceClient is a client for the AccountBalance schema.
type AccountBalanceClient struct {
	config
}

// NewAccountBalanceClient returns a client for the AccountBalance from the given config.
func NewAccountBalanceClient(c config) *AccountBalanceClient {
	return &AccountBalanceClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `accountbalance.Hooks(f(g(h())))`.
func (c *AccountBalanceClient) Use(hooks ...Hook) {
	c.hooks.AccountBalance = append(c.hooks.AccountBalance, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `accountbalance.Intercept(f(g(h())))`.
func (c *AccountBalanceClient) Intercept(interceptors ...Interceptor) {
	c.inters.AccountBalance = append(c.inters.AccountBalance, interceptors...)
}

// Create returns a builder for creating a AccountBalance entity.
func (c *AccountBalanceClient) Create() *AccountBalanceCreate {
	mutation := newAccountBalanceMutation(c.config, OpCreate)
	return &AccountBalanceCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of AccountBalance entities.
func (c *AccountBalanceClient) CreateBulk(builders ...*AccountBalanceCreate) *AccountBalanceCreateBulk {
	return &AccountBalanceCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *AccountBalanceClient) MapCreateBulk(slice any, setFunc func(*AccountBalanceCreate, int)) *AccountBalanceCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &AccountBalanceCreateBulk{err: fmt.Errorf("calling to AccountBalanceClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*AccountBalanceCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &AccountBalanceCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for AccountBalance.
func (c *AccountBalanceClient) Update() *AccountBalanceUpdate {
	mutation := newAccountBalanceMutation(c.config, OpUpdate)
	return &AccountBalanceUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *AccountBalanceClient) UpdateOne(_m *AccountBalance) *AccountBalanceUpdateOne {
	mutation := newAccountBalanceMutation(c.config, OpUpdateOne, withAccountBalance(_m))
	return &AccountBalanceUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *AccountBalanceClient) UpdateOneID(id int) *AccountBalanceUpdateOne {
	mutation := newAccountBalanceMutation(c.config, OpUpdateOne, withAccountBalanceID(id))
	return &AccountBalanceUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for AccountBalance.
func (c *AccountBalanceClient) Delete() *AccountBalanceDelete {
	mutation := newAccountBalanceMutation(c.config, OpDelete)
	return &AccountBalanceDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *AccountBalanceClient) DeleteOne(_m *AccountBalance) *AccountBalanceDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *AccountBalanceClient) DeleteOneID(id int) *AccountBalanceDeleteOne {
	builder := c.Delete().Where(accountbalance.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &AccountBalanceDeleteOne{builder}
}

// Query returns a query builder for AccountBalance.
func (c *AccountBalanceClient) Query() *AccountBalanceQuery {
	return &AccountBalanceQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeAccountBalance},
		inters: c.Interceptors(),
	}
}

// Get returns a AccountBalance entity by its id.
func (c *AccountBalanceClient) Get(ctx context.Context, id int) (*AccountBalance, error) {
	return c.Query().Where(accountbalance.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *AccountBalanceClient) GetX(ctx context.Context, id int) *AccountBalance {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *AccountBalanceClient) Hooks() []Hook {
	return c.hooks.AccountBalance
}

// Interceptors returns the client interceptors.
func (c *AccountBalanceClient) Interceptors() []Interceptor {
	return c.inters.AccountBalance
}

func (c *AccountBalanceClient) mutate(ctx context.Context, m *AccountBalanceMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&AccountBalanceCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&AccountBalanceUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&AccountBalanceUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&AccountBalanceDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown AccountBalance mutation op: %q", m.Op())
	}
}

// AssetConfigClient is a client for the AssetConfig schema.
type AssetConfigClient struct {
	config
}

// NewAssetConfigClient returns a client for the AssetConfig from the given config.
func NewAssetConfigClient(c config) *AssetConfigClient {
	return &AssetConfigClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `assetconfig.Hooks(f(g(h())))`.
func (c *AssetConfigClient) Use(hooks ...Hook) {
	c.hooks.AssetConfig = append(c.hooks.AssetConfig, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `assetconfig.Intercept(f(g(h())))`.
func (c *AssetConfigClient) Intercept(interceptors ...Interceptor) {
	c.inters.AssetConfig = append(c.inters.AssetConfig, interceptors...)
}

// Create returns a builder for creating a AssetConfig entity.
func (c *AssetConfigClient) Create() *AssetConfigCreate {
	mutation := newAssetConfigMutation(c.config, OpCreate)
	return &AssetConfigCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of AssetConfig entities.
func (c *AssetConfigClient) CreateBulk(builders ...*AssetConfigCreate) *AssetConfigCreateBulk {
	return &AssetConfigCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *AssetConfigClient) MapCreateBulk(slice any, setFunc func(*AssetConfigCreate, int)) *AssetConfigCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &AssetConfigCreateBulk{err: fmt.Errorf("calling to AssetConfigClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*AssetConfigCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &AssetConfigCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for AssetConfig.
func (c *AssetConfigClient) Update() *AssetConfigUpdate {
	mutation := newAssetConfigMutation(c.config, OpUpdate)
	return &AssetConfigUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *AssetConfigClient) UpdateOne(_m *AssetConfig) *AssetConfigUpdateOne {
	mutation := newAssetConfigMutation(c.config, OpUpdateOne, withAssetConfig(_m))
	return &AssetConfigUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *AssetConfigClient) UpdateOneID(id int) *AssetConfigUpdateOne {
	mutation := newAssetConfigMutation(c.config, OpUpdateOne, withAssetConfigID(id))
	return &AssetConfigUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for AssetConfig.
func (c *AssetConfigClient) Delete() *AssetConfigDelete {
	mutation := newAssetConfigMutation(c.config, OpDelete)
	return &AssetConfigDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *AssetConfigClient) DeleteOne(_m *AssetConfig) *AssetConfigDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *AssetConfigClient) DeleteOneID(id int) *AssetConfigDeleteOne {
	builder := c.Delete().Where(assetconfig.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &AssetConfigDeleteOne{builder}
}

// Query returns a query builder for AssetConfig.
func (c *AssetConfigClient) Query() *AssetConfigQuery {
	return &AssetConfigQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeAssetConfig},
		inters: c.Interceptors(),
	}
}

// Get returns a AssetConfig entity by its id.
func (c *AssetConfigClient) Get(ctx context.Context, id int) (*AssetConfig, error) {
	return c.Query().Where(assetconfig.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *AssetConfigClient) GetX(ctx context.Context, id int) *AssetConfig {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *AssetConfigClient) Hooks() []Hook {
	return c.hooks.AssetConfig
}

// Interceptors returns the client interceptors.
func (c *AssetConfigClient) Interceptors() []Interceptor {
	return c.inters.AssetConfig
}

func (c *AssetConfigClient) mutate(ctx context.Context, m *AssetConfigMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&AssetConfigCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&AssetConfigUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&AssetConfigUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&AssetConfigDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown AssetConfig mutation op: %q", m.Op())
	}
}

// CanonicalBlockClient is a client for the CanonicalBlock schema.
type CanonicalBlockClient struct {
	config
}

// NewCanonicalBlockClient returns a client for the CanonicalBlock from the given config.
func NewCanonicalBlockClient(c config) *CanonicalBlockClient {
	return &CanonicalBlockClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `canonicalblock.Hooks(f(g(h())))`.
func (c *CanonicalBlockClient) Use(hooks ...Hook) {
	c.hooks.CanonicalBlock = append(c.hooks.CanonicalBlock, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `canonicalblock.Intercept(f(g(h())))`.
func (c *CanonicalBlockClient) Intercept(interceptors ...Interceptor) {
	c.inters.CanonicalBlock = append(c.inters.CanonicalBlock, interceptors...)
}

// Create returns a builder for creating a CanonicalBlock entity.
func (c *CanonicalBlockClient) Create() *CanonicalBlockCreate {
	mutation := newCanonicalBlockMutation(c.config, OpCreate)
	return &CanonicalBlockCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of CanonicalBlock entities.
func (c *CanonicalBlockClient) CreateBulk(builders ...*CanonicalBlockCreate) *CanonicalBlockCreateBulk {
	return &CanonicalBlockCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *CanonicalBlockClient) MapCreateBulk(slice any, setFunc func(*CanonicalBlockCreate, int)) *CanonicalBlockCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &CanonicalBlockCreateBulk{err: fmt.Errorf("calling to CanonicalBlockClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*CanonicalBlockCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &CanonicalBlockCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for CanonicalBlock.
func (c *CanonicalBlockClient) Update() *CanonicalBlockUpdate {
	mutation := newCanonicalBlockMutation(c.config, OpUpdate)
	return &CanonicalBlockUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *CanonicalBlockClient) UpdateOne(_m *CanonicalBlock) *CanonicalBlockUpdateOne {
	mutation := newCanonicalBlockMutation(c.config, OpUpdateOne, withCanonicalBlock(_m))
	return &CanonicalBlockUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *CanonicalBlockClient) UpdateOneID(id int) *CanonicalBlockUpdateOne {
	mutation := newCanonicalBlockMutation(c.config, OpUpdateOne, withCanonicalBlockID(id))
	return &CanonicalBlockUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for CanonicalBlock.
func (c *CanonicalBlockClient) Delete() *CanonicalBlockDelete {
	mutation := newCanonicalBlockMutation(c.config, OpDelete)
	return &CanonicalBlockDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *CanonicalBlockClient) DeleteOne(_m *CanonicalBlock) *CanonicalBlockDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *CanonicalBlockClient) DeleteOneID(id int) *CanonicalBlockDeleteOne {
	builder := c.Delete().Where(canonicalblock.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &CanonicalBlockDeleteOne{builder}
}

// Query returns a query builder for CanonicalBlock.
func (c *CanonicalBlockClient) Query() *CanonicalBlockQuery {
	return &CanonicalBlockQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeCanonicalBlock},
		inters: c.Interceptors(),
	}
}

// Get returns a CanonicalBlock entity by its id.
func (c *CanonicalBlockClient) Get(ctx context.Context, id int) (*CanonicalBlock, error) {
	return c.Query().Where(canonicalblock.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *CanonicalBlockClient) GetX(ctx context.Context, id int) *CanonicalBlock {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *CanonicalBlockClient) Hooks() []Hook {
	return c.hooks.CanonicalBlock
}

// Interceptors returns the client interceptors.
func (c *CanonicalBlockClient) Interceptors() []Interceptor {
	return c.inters.CanonicalBlock
}

func (c *CanonicalBlockClient) mutate(ctx context.Context, m *CanonicalBlockMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&CanonicalBlockCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&CanonicalBlockUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&CanonicalBlockUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&CanonicalBlockDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown CanonicalBlock mutation op: %q", m.Op())
	}
}

// ChainCursorClient is a client for the ChainCursor schema.
type ChainCursorClient struct {
	config
}

// NewChainCursorClient returns a client for the ChainCursor from the given config.
func NewChainCursorClient(c config) *ChainCursorClient {
	return &ChainCursorClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `chaincursor.Hooks(f(g(h())))`.
func (c *ChainCursorClient) Use(hooks ...Hook) {
	c.hooks.ChainCursor = append(c.hooks.ChainCursor, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `chaincursor.Intercept(f(g(h())))`.
func (c *ChainCursorClient) Intercept(interceptors ...Interceptor) {
	c.inters.ChainCursor = append(c.inters.ChainCursor, interceptors...)
}

// Create returns a builder for creating a ChainCursor entity.
func (c *ChainCursorClient) Create() *ChainCursorCreate {
	mutation := newChainCursorMutation(c.config, OpCreate)
	return &ChainCursorCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of ChainCursor entities.
func (c *ChainCursorClient) CreateBulk(builders ...*ChainCursorCreate) *ChainCursorCreateBulk {
	return &ChainCursorCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ChainCursorClient) MapCreateBulk(slice any, setFunc func(*ChainCursorCreate, int)) *ChainCursorCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ChainCursorCreateBulk{err: fmt.Errorf("calling to ChainCursorClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ChainCursorCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ChainCursorCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for ChainCursor.
func (c *ChainCursorClient) Update() *ChainCursorUpdate {
	mutation := newChainCursorMutation(c.config, OpUpdate)
	return &ChainCursorUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ChainCursorClient) UpdateOne(_m *ChainCursor) *ChainCursorUpdateOne {
	mutation := newChainCursorMutation(c.config, OpUpdateOne, withChainCursor(_m))
	return &ChainCursorUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ChainCursorClient) UpdateOneID(id int) *ChainCursorUpdateOne {
	mutation := newChainCursorMutation(c.config, OpUpdateOne, withChainCursorID(id))
	return &ChainCursorUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for ChainCursor.
func (c *ChainCursorClient) Delete() *ChainCursorDelete {
	mutation := newChainCursorMutation(c.config, OpDelete)
	return &ChainCursorDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ChainCursorClient) DeleteOne(_m *ChainCursor) *ChainCursorDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ChainCursorClient) DeleteOneID(id int) *ChainCursorDeleteOne {
	builder := c.Delete().Where(chaincursor.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ChainCursorDeleteOne{builder}
}

// Query returns a query builder for ChainCursor.
func (c *ChainCursorClient) Query() *ChainCursorQuery {
	return &ChainCursorQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeChainCursor},
		inters: c.Interceptors(),
	}
}

// Get returns a ChainCursor entity by its id.
func (c *ChainCursorClient) Get(ctx context.Context, id int) (*ChainCursor, error) {
	return c.Query().Where(chaincursor.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ChainCursorClient) GetX(ctx context.Context, id int) *ChainCursor {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *ChainCursorClient) Hooks() []Hook {
	return c.hooks.ChainCursor
}

// Interceptors returns the client interceptors.
func (c *ChainCursorClient) Interceptors() []Interceptor {
	return c.inters.ChainCursor
}

func (c *ChainCursorClient) mutate(ctx context.Context, m *ChainCursorMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ChainCursorCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ChainCursorUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ChainCursorUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ChainCursorDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown ChainCursor mutation op: %q", m.Op())
	}
}

// DepositClient is a client for the Deposit schema.
type DepositClient struct {
	config
}

// NewDepositClient returns a client for the Deposit from the given config.
func NewDepositClient(c config) *DepositClient {
	return &DepositClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `deposit.Hooks(f(g(h())))`.
func (c *DepositClient) Use(hooks ...Hook) {
	c.hooks.Deposit = append(c.hooks.Deposit, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `deposit.Intercept(f(g(h())))`.
func (c *DepositClient) Intercept(interceptors ...Interceptor) {
	c.inters.Deposit = append(c.inters.Deposit, interceptors...)
}

// Create returns a builder for creating a Deposit entity.
func (c *DepositClient) Create() *DepositCreate {
	mutation := newDepositMutation(c.config, OpCreate)
	return &DepositCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Deposit entities.
func (c *DepositClient) CreateBulk(builders ...*DepositCreate) *DepositCreateBulk {
	return &DepositCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *DepositClient) MapCreateBulk(slice any, setFunc func(*DepositCreate, int)) *DepositCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &DepositCreateBulk{err: fmt.Errorf("calling to DepositClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*DepositCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &DepositCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Deposit.
func (c *DepositClient) Update() *DepositUpdate {
	mutation := newDepositMutation(c.config, OpUpdate)
	return &DepositUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *DepositClient) UpdateOne(_m *Deposit) *DepositUpdateOne {
	mutation := newDepositMutation(c.config, OpUpdateOne, withDeposit(_m))
	return &DepositUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *DepositClient) UpdateOneID(id int) *DepositUpdateOne {
	mutation := newDepositMutation(c.config, OpUpdateOne, withDepositID(id))
	return &DepositUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Deposit.
func (c *DepositClient) Delete() *DepositDelete {
	mutation := newDepositMutation(c.config, OpDelete)
	return &DepositDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *DepositClient) DeleteOne(_m *Deposit) *DepositDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *DepositClient) DeleteOneID(id int) *DepositDeleteOne {
	builder := c.Delete().Where(deposit.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &DepositDeleteOne{builder}
}

// Query returns a query builder for Deposit.
func (c *DepositClient) Query() *DepositQuery {
	return &DepositQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeDeposit},
		inters: c.Interceptors(),
	}
}

// Get returns a Deposit entity by its id.
func (c *DepositClient) Get(ctx context.Context, id int) (*Deposit, error) {
	return c.Query().Where(deposit.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *DepositClient) GetX(ctx context.Context, id int) *Deposit {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *DepositClient) Hooks() []Hook {
	return c.hooks.Deposit
}

// Interceptors returns the client interceptors.
func (c *DepositClient) Interceptors() []Interceptor {
	return c.inters.Deposit
}

func (c *DepositClient) mutate(ctx context.Context, m *DepositMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&DepositCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&DepositUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&DepositUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&DepositDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Deposit mutation op: %q", m.Op())
	}
}

// DepositAddressClient is a client for the DepositAddress schema.
type DepositAddressClient struct {
	config
}

// NewDepositAddressClient returns a client for the DepositAddress from the given config.
func NewDepositAddressClient(c config) *DepositAddressClient {
	return &DepositAddressClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `depositaddress.Hooks(f(g(h())))`.
func (c *DepositAddressClient) Use(hooks ...Hook) {
	c.hooks.DepositAddress = append(c.hooks.DepositAddress, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `depositaddress.Intercept(f(g(h())))`.
func (c *DepositAddressClient) Intercept(interceptors ...Interceptor) {
	c.inters.DepositAddress = append(c.inters.DepositAddress, interceptors...)
}

// Create returns a builder for creating a DepositAddress entity.
func (c *DepositAddressClient) Create() *DepositAddressCreate {
	mutation := newDepositAddressMutation(c.config, OpCreate)
	return &DepositAddressCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of DepositAddress entities.
func (c *DepositAddressClient) CreateBulk(builders ...*DepositAddressCreate) *DepositAddressCreateBulk {
	return &DepositAddressCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *DepositAddressClient) MapCreateBulk(slice any, setFunc func(*DepositAddressCreate, int)) *DepositAddressCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &DepositAddressCreateBulk{err: fmt.Errorf("calling to DepositAddressClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*DepositAddressCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &DepositAddressCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for DepositAddress.
func (c *DepositAddressClient) Update() *DepositAddressUpdate {
	mutation := newDepositAddressMutation(c.config, OpUpdate)
	return &DepositAddressUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *DepositAddressClient) UpdateOne(_m *DepositAddress) *DepositAddressUpdateOne {
	mutation := newDepositAddressMutation(c.config, OpUpdateOne, withDepositAddress(_m))
	return &DepositAddressUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *DepositAddressClient) UpdateOneID(id int) *DepositAddressUpdateOne {
	mutation := newDepositAddressMutation(c.config, OpUpdateOne, withDepositAddressID(id))
	return &DepositAddressUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for DepositAddress.
func (c *DepositAddressClient) Delete() *DepositAddressDelete {
	mutation := newDepositAddressMutation(c.config, OpDelete)
	return &DepositAddressDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *DepositAddressClient) DeleteOne(_m *DepositAddress) *DepositAddressDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *DepositAddressClient) DeleteOneID(id int) *DepositAddressDeleteOne {
	builder := c.Delete().Where(depositaddress.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &DepositAddressDeleteOne{builder}
}

// Query returns a query builder for DepositAddress.
func (c *DepositAddressClient) Query() *DepositAddressQuery {
	return &DepositAddressQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeDepositAddress},
		inters: c.Interceptors(),
	}
}

// Get returns a DepositAddress entity by its id.
func (c *DepositAddressClient) Get(ctx context.Context, id int) (*DepositAddress, error) {
	return c.Query().Where(depositaddress.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *DepositAddressClient) GetX(ctx context.Context, id int) *DepositAddress {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *DepositAddressClient) Hooks() []Hook {
	return c.hooks.DepositAddress
}

// Interceptors returns the client interceptors.
func (c *DepositAddressClient) Interceptors() []Interceptor {
	return c.inters.DepositAddress
}

func (c *DepositAddressClient) mutate(ctx context.Context, m *DepositAddressMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&DepositAddressCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&DepositAddressUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&DepositAddressUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&DepositAddressDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown DepositAddress mutation op: %q", m.Op())
	}
}

// ExposureStateClient is a client for the ExposureState schema.
type ExposureStateClient struct {
	config
}

// NewExposureStateClient returns a client for the ExposureState from the given config.
func NewExposureStateClient(c config) *ExposureStateClient {
	return &ExposureStateClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `exposurestate.Hooks(f(g(h())))`.
func (c *ExposureStateClient) Use(hooks ...Hook) {
	c.hooks.ExposureState = append(c.hooks.ExposureState, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `exposurestate.Intercept(f(g(h())))`.
func (c *ExposureStateClient) Intercept(interceptors ...Interceptor) {
	c.inters.ExposureState = append(c.inters.ExposureState, interceptors...)
}

// Create returns a builder for creating a ExposureState entity.
func (c *ExposureStateClient) Create() *ExposureStateCreate {
	mutation := newExposureStateMutation(c.config, OpCreate)
	return &ExposureStateCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of ExposureState entities.
func (c *ExposureStateClient) CreateBulk(builders ...*ExposureStateCreate) *ExposureStateCreateBulk {
	return &ExposureStateCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ExposureStateClient) MapCreateBulk(slice any, setFunc func(*ExposureStateCreate, int)) *ExposureStateCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ExposureStateCreateBulk{err: fmt.Errorf("calling to ExposureStateClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ExposureStateCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ExposureStateCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for ExposureState.
func (c *ExposureStateClient) Update() *ExposureStateUpdate {
	mutation := newExposureStateMutation(c.config, OpUpdate)
	return &ExposureStateUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ExposureStateClient) UpdateOne(_m *ExposureState) *ExposureStateUpdateOne {
	mutation := newExposureStateMutation(c.config, OpUpdateOne, withExposureState(_m))
	return &ExposureStateUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ExposureStateClient) UpdateOneID(id int) *ExposureStateUpdateOne {
	mutation := newExposureStateMutation(c.config, OpUpdateOne, withExposureStateID(id))
	return &ExposureStateUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for ExposureState.
func (c *ExposureStateClient) Delete() *ExposureStateDelete {
	mutation := newExposureStateMutation(c.config, OpDelete)
	return &ExposureStateDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ExposureStateClient) DeleteOne(_m *ExposureState) *ExposureStateDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ExposureStateClient) DeleteOneID(id int) *ExposureStateDeleteOne {
	builder := c.Delete().Where(exposurestate.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ExposureStateDeleteOne{builder}
}

// Query returns a query builder for ExposureState.
func (c *ExposureStateClient) Query() *ExposureStateQuery {
	return &ExposureStateQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeExposureState},
		inters: c.Interceptors(),
	}
}

// Get returns a ExposureState entity by its id.
func (c *ExposureStateClient) Get(ctx context.Context, id int) (*ExposureState, error) {
	return c.Query().Where(exposurestate.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ExposureStateClient) GetX(ctx context.Context, id int) *ExposureState {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *ExposureStateClient) Hooks() []Hook {
	return c.hooks.ExposureState
}

// Interceptors returns the client interceptors.
func (c *ExposureStateClient) Interceptors() []Interceptor {
	return c.inters.ExposureState
}

func (c *ExposureStateClient) mutate(ctx context.Context, m *ExposureStateMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ExposureStateCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ExposureStateUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ExposureStateUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ExposureStateDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown ExposureState mutation op: %q", m.Op())
	}
}

// LedgerEntryClient is a client for the LedgerEntry schema.
type LedgerEntryClient struct {
	config
}

// NewLedgerEntryClient returns a client for the LedgerEntry from the given config.
func NewLedgerEntryClient(c config) *LedgerEntryClient {
	return &LedgerEntryClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `ledgerentry.Hooks(f(g(h())))`.
func (c *LedgerEntryClient) Use(hooks ...Hook) {
	c.hooks.LedgerEntry = append(c.hooks.LedgerEntry, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `ledgerentry.Intercept(f(g(h())))`.
func (c *LedgerEntryClient) Intercept(interceptors ...Interceptor) {
	c.inters.LedgerEntry = append(c.inters.LedgerEntry, interceptors...)
}

// Create returns a builder for creating a LedgerEntry entity.
func (c *LedgerEntryClient) Create() *LedgerEntryCreate {
	mutation := newLedgerEntryMutation(c.config, OpCreate)
	return &LedgerEntryCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of LedgerEntry entities.
func (c *LedgerEntryClient) CreateBulk(builders ...*LedgerEntryCreate) *LedgerEntryCreateBulk {
	return &LedgerEntryCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *LedgerEntryClient) MapCreateBulk(slice any, setFunc func(*LedgerEntryCreate, int)) *LedgerEntryCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &LedgerEntryCreateBulk{err: fmt.Errorf("calling to LedgerEntryClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*LedgerEntryCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &LedgerEntryCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for LedgerEntry.
func (c *LedgerEntryClient) Update() *LedgerEntryUpdate {
	mutation := newLedgerEntryMutation(c.config, OpUpdate)
	return &LedgerEntryUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *LedgerEntryClient) UpdateOne(_m *LedgerEntry) *LedgerEntryUpdateOne {
	mutation := newLedgerEntryMutation(c.config, OpUpdateOne, withLedgerEntry(_m))
	return &LedgerEntryUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *LedgerEntryClient) UpdateOneID(id int) *LedgerEntryUpdateOne {
	mutation := newLedgerEntryMutation(c.config, OpUpdateOne, withLedgerEntryID(id))
	return &LedgerEntryUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for LedgerEntry.
func (c *LedgerEntryClient) Delete() *LedgerEntryDelete {
	mutation := newLedgerEntryMutation(c.config, OpDelete)
	return &LedgerEntryDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *LedgerEntryClient) DeleteOne(_m *LedgerEntry) *LedgerEntryDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *LedgerEntryClient) DeleteOneID(id int) *LedgerEntryDeleteOne {
	builder := c.Delete().Where(ledgerentry.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &LedgerEntryDeleteOne{builder}
}

// Query returns a query builder for LedgerEntry.
func (c *LedgerEntryClient) Query() *LedgerEntryQuery {
	return &LedgerEntryQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeLedgerEntry},
		inters: c.Interceptors(),
	}
}

// Get returns a LedgerEntry entity by its id.
func (c *LedgerEntryClient) Get(ctx context.Context, id int) (*LedgerEntry, error) {
	return c.Query().Where(ledgerentry.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *LedgerEntryClient) GetX(ctx context.Context, id int) *LedgerEntry {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *LedgerEntryClient) Hooks() []Hook {
	return c.hooks.LedgerEntry
}

// Interceptors returns the client interceptors.
func (c *LedgerEntryClient) Interceptors() []Interceptor {
	return c.inters.LedgerEntry
}

func (c *LedgerEntryClient) mutate(ctx context.Context, m *LedgerEntryMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&LedgerEntryCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&LedgerEntryUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&LedgerEntryUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&LedgerEntryDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown LedgerEntry mutation op: %q", m.Op())
	}
}

// SourceEventClient is a client for the SourceEvent schema.
type SourceEventClient struct {
	config
}

// NewSourceEventClient returns a client for the SourceEvent from the given config.
func NewSourceEventClient(c config) *SourceEventClient {
	return &SourceEventClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `sourceevent.Hooks(f(g(h())))`.
func (c *SourceEventClient) Use(hooks ...Hook) {
	c.hooks.SourceEvent = append(c.hooks.SourceEvent, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `sourceevent.Intercept(f(g(h())))`.
func (c *SourceEventClient) Intercept(interceptors ...Interceptor) {
	c.inters.SourceEvent = append(c.inters.SourceEvent, interceptors...)
}

// Create returns a builder for creating a SourceEvent entity.
func (c *SourceEventClient) Create() *SourceEventCreate {
	mutation := newSourceEventMutation(c.config, OpCreate)
	return &SourceEventCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of SourceEvent entities.
func (c *SourceEventClient) CreateBulk(builders ...*SourceEventCreate) *SourceEventCreateBulk {
	return &SourceEventCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *SourceEventClient) MapCreateBulk(slice any, setFunc func(*SourceEventCreate, int)) *SourceEventCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &SourceEventCreateBulk{err: fmt.Errorf("calling to SourceEventClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*SourceEventCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &SourceEventCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for SourceEvent.
func (c *SourceEventClient) Update() *SourceEventUpdate {
	mutation := newSourceEventMutation(c.config, OpUpdate)
	return &SourceEventUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *SourceEventClient) UpdateOne(_m *SourceEvent) *SourceEventUpdateOne {
	mutation := newSourceEventMutation(c.config, OpUpdateOne, withSourceEvent(_m))
	return &SourceEventUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *SourceEventClient) UpdateOneID(id int) *SourceEventUpdateOne {
	mutation := newSourceEventMutation(c.config, OpUpdateOne, withSourceEventID(id))
	return &SourceEventUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for SourceEvent.
func (c *SourceEventClient) Delete() *SourceEventDelete {
	mutation := newSourceEventMutation(c.config, OpDelete)
	return &SourceEventDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *SourceEventClient) DeleteOne(_m *SourceEvent) *SourceEventDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *SourceEventClient) DeleteOneID(id int) *SourceEventDeleteOne {
	builder := c.Delete().Where(sourceevent.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &SourceEventDeleteOne{builder}
}

// Query returns a query builder for SourceEvent.
func (c *SourceEventClient) Query() *SourceEventQuery {
	return &SourceEventQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeSourceEvent},
		inters: c.Interceptors(),
	}
}

// Get returns a SourceEvent entity by its id.
func (c *SourceEventClient) Get(ctx context.Context, id int) (*SourceEvent, error) {
	return c.Query().Where(sourceevent.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *SourceEventClient) GetX(ctx context.Context, id int) *SourceEvent {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *SourceEventClient) Hooks() []Hook {
	return c.hooks.SourceEvent
}

// Interceptors returns the client interceptors.
func (c *SourceEventClient) Interceptors() []Interceptor {
	return c.inters.SourceEvent
}

func (c *SourceEventClient) mutate(ctx context.Context, m *SourceEventMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&SourceEventCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&SourceEventUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&SourceEventUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&SourceEventDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown SourceEvent mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		AccountBalance, AssetConfig, CanonicalBlock, ChainCursor, Deposit,
		DepositAddress, ExposureState, LedgerEntry, SourceEvent []ent.Hook
	}
	inters struct {
		AccountBalance, AssetConfig, CanonicalBlock, ChainCursor, Deposit,
		DepositAddress, ExposureState, LedgerEntry, SourceEvent []ent.Interceptor
	}
)
