// Code generated by ent, DO NOT EDIT.

package ent

import (
	"deposit-crediting/internal/store/ent/deposit"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Deposit is the model entity for the Deposit schema.
type Deposit struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// TransferID holds the value of the "transfer_id" field.
	TransferID string `json:"transfer_id,omitempty"`
	// Chain holds the value of the "chain" field.
	Chain string `json:"chain,omitempty"`
	// Asset holds the value of the "asset" field.
	Asset string `json:"asset,omitempty"`
	// Account holds the value of the "account" field.
	Account string `json:"account,omitempty"`
	// Address holds the value of the "address" field.
	Address string `json:"address,omitempty"`
	// Amount holds the value of the "amount" field.
	Amount string `json:"amount,omitempty"`
	// Mode holds the value of the "mode" field.
	Mode deposit.Mode `json:"mode,omitempty"`
	// State holds the value of the "state" field.
	State deposit.State `json:"state,omitempty"`
	// CreditCycle holds the value of the "credit_cycle" field.
	CreditCycle int `json:"credit_cycle,omitempty"`
	// BlockHeight holds the value of the "block_height" field.
	BlockHeight *int64 `json:"block_height,omitempty"`
	// BlockHash holds the value of the "block_hash" field.
	BlockHash *string `json:"block_hash,omitempty"`
	// ReorgedHeight holds the value of the "reorged_height" field.
	ReorgedHeight *int64 `json:"reorged_height,omitempty"`
	// TxHash holds the value of the "tx_hash" field.
	TxHash *string `json:"tx_hash,omitempty"`
	// SourceEvent holds the value of the "source_event" field.
	SourceEvent *string `json:"source_event,omitempty"`
	// Held holds the value of the "held" field.
	Held bool `json:"held,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Deposit) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case deposit.FieldHeld:
			values[i] = new(sql.NullBool)
		case deposit.FieldID, deposit.FieldCreditCycle, deposit.FieldBlockHeight, deposit.FieldReorgedHeight:
			values[i] = new(sql.NullInt64)
		case deposit.FieldTransferID, deposit.FieldChain, deposit.FieldAsset, deposit.FieldAccount, deposit.FieldAddress, deposit.FieldAmount, deposit.FieldMode, deposit.FieldState, deposit.FieldBlockHash, deposit.FieldTxHash, deposit.FieldSourceEvent:
			values[i] = new(sql.NullString)
		case deposit.FieldCreatedAt, deposit.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Deposit fields.
func (_m *Deposit) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case deposit.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case deposit.FieldTransferID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field transfer_id", values[i])
			} else if value.Valid {
				_m.TransferID = value.String
			}
		case deposit.FieldChain:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field chain", values[i])
			} else if value.Valid {
				_m.Chain = value.String
			}
		case deposit.FieldAsset:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field asset", values[i])
			} else if value.Valid {
				_m.Asset = value.String
			}
		case deposit.FieldAccount:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field account", values[i])
			} else if value.Valid {
				_m.Account = value.String
			}
		case deposit.FieldAddress:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field address", values[i])
			} else if value.Valid {
				_m.Address = value.String
			}
		case deposit.FieldAmount:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field amount", values[i])
			} else if value.Valid {
				_m.Amount = value.String
			}
		case deposit.FieldMode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field mode", values[i])
			} else if value.Valid {
				_m.Mode = deposit.Mode(value.String)
			}
		case deposit.FieldState:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field state", values[i])
			} else if value.Valid {
				_m.State = deposit.State(value.String)
			}
		case deposit.FieldCreditCycle:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field credit_cycle", values[i])
			} else if value.Valid {
				_m.CreditCycle = int(value.Int64)
			}
		case deposit.FieldBlockHeight:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field block_height", values[i])
			} else if value.Valid {
				_m.BlockHeight = new(int64)
				*_m.BlockHeight = value.Int64
			}
		case deposit.FieldBlockHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field block_hash", values[i])
			} else if value.Valid {
				_m.BlockHash = new(string)
				*_m.BlockHash = value.String
			}
		case deposit.FieldReorgedHeight:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field reorged_height", values[i])
			} else if value.Valid {
				_m.ReorgedHeight = new(int64)
				*_m.ReorgedHeight = value.Int64
			}
		case deposit.FieldTxHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field tx_hash", values[i])
			} else if value.Valid {
				_m.TxHash = new(string)
				*_m.TxHash = value.String
			}
		case deposit.FieldSourceEvent:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source_event", values[i])
			} else if value.Valid {
				_m.SourceEvent = new(string)
				*_m.SourceEvent = value.String
			}
		case deposit.FieldHeld:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field held", values[i])
			} else if value.Valid {
				_m.Held = value.Bool
			}
		case deposit.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case deposit.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Deposit.
// This includes values selected through modifiers, order, etc.
func (_m *Deposit) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this Deposit.
// Note that you need to call Deposit.Unwrap() before calling this method if this Deposit
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Deposit) Update() *DepositUpdateOne {
	return NewDepositClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Deposit entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Deposit) Unwrap() *Deposit {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Deposit is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Deposit) String() string {
	var builder strings.Builder
	builder.WriteString("Deposit(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("transfer_id=")
	builder.WriteString(_m.TransferID)
	builder.WriteString(", ")
	builder.WriteString("chain=")
	builder.WriteString(_m.Chain)
	builder.WriteString(", ")
	builder.WriteString("asset=")
	builder.WriteString(_m.Asset)
	builder.WriteString(", ")
	builder.WriteString("account=")
	builder.WriteString(_m.Account)
	builder.WriteString(", ")
	builder.WriteString("address=")
	builder.WriteString(_m.Address)
	builder.WriteString(", ")
	builder.WriteString("amount=")
	builder.WriteString(_m.Amount)
	builder.WriteString(", ")
	builder.WriteString("mode=")
	builder.WriteString(fmt.Sprintf("%v", _m.Mode))
	builder.WriteString(", ")
	builder.WriteString("state=")
	builder.WriteString(fmt.Sprintf("%v", _m.State))
	builder.WriteString(", ")
	builder.WriteString("credit_cycle=")
	builder.WriteString(fmt.Sprintf("%v", _m.CreditCycle))
	builder.WriteString(", ")
	if v := _m.BlockHeight; v != nil {
		builder.WriteString("block_height=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.BlockHash; v != nil {
		builder.WriteString("block_hash=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ReorgedHeight; v != nil {
		builder.WriteString("reorged_height=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.TxHash; v != nil {
		builder.WriteString("tx_hash=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.SourceEvent; v != nil {
		builder.WriteString("source_event=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("held=")
	builder.WriteString(fmt.Sprintf("%v", _m.Held))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Deposits is a parsable slice of Deposit.
type Deposits []*Deposit
