// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"deposit-crediting/internal/store/ent/depositaddress"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DepositAddressCreate is the builder for creating a DepositAddress entity.
type DepositAddressCreate struct {
	config
	mutation *DepositAddressMutation
	hooks    []Hook
}

// SetAccount sets the "account" field.
func (_c *DepositAddressCreate) SetAccount(v string) *DepositAddressCreate {
	_c.mutation.SetAccount(v)
	return _c
}

// SetChain sets the "chain" field.
func (_c *DepositAddressCreate) SetChain(v string) *DepositAddressCreate {
	_c.mutation.SetChain(v)
	return _c
}

// SetAddress sets the "address" field.
func (_c *DepositAddressCreate) SetAddress(v string) *DepositAddressCreate {
	_c.mutation.SetAddress(v)
	return _c
}

// SetMode sets the "mode" field.
func (_c *DepositAddressCreate) SetMode(v depositaddress.Mode) *DepositAddressCreate {
	_c.mutation.SetMode(v)
	return _c
}

// SetActive sets the "active" field.
func (_c *DepositAddressCreate) SetActive(v bool) *DepositAddressCreate {
	_c.mutation.SetActive(v)
	return _c
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (_c *DepositAddressCreate) SetNillableActive(v *bool) *DepositAddressCreate {
	if v != nil {
		_c.SetActive(*v)
	}
	return _c
}

// Mutation returns the DepositAddressMutation object of the builder.
func (_c *DepositAddressCreate) Mutation() *DepositAddressMutation {
	return _c.mutation
}

// Save creates the DepositAddress in the database.
func (_c *DepositAddressCreate) Save(ctx context.Context) (*DepositAddress, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *DepositAddressCreate) SaveX(ctx context.Context) *DepositAddress {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DepositAddressCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DepositAddressCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *DepositAddressCreate) defaults() {
	if _, ok := _c.mutation.Active(); !ok {
		v := depositaddress.DefaultActive
		_c.mutation.SetActive(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *DepositAddressCreate) check() error {
	if _, ok := _c.mutation.Account(); !ok {
		return &ValidationError{Name: "account", err: errors.New(`ent: missing required field "DepositAddress.account"`)}
	}
	if v, ok := _c.mutation.Account(); ok {
		if err := depositaddress.AccountValidator(v); err != nil {
			return &ValidationError{Name: "account", err: fmt.Errorf(`ent: validator failed for field "DepositAddress.account": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Chain(); !ok {
		return &ValidationError{Name: "chain", err: errors.New(`ent: missing required field "DepositAddress.chain"`)}
	}
	if v, ok := _c.mutation.Chain(); ok {
		if err := depositaddress.ChainValidator(v); err != nil {
			return &ValidationError{Name: "chain", err: fmt.Errorf(`ent: validator failed for field "DepositAddress.chain": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Address(); !ok {
		return &ValidationError{Name: "address", err: errors.New(`ent: missing required field "DepositAddress.address"`)}
	}
	if v, ok := _c.mutation.Address(); ok {
		if err := depositaddress.AddressValidator(v); err != nil {
			return &ValidationError{Name: "address", err: fmt.Errorf(`ent: validator failed for field "DepositAddress.address": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Mode(); !ok {
		return &ValidationError{Name: "mode", err: errors.New(`ent: missing required field "DepositAddress.mode"`)}
	}
	if v, ok := _c.mutation.Mode(); ok {
		if err := depositaddress.ModeValidator(v); err != nil {
			return &ValidationError{Name: "mode", err: fmt.Errorf(`ent: validator failed for field "DepositAddress.mode": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Active(); !ok {
		return &ValidationError{Name: "active", err: errors.New(`ent: missing required field "DepositAddress.active"`)}
	}
	return nil
}

func (_c *DepositAddressCreate) sqlSave(ctx context.Context) (*DepositAddress, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *DepositAddressCreate) createSpec() (*DepositAddress, *sqlgraph.CreateSpec) {
	var (
		_node = &DepositAddress{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(depositaddress.Table, sqlgraph.NewFieldSpec(depositaddress.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Account(); ok {
		_spec.SetField(depositaddress.FieldAccount, field.TypeString, value)
		_node.Account = value
	}
	if value, ok := _c.mutation.Chain(); ok {
		_spec.SetField(depositaddress.FieldChain, field.TypeString, value)
		_node.Chain = value
	}
	if value, ok := _c.mutation.Address(); ok {
		_spec.SetField(depositaddress.FieldAddress, field.TypeString, value)
		_node.Address = value
	}
	if value, ok := _c.mutation.Mode(); ok {
		_spec.SetField(depositaddress.FieldMode, field.TypeEnum, value)
		_node.Mode = value
	}
	if value, ok := _c.mutation.Active(); ok {
		_spec.SetField(depositaddress.FieldActive, field.TypeBool, value)
		_node.Active = value
	}
	return _node, _spec
}

// DepositAddressCreateBulk is the builder for creating many DepositAddress entities in bulk.
type DepositAddressCreateBulk struct {
	config
	err      error
	builders []*DepositAddressCreate
}

// Save creates the DepositAddress entities in the database.
func (_c *DepositAddressCreateBulk) Save(ctx context.Context) ([]*DepositAddress, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*DepositAddress, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DepositAddressMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *DepositAddressCreateBulk) SaveX(ctx context.Context) []*DepositAddress {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DepositAddressCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DepositAddressCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
