// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"deposit-crediting/internal/store/ent/deposit"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DepositCreate is the builder for creating a Deposit entity.
type DepositCreate struct {
	config
	mutation *DepositMutation
	hooks    []Hook
}

// SetTransferID sets the "transfer_id" field.
func (_c *DepositCreate) SetTransferID(v string) *DepositCreate {
	_c.mutation.SetTransferID(v)
	return _c
}

// SetChain sets the "chain" field.
func (_c *DepositCreate) SetChain(v string) *DepositCreate {
	_c.mutation.SetChain(v)
	return _c
}

// SetAsset sets the "asset" field.
func (_c *DepositCreate) SetAsset(v string) *DepositCreate {
	_c.mutation.SetAsset(v)
	return _c
}

// SetAccount sets the "account" field.
func (_c *DepositCreate) SetAccount(v string) *DepositCreate {
	_c.mutation.SetAccount(v)
	return _c
}

// SetAddress sets the "address" field.
func (_c *DepositCreate) SetAddress(v string) *DepositCreate {
	_c.mutation.SetAddress(v)
	return _c
}

// SetAmount sets the "amount" field.
func (_c *DepositCreate) SetAmount(v string) *DepositCreate {
	_c.mutation.SetAmount(v)
	return _c
}

// SetMode sets the "mode" field.
func (_c *DepositCreate) SetMode(v deposit.Mode) *DepositCreate {
	_c.mutation.SetMode(v)
	return _c
}

// SetState sets the "state" field.
func (_c *DepositCreate) SetState(v deposit.State) *DepositCreate {
	_c.mutation.SetState(v)
	return _c
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_c *DepositCreate) SetNillableState(v *deposit.State) *DepositCreate {
	if v != nil {
		_c.SetState(*v)
	}
	return _c
}

// SetCreditCycle sets the "credit_cycle" field.
func (_c *DepositCreate) SetCreditCycle(v int) *DepositCreate {
	_c.mutation.SetCreditCycle(v)
	return _c
}

// SetNillableCreditCycle sets the "credit_cycle" field if the given value is not nil.
func (_c *DepositCreate) SetNillableCreditCycle(v *int) *DepositCreate {
	if v != nil {
		_c.SetCreditCycle(*v)
	}
	return _c
}

// SetBlockHeight sets the "block_height" field.
func (_c *DepositCreate) SetBlockHeight(v int64) *DepositCreate {
	_c.mutation.SetBlockHeight(v)
	return _c
}

// SetNillableBlockHeight sets the "block_height" field if the given value is not nil.
func (_c *DepositCreate) SetNillableBlockHeight(v *int64) *DepositCreate {
	if v != nil {
		_c.SetBlockHeight(*v)
	}
	return _c
}

// SetBlockHash sets the "block_hash" field.
func (_c *DepositCreate) SetBlockHash(v string) *DepositCreate {
	_c.mutation.SetBlockHash(v)
	return _c
}

// SetNillableBlockHash sets the "block_hash" field if the given value is not nil.
func (_c *DepositCreate) SetNillableBlockHash(v *string) *DepositCreate {
	if v != nil {
		_c.SetBlockHash(*v)
	}
	return _c
}

// SetReorgedHeight sets the "reorged_height" field.
func (_c *DepositCreate) SetReorgedHeight(v int64) *DepositCreate {
	_c.mutation.SetReorgedHeight(v)
	return _c
}

// SetNillableReorgedHeight sets the "reorged_height" field if the given value is not nil.
func (_c *DepositCreate) SetNillableReorgedHeight(v *int64) *DepositCreate {
	if v != nil {
		_c.SetReorgedHeight(*v)
	}
	return _c
}

// SetTxHash sets the "tx_hash" field.
func (_c *DepositCreate) SetTxHash(v string) *DepositCreate {
	_c.mutation.SetTxHash(v)
	return _c
}

// SetNillableTxHash sets the "tx_hash" field if the given value is not nil.
func (_c *DepositCreate) SetNillableTxHash(v *string) *DepositCreate {
	if v != nil {
		_c.SetTxHash(*v)
	}
	return _c
}

// SetSourceEvent sets the "source_event" field.
func (_c *DepositCreate) SetSourceEvent(v string) *DepositCreate {
	_c.mutation.SetSourceEvent(v)
	return _c
}

// SetNillableSourceEvent sets the "source_event" field if the given value is not nil.
func (_c *DepositCreate) SetNillableSourceEvent(v *string) *DepositCreate {
	if v != nil {
		_c.SetSourceEvent(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *DepositCreate) SetCreatedAt(v time.Time) *DepositCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *DepositCreate) SetNillableCreatedAt(v *time.Time) *DepositCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *DepositCreate) SetUpdatedAt(v time.Time) *DepositCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *DepositCreate) SetNillableUpdatedAt(v *time.Time) *DepositCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the DepositMutation object of the builder.
func (_c *DepositCreate) Mutation() *DepositMutation {
	return _c.mutation
}

// Save creates the Deposit in the database.
func (_c *DepositCreate) Save(ctx context.Context) (*Deposit, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *DepositCreate) SaveX(ctx context.Context) *Deposit {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DepositCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DepositCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *DepositCreate) defaults() {
	if _, ok := _c.mutation.State(); !ok {
		v := deposit.DefaultState
		_c.mutation.SetState(v)
	}
	if _, ok := _c.mutation.CreditCycle(); !ok {
		v := deposit.DefaultCreditCycle
		_c.mutation.SetCreditCycle(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := deposit.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := deposit.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *DepositCreate) check() error {
	if _, ok := _c.mutation.TransferID(); !ok {
		return &ValidationError{Name: "transfer_id", err: errors.New(`ent: missing required field "Deposit.transfer_id"`)}
	}
	if v, ok := _c.mutation.TransferID(); ok {
		if err := deposit.TransferIDValidator(v); err != nil {
			return &ValidationError{Name: "transfer_id", err: fmt.Errorf(`ent: validator failed for field "Deposit.transfer_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Chain(); !ok {
		return &ValidationError{Name: "chain", err: errors.New(`ent: missing required field "Deposit.chain"`)}
	}
	if v, ok := _c.mutation.Chain(); ok {
		if err := deposit.ChainValidator(v); err != nil {
			return &ValidationError{Name: "chain", err: fmt.Errorf(`ent: validator failed for field "Deposit.chain": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Asset(); !ok {
		return &ValidationError{Name: "asset", err: errors.New(`ent: missing required field "Deposit.asset"`)}
	}
	if v, ok := _c.mutation.Asset(); ok {
		if err := deposit.AssetValidator(v); err != nil {
			return &ValidationError{Name: "asset", err: fmt.Errorf(`ent: validator failed for field "Deposit.asset": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Account(); !ok {
		return &ValidationError{Name: "account", err: errors.New(`ent: missing required field "Deposit.account"`)}
	}
	if v, ok := _c.mutation.Account(); ok {
		if err := deposit.AccountValidator(v); err != nil {
			return &ValidationError{Name: "account", err: fmt.Errorf(`ent: validator failed for field "Deposit.account": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Address(); !ok {
		return &ValidationError{Name: "address", err: errors.New(`ent: missing required field "Deposit.address"`)}
	}
	if v, ok := _c.mutation.Address(); ok {
		if err := deposit.AddressValidator(v); err != nil {
			return &ValidationError{Name: "address", err: fmt.Errorf(`ent: validator failed for field "Deposit.address": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Amount(); !ok {
		return &ValidationError{Name: "amount", err: errors.New(`ent: missing required field "Deposit.amount"`)}
	}
	if _, ok := _c.mutation.Mode(); !ok {
		return &ValidationError{Name: "mode", err: errors.New(`ent: missing required field "Deposit.mode"`)}
	}
	if v, ok := _c.mutation.Mode(); ok {
		if err := deposit.ModeValidator(v); err != nil {
			return &ValidationError{Name: "mode", err: fmt.Errorf(`ent: validator failed for field "Deposit.mode": %w`, err)}
		}
	}
	if _, ok := _c.mutation.State(); !ok {
		return &ValidationError{Name: "state", err: errors.New(`ent: missing required field "Deposit.state"`)}
	}
	if v, ok := _c.mutation.State(); ok {
		if err := deposit.StateValidator(v); err != nil {
			return &ValidationError{Name: "state", err: fmt.Errorf(`ent: validator failed for field "Deposit.state": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreditCycle(); !ok {
		return &ValidationError{Name: "credit_cycle", err: errors.New(`ent: missing required field "Deposit.credit_cycle"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Deposit.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Deposit.updated_at"`)}
	}
	return nil
}

func (_c *DepositCreate) sqlSave(ctx context.Context) (*Deposit, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *DepositCreate) createSpec() (*Deposit, *sqlgraph.CreateSpec) {
	var (
		_node = &Deposit{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(deposit.Table, sqlgraph.NewFieldSpec(deposit.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.TransferID(); ok {
		_spec.SetField(deposit.FieldTransferID, field.TypeString, value)
		_node.TransferID = value
	}
	if value, ok := _c.mutation.Chain(); ok {
		_spec.SetField(deposit.FieldChain, field.TypeString, value)
		_node.Chain = value
	}
	if value, ok := _c.mutation.Asset(); ok {
		_spec.SetField(deposit.FieldAsset, field.TypeString, value)
		_node.Asset = value
	}
	if value, ok := _c.mutation.Account(); ok {
		_spec.SetField(deposit.FieldAccount, field.TypeString, value)
		_node.Account = value
	}
	if value, ok := _c.mutation.Address(); ok {
		_spec.SetField(deposit.FieldAddress, field.TypeString, value)
		_node.Address = value
	}
	if value, ok := _c.mutation.Amount(); ok {
		_spec.SetField(deposit.FieldAmount, field.TypeString, value)
		_node.Amount = value
	}
	if value, ok := _c.mutation.Mode(); ok {
		_spec.SetField(deposit.FieldMode, field.TypeEnum, value)
		_node.Mode = value
	}
	if value, ok := _c.mutation.State(); ok {
		_spec.SetField(deposit.FieldState, field.TypeEnum, value)
		_node.State = value
	}
	if value, ok := _c.mutation.CreditCycle(); ok {
		_spec.SetField(deposit.FieldCreditCycle, field.TypeInt, value)
		_node.CreditCycle = value
	}
	if value, ok := _c.mutation.BlockHeight(); ok {
		_spec.SetField(deposit.FieldBlockHeight, field.TypeInt64, value)
		_node.BlockHeight = &value
	}
	if value, ok := _c.mutation.BlockHash(); ok {
		_spec.SetField(deposit.FieldBlockHash, field.TypeString, value)
		_node.BlockHash = &value
	}
	if value, ok := _c.mutation.ReorgedHeight(); ok {
		_spec.SetField(deposit.FieldReorgedHeight, field.TypeInt64, value)
		_node.ReorgedHeight = &value
	}
	if value, ok := _c.mutation.TxHash(); ok {
		_spec.SetField(deposit.FieldTxHash, field.TypeString, value)
		_node.TxHash = &value
	}
	if value, ok := _c.mutation.SourceEvent(); ok {
		_spec.SetField(deposit.FieldSourceEvent, field.TypeString, value)
		_node.SourceEvent = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(deposit.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(deposit.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// DepositCreateBulk is the builder for creating many Deposit entities in bulk.
type DepositCreateBulk struct {
	config
	err      error
	builders []*DepositCreate
}

// Save creates the Deposit entities in the database.
func (_c *DepositCreateBulk) Save(ctx context.Context) ([]*Deposit, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Deposit, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DepositMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *DepositCreateBulk) SaveX(ctx context.Context) []*Deposit {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DepositCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DepositCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
