// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"deposit-crediting/internal/store/ent/depositaddress"
	"deposit-crediting/internal/store/ent/predicate"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DepositAddressUpdate is the builder for updating DepositAddress entities.
type DepositAddressUpdate struct {
	config
	hooks    []Hook
	mutation *DepositAddressMutation
}

// Where appends a list predicates to the DepositAddressUpdate builder.
func (_u *DepositAddressUpdate) Where(ps ...predicate.DepositAddress) *DepositAddressUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetAccount sets the "account" field.
func (_u *DepositAddressUpdate) SetAccount(v string) *DepositAddressUpdate {
	_u.mutation.SetAccount(v)
	return _u
}

// SetNillableAccount sets the "account" field if the given value is not nil.
func (_u *DepositAddressUpdate) SetNillableAccount(v *string) *DepositAddressUpdate {
	if v != nil {
		_u.SetAccount(*v)
	}
	return _u
}

// SetChain sets the "chain" field.
func (_u *DepositAddressUpdate) SetChain(v string) *DepositAddressUpdate {
	_u.mutation.SetChain(v)
	return _u
}

// SetNillableChain sets the "chain" field if the given value is not nil.
func (_u *DepositAddressUpdate) SetNillableChain(v *string) *DepositAddressUpdate {
	if v != nil {
		_u.SetChain(*v)
	}
	return _u
}

// SetAddress sets the "address" field.
func (_u *DepositAddressUpdate) SetAddress(v string) *DepositAddressUpdate {
	_u.mutation.SetAddress(v)
	return _u
}

// SetNillableAddress sets the "address" field if the given value is not nil.
func (_u *DepositAddressUpdate) SetNillableAddress(v *string) *DepositAddressUpdate {
	if v != nil {
		_u.SetAddress(*v)
	}
	return _u
}

// SetActive sets the "active" field.
func (_u *DepositAddressUpdate) SetActive(v bool) *DepositAddressUpdate {
	_u.mutation.SetActive(v)
	return _u
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (_u *DepositAddressUpdate) SetNillableActive(v *bool) *DepositAddressUpdate {
	if v != nil {
		_u.SetActive(*v)
	}
	return _u
}

// Mutation returns the DepositAddressMutation object of the builder.
func (_u *DepositAddressUpdate) Mutation() *DepositAddressMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DepositAddressUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DepositAddressUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DepositAddressUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DepositAddressUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DepositAddressUpdate) check() error {
	if v, ok := _u.mutation.Account(); ok {
		if err := depositaddress.AccountValidator(v); err != nil {
			return &ValidationError{Name: "account", err: fmt.Errorf(`ent: validator failed for field "DepositAddress.account": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Chain(); ok {
		if err := depositaddress.ChainValidator(v); err != nil {
			return &ValidationError{Name: "chain", err: fmt.Errorf(`ent: validator failed for field "DepositAddress.chain": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Address(); ok {
		if err := depositaddress.AddressValidator(v); err != nil {
			return &ValidationError{Name: "address", err: fmt.Errorf(`ent: validator failed for field "DepositAddress.address": %w`, err)}
		}
	}
	return nil
}

func (_u *DepositAddressUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(depositaddress.Table, depositaddress.Columns, sqlgraph.NewFieldSpec(depositaddress.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Account(); ok {
		_spec.SetField(depositaddress.FieldAccount, field.TypeString, value)
	}
	if value, ok := _u.mutation.Chain(); ok {
		_spec.SetField(depositaddress.FieldChain, field.TypeString, value)
	}
	if value, ok := _u.mutation.Address(); ok {
		_spec.SetField(depositaddress.FieldAddress, field.TypeString, value)
	}
	if value, ok := _u.mutation.Active(); ok {
		_spec.SetField(depositaddress.FieldActive, field.TypeBool, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{depositaddress.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DepositAddressUpdateOne is the builder for updating a single DepositAddress entity.
type DepositAddressUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DepositAddressMutation
}

// SetAccount sets the "account" field.
func (_u *DepositAddressUpdateOne) SetAccount(v string) *DepositAddressUpdateOne {
	_u.mutation.SetAccount(v)
	return _u
}

// SetNillableAccount sets the "account" field if the given value is not nil.
func (_u *DepositAddressUpdateOne) SetNillableAccount(v *string) *DepositAddressUpdateOne {
	if v != nil {
		_u.SetAccount(*v)
	}
	return _u
}

// SetChain sets the "chain" field.
func (_u *DepositAddressUpdateOne) SetChain(v string) *DepositAddressUpdateOne {
	_u.mutation.SetChain(v)
	return _u
}

// SetNillableChain sets the "chain" field if the given value is not nil.
func (_u *DepositAddressUpdateOne) SetNillableChain(v *string) *DepositAddressUpdateOne {
	if v != nil {
		_u.SetChain(*v)
	}
	return _u
}

// SetAddress sets the "address" field.
func (_u *DepositAddressUpdateOne) SetAddress(v string) *DepositAddressUpdateOne {
	_u.mutation.SetAddress(v)
	return _u
}

// SetNillableAddress sets the "address" field if the given value is not nil.
func (_u *DepositAddressUpdateOne) SetNillableAddress(v *string) *DepositAddressUpdateOne {
	if v != nil {
		_u.SetAddress(*v)
	}
	return _u
}

// SetActive sets the "active" field.
func (_u *DepositAddressUpdateOne) SetActive(v bool) *DepositAddressUpdateOne {
	_u.mutation.SetActive(v)
	return _u
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (_u *DepositAddressUpdateOne) SetNillableActive(v *bool) *DepositAddressUpdateOne {
	if v != nil {
		_u.SetActive(*v)
	}
	return _u
}

// Mutation returns the DepositAddressMutation object of the builder.
func (_u *DepositAddressUpdateOne) Mutation() *DepositAddressMutation {
	return _u.mutation
}

// Where appends a list predicates to the DepositAddressUpdate builder.
func (_u *DepositAddressUpdateOne) Where(ps ...predicate.DepositAddress) *DepositAddressUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DepositAddressUpdateOne) Select(field string, fields ...string) *DepositAddressUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated DepositAddress entity.
func (_u *DepositAddressUpdateOne) Save(ctx context.Context) (*DepositAddress, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DepositAddressUpdateOne) SaveX(ctx context.Context) *DepositAddress {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DepositAddressUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DepositAddressUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DepositAddressUpdateOne) check() error {
	if v, ok := _u.mutation.Account(); ok {
		if err := depositaddress.AccountValidator(v); err != nil {
			return &ValidationError{Name: "account", err: fmt.Errorf(`ent: validator failed for field "DepositAddress.account": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Chain(); ok {
		if err := depositaddress.ChainValidator(v); err != nil {
			return &ValidationError{Name: "chain", err: fmt.Errorf(`ent: validator failed for field "DepositAddress.chain": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Address(); ok {
		if err := depositaddress.AddressValidator(v); err != nil {
			return &ValidationError{Name: "address", err: fmt.Errorf(`ent: validator failed for field "DepositAddress.address": %w`, err)}
		}
	}
	return nil
}

func (_u *DepositAddressUpdateOne) sqlSave(ctx context.Context) (_node *DepositAddress, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(depositaddress.Table, depositaddress.Columns, sqlgraph.NewFieldSpec(depositaddress.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "DepositAddress.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, depositaddress.FieldID)
		for _, f := range fields {
			if !depositaddress.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != depositaddress.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Account(); ok {
		_spec.SetField(depositaddress.FieldAccount, field.TypeString, value)
	}
	if value, ok := _u.mutation.Chain(); ok {
		_spec.SetField(depositaddress.FieldChain, field.TypeString, value)
	}
	if value, ok := _u.mutation.Address(); ok {
		_spec.SetField(depositaddress.FieldAddress, field.TypeString, value)
	}
	if value, ok := _u.mutation.Active(); ok {
		_spec.SetField(depositaddress.FieldActive, field.TypeBool, value)
	}
	_node = &DepositAddress{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{depositaddress.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
