// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"deposit-crediting/internal/store/ent/deposit"
	"deposit-crediting/internal/store/ent/predicate"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DepositUpdate is the builder for updating Deposit entities.
type DepositUpdate struct {
	config
	hooks    []Hook
	mutation *DepositMutation
}

// Where appends a list predicates to the DepositUpdate builder.
func (_u *DepositUpdate) Where(ps ...predicate.Deposit) *DepositUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetChain sets the "chain" field.
func (_u *DepositUpdate) SetChain(v string) *DepositUpdate {
	_u.mutation.SetChain(v)
	return _u
}

// SetNillableChain sets the "chain" field if the given value is not nil.
func (_u *DepositUpdate) SetNillableChain(v *string) *DepositUpdate {
	if v != nil {
		_u.SetChain(*v)
	}
	return _u
}

// SetAsset sets the "asset" field.
func (_u *DepositUpdate) SetAsset(v string) *DepositUpdate {
	_u.mutation.SetAsset(v)
	return _u
}

// SetNillableAsset sets the "asset" field if the given value is not nil.
func (_u *DepositUpdate) SetNillableAsset(v *string) *DepositUpdate {
	if v != nil {
		_u.SetAsset(*v)
	}
	return _u
}

// SetAccount sets the "account" field.
func (_u *DepositUpdate) SetAccount(v string) *DepositUpdate {
	_u.mutation.SetAccount(v)
	return _u
}

// SetNillableAccount sets the "account" field if the given value is not nil.
func (_u *DepositUpdate) SetNillableAccount(v *string) *DepositUpdate {
	if v != nil {
		_u.SetAccount(*v)
	}
	return _u
}

// SetAddress sets the "address" field.
func (_u *DepositUpdate) SetAddress(v string) *DepositUpdate {
	_u.mutation.SetAddress(v)
	return _u
}

// SetNillableAddress sets the "address" field if the given value is not nil.
func (_u *DepositUpdate) SetNillableAddress(v *string) *DepositUpdate {
	if v != nil {
		_u.SetAddress(*v)
	}
	return _u
}

// SetAmount sets the "amount" field.
func (_u *DepositUpdate) SetAmount(v string) *DepositUpdate {
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *DepositUpdate) SetNillableAmount(v *string) *DepositUpdate {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// SetMode sets the "mode" field.
func (_u *DepositUpdate) SetMode(v deposit.Mode) *DepositUpdate {
	_u.mutation.SetMode(v)
	return _u
}

// SetNillableMode sets the "mode" field if the given value is not nil.
func (_u *DepositUpdate) SetNillableMode(v *deposit.Mode) *DepositUpdate {
	if v != nil {
		_u.SetMode(*v)
	}
	return _u
}

// SetState sets the "state" field.
func (_u *DepositUpdate) SetState(v deposit.State) *DepositUpdate {
	_u.mutation.SetState(v)
	return _u
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_u *DepositUpdate) SetNillableState(v *deposit.State) *DepositUpdate {
	if v != nil {
		_u.SetState(*v)
	}
	return _u
}

// SetCreditCycle sets the "credit_cycle" field.
func (_u *DepositUpdate) SetCreditCycle(v int) *DepositUpdate {
	_u.mutation.ResetCreditCycle()
	_u.mutation.SetCreditCycle(v)
	return _u
}

// SetNillableCreditCycle sets the "credit_cycle" field if the given value is not nil.
func (_u *DepositUpdate) SetNillableCreditCycle(v *int) *DepositUpdate {
	if v != nil {
		_u.SetCreditCycle(*v)
	}
	return _u
}

// AddCreditCycle adds value to the "credit_cycle" field.
func (_u *DepositUpdate) AddCreditCycle(v int) *DepositUpdate {
	_u.mutation.AddCreditCycle(v)
	return _u
}

// SetBlockHeight sets the "block_height" field.
func (_u *DepositUpdate) SetBlockHeight(v int64) *DepositUpdate {
	_u.mutation.ResetBlockHeight()
	_u.mutation.SetBlockHeight(v)
	return _u
}

// SetNillableBlockHeight sets the "block_height" field if the given value is not nil.
func (_u *DepositUpdate) SetNillableBlockHeight(v *int64) *DepositUpdate {
	if v != nil {
		_u.SetBlockHeight(*v)
	}
	return _u
}

// AddBlockHeight adds value to the "block_height" field.
func (_u *DepositUpdate) AddBlockHeight(v int64) *DepositUpdate {
	_u.mutation.AddBlockHeight(v)
	return _u
}

// ClearBlockHeight clears the value of the "block_height" field.
func (_u *DepositUpdate) ClearBlockHeight() *DepositUpdate {
	_u.mutation.ClearBlockHeight()
	return _u
}

// SetBlockHash sets the "block_hash" field.
func (_u *DepositUpdate) SetBlockHash(v string) *DepositUpdate {
	_u.mutation.SetBlockHash(v)
	return _u
}

// SetNillableBlockHash sets the "block_hash" field if the given value is not nil.
func (_u *DepositUpdate) SetNillableBlockHash(v *string) *DepositUpdate {
	if v != nil {
		_u.SetBlockHash(*v)
	}
	return _u
}

// ClearBlockHash clears the value of the "block_hash" field.
func (_u *DepositUpdate) ClearBlockHash() *DepositUpdate {
	_u.mutation.ClearBlockHash()
	return _u
}

// SetReorgedHeight sets the "reorged_height" field.
func (_u *DepositUpdate) SetReorgedHeight(v int64) *DepositUpdate {
	_u.mutation.ResetReorgedHeight()
	_u.mutation.SetReorgedHeight(v)
	return _u
}

// SetNillableReorgedHeight sets the "reorged_height" field if the given value is not nil.
func (_u *DepositUpdate) SetNillableReorgedHeight(v *int64) *DepositUpdate {
	if v != nil {
		_u.SetReorgedHeight(*v)
	}
	return _u
}

// AddReorgedHeight adds value to the "reorged_height" field.
func (_u *DepositUpdate) AddReorgedHeight(v int64) *DepositUpdate {
	_u.mutation.AddReorgedHeight(v)
	return _u
}

// ClearReorgedHeight clears the value of the "reorged_height" field.
func (_u *DepositUpdate) ClearReorgedHeight() *DepositUpdate {
	_u.mutation.ClearReorgedHeight()
	return _u
}

// SetTxHash sets the "tx_hash" field.
func (_u *DepositUpdate) SetTxHash(v string) *DepositUpdate {
	_u.mutation.SetTxHash(v)
	return _u
}

// SetNillableTxHash sets the "tx_hash" field if the given value is not nil.
func (_u *DepositUpdate) SetNillableTxHash(v *string) *DepositUpdate {
	if v != nil {
		_u.SetTxHash(*v)
	}
	return _u
}

// ClearTxHash clears the value of the "tx_hash" field.
func (_u *DepositUpdate) ClearTxHash() *DepositUpdate {
	_u.mutation.ClearTxHash()
	return _u
}

// SetSourceEvent sets the "source_event" field.
func (_u *DepositUpdate) SetSourceEvent(v string) *DepositUpdate {
	_u.mutation.SetSourceEvent(v)
	return _u
}

// SetNillableSourceEvent sets the "source_event" field if the given value is not nil.
func (_u *DepositUpdate) SetNillableSourceEvent(v *string) *DepositUpdate {
	if v != nil {
		_u.SetSourceEvent(*v)
	}
	return _u
}

// ClearSourceEvent clears the value of the "source_event" field.
func (_u *DepositUpdate) ClearSourceEvent() *DepositUpdate {
	_u.mutation.ClearSourceEvent()
	return _u
}

// SetHeld sets the "held" field.
func (_u *DepositUpdate) SetHeld(v bool) *DepositUpdate {
	_u.mutation.SetHeld(v)
	return _u
}

// SetNillableHeld sets the "held" field if the given value is not nil.
func (_u *DepositUpdate) SetNillableHeld(v *bool) *DepositUpdate {
	if v != nil {
		_u.SetHeld(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DepositUpdate) SetUpdatedAt(v time.Time) *DepositUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the DepositMutation object of the builder.
func (_u *DepositUpdate) Mutation() *DepositMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DepositUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DepositUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DepositUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DepositUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DepositUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := deposit.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DepositUpdate) check() error {
	if v, ok := _u.mutation.Chain(); ok {
		if err := deposit.ChainValidator(v); err != nil {
			return &ValidationError{Name: "chain", err: fmt.Errorf(`ent: validator failed for field "Deposit.chain": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Asset(); ok {
		if err := deposit.AssetValidator(v); err != nil {
			return &ValidationError{Name: "asset", err: fmt.Errorf(`ent: validator failed for field "Deposit.asset": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Account(); ok {
		if err := deposit.AccountValidator(v); err != nil {
			return &ValidationError{Name: "account", err: fmt.Errorf(`ent: validator failed for field "Deposit.account": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Address(); ok {
		if err := deposit.AddressValidator(v); err != nil {
			return &ValidationError{Name: "address", err: fmt.Errorf(`ent: validator failed for field "Deposit.address": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Mode(); ok {
		if err := deposit.ModeValidator(v); err != nil {
			return &ValidationError{Name: "mode", err: fmt.Errorf(`ent: validator failed for field "Deposit.mode": %w`, err)}
		}
	}
	if v, ok := _u.mutation.State(); ok {
		if err := deposit.StateValidator(v); err != nil {
			return &ValidationError{Name: "state", err: fmt.Errorf(`ent: validator failed for field "Deposit.state": %w`, err)}
		}
	}
	return nil
}

func (_u *DepositUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(deposit.Table, deposit.Columns, sqlgraph.NewFieldSpec(deposit.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Chain(); ok {
		_spec.SetField(deposit.FieldChain, field.TypeString, value)
	}
	if value, ok := _u.mutation.Asset(); ok {
		_spec.SetField(deposit.FieldAsset, field.TypeString, value)
	}
	if value, ok := _u.mutation.Account(); ok {
		_spec.SetField(deposit.FieldAccount, field.TypeString, value)
	}
	if value, ok := _u.mutation.Address(); ok {
		_spec.SetField(deposit.FieldAddress, field.TypeString, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(deposit.FieldAmount, field.TypeString, value)
	}
	if value, ok := _u.mutation.Mode(); ok {
		_spec.SetField(deposit.FieldMode, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.State(); ok {
		_spec.SetField(deposit.FieldState, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.CreditCycle(); ok {
		_spec.SetField(deposit.FieldCreditCycle, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCreditCycle(); ok {
		_spec.AddField(deposit.FieldCreditCycle, field.TypeInt, value)
	}
	if value, ok := _u.mutation.BlockHeight(); ok {
		_spec.SetField(deposit.FieldBlockHeight, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedBlockHeight(); ok {
		_spec.AddField(deposit.FieldBlockHeight, field.TypeInt64, value)
	}
	if _u.mutation.BlockHeightCleared() {
		_spec.ClearField(deposit.FieldBlockHeight, field.TypeInt64)
	}
	if value, ok := _u.mutation.BlockHash(); ok {
		_spec.SetField(deposit.FieldBlockHash, field.TypeString, value)
	}
	if _u.mutation.BlockHashCleared() {
		_spec.ClearField(deposit.FieldBlockHash, field.TypeString)
	}
	if value, ok := _u.mutation.ReorgedHeight(); ok {
		_spec.SetField(deposit.FieldReorgedHeight, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedReorgedHeight(); ok {
		_spec.AddField(deposit.FieldReorgedHeight, field.TypeInt64, value)
	}
	if _u.mutation.ReorgedHeightCleared() {
		_spec.ClearField(deposit.FieldReorgedHeight, field.TypeInt64)
	}
	if value, ok := _u.mutation.TxHash(); ok {
		_spec.SetField(deposit.FieldTxHash, field.TypeString, value)
	}
	if _u.mutation.TxHashCleared() {
		_spec.ClearField(deposit.FieldTxHash, field.TypeString)
	}
	if value, ok := _u.mutation.SourceEvent(); ok {
		_spec.SetField(deposit.FieldSourceEvent, field.TypeString, value)
	}
	if _u.mutation.SourceEventCleared() {
		_spec.ClearField(deposit.FieldSourceEvent, field.TypeString)
	}
	if value, ok := _u.mutation.Held(); ok {
		_spec.SetField(deposit.FieldHeld, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(deposit.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{deposit.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DepositUpdateOne is the builder for updating a single Deposit entity.
type DepositUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DepositMutation
}

// SetChain sets the "chain" field.
func (_u *DepositUpdateOne) SetChain(v string) *DepositUpdateOne {
	_u.mutation.SetChain(v)
	return _u
}

// SetNillableChain sets the "chain" field if the given value is not nil.
func (_u *DepositUpdateOne) SetNillableChain(v *string) *DepositUpdateOne {
	if v != nil {
		_u.SetChain(*v)
	}
	return _u
}

// SetAsset sets the "asset" field.
func (_u *DepositUpdateOne) SetAsset(v string) *DepositUpdateOne {
	_u.mutation.SetAsset(v)
	return _u
}

// SetNillableAsset sets the "asset" field if the given value is not nil.
func (_u *DepositUpdateOne) SetNillableAsset(v *string) *DepositUpdateOne {
	if v != nil {
		_u.SetAsset(*v)
	}
	return _u
}

// SetAccount sets the "account" field.
func (_u *DepositUpdateOne) SetAccount(v string) *DepositUpdateOne {
	_u.mutation.SetAccount(v)
	return _u
}

// SetNillableAccount sets the "account" field if the given value is not nil.
func (_u *DepositUpdateOne) SetNillableAccount(v *string) *DepositUpdateOne {
	if v != nil {
		_u.SetAccount(*v)
	}
	return _u
}

// SetAddress sets the "address" field.
func (_u *DepositUpdateOne) SetAddress(v string) *DepositUpdateOne {
	_u.mutation.SetAddress(v)
	return _u
}

// SetNillableAddress sets the "address" field if the given value is not nil.
func (_u *DepositUpdateOne) SetNillableAddress(v *string) *DepositUpdateOne {
	if v != nil {
		_u.SetAddress(*v)
	}
	return _u
}

// SetAmount sets the "amount" field.
func (_u *DepositUpdateOne) SetAmount(v string) *DepositUpdateOne {
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *DepositUpdateOne) SetNillableAmount(v *string) *DepositUpdateOne {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// SetMode sets the "mode" field.
func (_u *DepositUpdateOne) SetMode(v deposit.Mode) *DepositUpdateOne {
	_u.mutation.SetMode(v)
	return _u
}

// SetNillableMode sets the "mode" field if the given value is not nil.
func (_u *DepositUpdateOne) SetNillableMode(v *deposit.Mode) *DepositUpdateOne {
	if v != nil {
		_u.SetMode(*v)
	}
	return _u
}

// SetState sets the "state" field.
func (_u *DepositUpdateOne) SetState(v deposit.State) *DepositUpdateOne {
	_u.mutation.SetState(v)
	return _u
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_u *DepositUpdateOne) SetNillableState(v *deposit.State) *DepositUpdateOne {
	if v != nil {
		_u.SetState(*v)
	}
	return _u
}

// SetCreditCycle sets the "credit_cycle" field.
func (_u *DepositUpdateOne) SetCreditCycle(v int) *DepositUpdateOne {
	_u.mutation.ResetCreditCycle()
	_u.mutation.SetCreditCycle(v)
	return _u
}

// SetNillableCreditCycle sets the "credit_cycle" field if the given value is not nil.
func (_u *DepositUpdateOne) SetNillableCreditCycle(v *int) *DepositUpdateOne {
	if v != nil {
		_u.SetCreditCycle(*v)
	}
	return _u
}

// AddCreditCycle adds value to the "credit_cycle" field.
func (_u *DepositUpdateOne) AddCreditCycle(v int) *DepositUpdateOne {
	_u.mutation.AddCreditCycle(v)
	return _u
}

// SetBlockHeight sets the "block_height" field.
func (_u *DepositUpdateOne) SetBlockHeight(v int64) *DepositUpdateOne {
	_u.mutation.ResetBlockHeight()
	_u.mutation.SetBlockHeight(v)
	return _u
}

// SetNillableBlockHeight sets the "block_height" field if the given value is not nil.
func (_u *DepositUpdateOne) SetNillableBlockHeight(v *int64) *DepositUpdateOne {
	if v != nil {
		_u.SetBlockHeight(*v)
	}
	return _u
}

// AddBlockHeight adds value to the "block_height" field.
func (_u *DepositUpdateOne) AddBlockHeight(v int64) *DepositUpdateOne {
	_u.mutation.AddBlockHeight(v)
	return _u
}

// ClearBlockHeight clears the value of the "block_height" field.
func (_u *DepositUpdateOne) ClearBlockHeight() *DepositUpdateOne {
	_u.mutation.ClearBlockHeight()
	return _u
}

// SetBlockHash sets the "block_hash" field.
func (_u *DepositUpdateOne) SetBlockHash(v string) *DepositUpdateOne {
	_u.mutation.SetBlockHash(v)
	return _u
}

// SetNillableBlockHash sets the "block_hash" field if the given value is not nil.
func (_u *DepositUpdateOne) SetNillableBlockHash(v *string) *DepositUpdateOne {
	if v != nil {
		_u.SetBlockHash(*v)
	}
	return _u
}

// ClearBlockHash clears the value of the "block_hash" field.
func (_u *DepositUpdateOne) ClearBlockHash() *DepositUpdateOne {
	_u.mutation.ClearBlockHash()
	return _u
}

// SetReorgedHeight sets the "reorged_height" field.
func (_u *DepositUpdateOne) SetReorgedHeight(v int64) *DepositUpdateOne {
	_u.mutation.ResetReorgedHeight()
	_u.mutation.SetReorgedHeight(v)
	return _u
}

// SetNillableReorgedHeight sets the "reorged_height" field if the given value is not nil.
func (_u *DepositUpdateOne) SetNillableReorgedHeight(v *int64) *DepositUpdateOne {
	if v != nil {
		_u.SetReorgedHeight(*v)
	}
	return _u
}

// AddReorgedHeight adds value to the "reorged_height" field.
func (_u *DepositUpdateOne) AddReorgedHeight(v int64) *DepositUpdateOne {
	_u.mutation.AddReorgedHeight(v)
	return _u
}

// ClearReorgedHeight clears the value of the "reorged_height" field.
func (_u *DepositUpdateOne) ClearReorgedHeight() *DepositUpdateOne {
	_u.mutation.ClearReorgedHeight()
	return _u
}

// SetTxHash sets the "tx_hash" field.
func (_u *DepositUpdateOne) SetTxHash(v string) *DepositUpdateOne {
	_u.mutation.SetTxHash(v)
	return _u
}

// SetNillableTxHash sets the "tx_hash" field if the given value is not nil.
func (_u *DepositUpdateOne) SetNillableTxHash(v *string) *DepositUpdateOne {
	if v != nil {
		_u.SetTxHash(*v)
	}
	return _u
}

// ClearTxHash clears the value of the "tx_hash" field.
func (_u *DepositUpdateOne) ClearTxHash() *DepositUpdateOne {
	_u.mutation.ClearTxHash()
	return _u
}

// SetSourceEvent sets the "source_event" field.
func (_u *DepositUpdateOne) SetSourceEvent(v string) *DepositUpdateOne {
	_u.mutation.SetSourceEvent(v)
	return _u
}

// SetNillableSourceEvent sets the "source_event" field if the given value is not nil.
func (_u *DepositUpdateOne) SetNillableSourceEvent(v *string) *DepositUpdateOne {
	if v != nil {
		_u.SetSourceEvent(*v)
	}
	return _u
}

// ClearSourceEvent clears the value of the "source_event" field.
func (_u *DepositUpdateOne) ClearSourceEvent() *DepositUpdateOne {
	_u.mutation.ClearSourceEvent()
	return _u
}

// SetHeld sets the "held" field.
func (_u *DepositUpdateOne) SetHeld(v bool) *DepositUpdateOne {
	_u.mutation.SetHeld(v)
	return _u
}

// SetNillableHeld sets the "held" field if the given value is not nil.
func (_u *DepositUpdateOne) SetNillableHeld(v *bool) *DepositUpdateOne {
	if v != nil {
		_u.SetHeld(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DepositUpdateOne) SetUpdatedAt(v time.Time) *DepositUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the DepositMutation object of the builder.
func (_u *DepositUpdateOne) Mutation() *DepositMutation {
	return _u.mutation
}

// Where appends a list predicates to the DepositUpdate builder.
func (_u *DepositUpdateOne) Where(ps ...predicate.Deposit) *DepositUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DepositUpdateOne) Select(field string, fields ...string) *DepositUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Deposit entity.
func (_u *DepositUpdateOne) Save(ctx context.Context) (*Deposit, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DepositUpdateOne) SaveX(ctx context.Context) *Deposit {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DepositUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DepositUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DepositUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := deposit.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DepositUpdateOne) check() error {
	if v, ok := _u.mutation.Chain(); ok {
		if err := deposit.ChainValidator(v); err != nil {
			return &ValidationError{Name: "chain", err: fmt.Errorf(`ent: validator failed for field "Deposit.chain": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Asset(); ok {
		if err := deposit.AssetValidator(v); err != nil {
			return &ValidationError{Name: "asset", err: fmt.Errorf(`ent: validator failed for field "Deposit.asset": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Account(); ok {
		if err := deposit.AccountValidator(v); err != nil {
			return &ValidationError{Name: "account", err: fmt.Errorf(`ent: validator failed for field "Deposit.account": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Address(); ok {
		if err := deposit.AddressValidator(v); err != nil {
			return &ValidationError{Name: "address", err: fmt.Errorf(`ent: validator failed for field "Deposit.address": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Mode(); ok {
		if err := deposit.ModeValidator(v); err != nil {
			return &ValidationError{Name: "mode", err: fmt.Errorf(`ent: validator failed for field "Deposit.mode": %w`, err)}
		}
	}
	if v, ok := _u.mutation.State(); ok {
		if err := deposit.StateValidator(v); err != nil {
			return &ValidationError{Name: "state", err: fmt.Errorf(`ent: validator failed for field "Deposit.state": %w`, err)}
		}
	}
	return nil
}

func (_u *DepositUpdateOne) sqlSave(ctx context.Context) (_node *Deposit, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(deposit.Table, deposit.Columns, sqlgraph.NewFieldSpec(deposit.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Deposit.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, deposit.FieldID)
		for _, f := range fields {
			if !deposit.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != deposit.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Chain(); ok {
		_spec.SetField(deposit.FieldChain, field.TypeString, value)
	}
	if value, ok := _u.mutation.Asset(); ok {
		_spec.SetField(deposit.FieldAsset, field.TypeString, value)
	}
	if value, ok := _u.mutation.Account(); ok {
		_spec.SetField(deposit.FieldAccount, field.TypeString, value)
	}
	if value, ok := _u.mutation.Address(); ok {
		_spec.SetField(deposit.FieldAddress, field.TypeString, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(deposit.FieldAmount, field.TypeString, value)
	}
	if value, ok := _u.mutation.Mode(); ok {
		_spec.SetField(deposit.FieldMode, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.State(); ok {
		_spec.SetField(deposit.FieldState, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.CreditCycle(); ok {
		_spec.SetField(deposit.FieldCreditCycle, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCreditCycle(); ok {
		_spec.AddField(deposit.FieldCreditCycle, field.TypeInt, value)
	}
	if value, ok := _u.mutation.BlockHeight(); ok {
		_spec.SetField(deposit.FieldBlockHeight, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedBlockHeight(); ok {
		_spec.AddField(deposit.FieldBlockHeight, field.TypeInt64, value)
	}
	if _u.mutation.BlockHeightCleared() {
		_spec.ClearField(deposit.FieldBlockHeight, field.TypeInt64)
	}
	if value, ok := _u.mutation.BlockHash(); ok {
		_spec.SetField(deposit.FieldBlockHash, field.TypeString, value)
	}
	if _u.mutation.BlockHashCleared() {
		_spec.ClearField(deposit.FieldBlockHash, field.TypeString)
	}
	if value, ok := _u.mutation.ReorgedHeight(); ok {
		_spec.SetField(deposit.FieldReorgedHeight, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedReorgedHeight(); ok {
		_spec.AddField(deposit.FieldReorgedHeight, field.TypeInt64, value)
	}
	if _u.mutation.ReorgedHeightCleared() {
		_spec.ClearField(deposit.FieldReorgedHeight, field.TypeInt64)
	}
	if value, ok := _u.mutation.TxHash(); ok {
		_spec.SetField(deposit.FieldTxHash, field.TypeString, value)
	}
	if _u.mutation.TxHashCleared() {
		_spec.ClearField(deposit.FieldTxHash, field.TypeString)
	}
	if value, ok := _u.mutation.SourceEvent(); ok {
		_spec.SetField(deposit.FieldSourceEvent, field.TypeString, value)
	}
	if _u.mutation.SourceEventCleared() {
		_spec.ClearField(deposit.FieldSourceEvent, field.TypeString)
	}
	if value, ok := _u.mutation.Held(); ok {
		_spec.SetField(deposit.FieldHeld, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(deposit.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &Deposit{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{deposit.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
