// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"deposit-crediting/internal/store/ent/exposurestate"
	"deposit-crediting/internal/store/ent/predicate"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ExposureStateUpdate is the builder for updating ExposureState entities.
type ExposureStateUpdate struct {
	config
	hooks    []Hook
	mutation *ExposureStateMutation
}

// Where appends a list predicates to the ExposureStateUpdate builder.
func (_u *ExposureStateUpdate) Where(ps ...predicate.ExposureState) *ExposureStateUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetChain sets the "chain" field.
func (_u *ExposureStateUpdate) SetChain(v string) *ExposureStateUpdate {
	_u.mutation.SetChain(v)
	return _u
}

// SetNillableChain sets the "chain" field if the given value is not nil.
func (_u *ExposureStateUpdate) SetNillableChain(v *string) *ExposureStateUpdate {
	if v != nil {
		_u.SetChain(*v)
	}
	return _u
}

// SetAsset sets the "asset" field.
func (_u *ExposureStateUpdate) SetAsset(v string) *ExposureStateUpdate {
	_u.mutation.SetAsset(v)
	return _u
}

// SetNillableAsset sets the "asset" field if the given value is not nil.
func (_u *ExposureStateUpdate) SetNillableAsset(v *string) *ExposureStateUpdate {
	if v != nil {
		_u.SetAsset(*v)
	}
	return _u
}

// SetHoldsActive sets the "holds_active" field.
func (_u *ExposureStateUpdate) SetHoldsActive(v bool) *ExposureStateUpdate {
	_u.mutation.SetHoldsActive(v)
	return _u
}

// SetNillableHoldsActive sets the "holds_active" field if the given value is not nil.
func (_u *ExposureStateUpdate) SetNillableHoldsActive(v *bool) *ExposureStateUpdate {
	if v != nil {
		_u.SetHoldsActive(*v)
	}
	return _u
}

// SetExposure sets the "exposure" field.
func (_u *ExposureStateUpdate) SetExposure(v string) *ExposureStateUpdate {
	_u.mutation.SetExposure(v)
	return _u
}

// SetNillableExposure sets the "exposure" field if the given value is not nil.
func (_u *ExposureStateUpdate) SetNillableExposure(v *string) *ExposureStateUpdate {
	if v != nil {
		_u.SetExposure(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ExposureStateUpdate) SetUpdatedAt(v time.Time) *ExposureStateUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the ExposureStateMutation object of the builder.
func (_u *ExposureStateUpdate) Mutation() *ExposureStateMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ExposureStateUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ExposureStateUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ExposureStateUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ExposureStateUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ExposureStateUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := exposurestate.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ExposureStateUpdate) check() error {
	if v, ok := _u.mutation.Chain(); ok {
		if err := exposurestate.ChainValidator(v); err != nil {
			return &ValidationError{Name: "chain", err: fmt.Errorf(`ent: validator failed for field "ExposureState.chain": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Asset(); ok {
		if err := exposurestate.AssetValidator(v); err != nil {
			return &ValidationError{Name: "asset", err: fmt.Errorf(`ent: validator failed for field "ExposureState.asset": %w`, err)}
		}
	}
	return nil
}

func (_u *ExposureStateUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(exposurestate.Table, exposurestate.Columns, sqlgraph.NewFieldSpec(exposurestate.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Chain(); ok {
		_spec.SetField(exposurestate.FieldChain, field.TypeString, value)
	}
	if value, ok := _u.mutation.Asset(); ok {
		_spec.SetField(exposurestate.FieldAsset, field.TypeString, value)
	}
	if value, ok := _u.mutation.HoldsActive(); ok {
		_spec.SetField(exposurestate.FieldHoldsActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Exposure(); ok {
		_spec.SetField(exposurestate.FieldExposure, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(exposurestate.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{exposurestate.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ExposureStateUpdateOne is the builder for updating a single ExposureState entity.
type ExposureStateUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ExposureStateMutation
}

// SetChain sets the "chain" field.
func (_u *ExposureStateUpdateOne) SetChain(v string) *ExposureStateUpdateOne {
	_u.mutation.SetChain(v)
	return _u
}

// SetNillableChain sets the "chain" field if the given value is not nil.
func (_u *ExposureStateUpdateOne) SetNillableChain(v *string) *ExposureStateUpdateOne {
	if v != nil {
		_u.SetChain(*v)
	}
	return _u
}

// SetAsset sets the "asset" field.
func (_u *ExposureStateUpdateOne) SetAsset(v string) *ExposureStateUpdateOne {
	_u.mutation.SetAsset(v)
	return _u
}

// SetNillableAsset sets the "asset" field if the given value is not nil.
func (_u *ExposureStateUpdateOne) SetNillableAsset(v *string) *ExposureStateUpdateOne {
	if v != nil {
		_u.SetAsset(*v)
	}
	return _u
}

// SetHoldsActive sets the "holds_active" field.
func (_u *ExposureStateUpdateOne) SetHoldsActive(v bool) *ExposureStateUpdateOne {
	_u.mutation.SetHoldsActive(v)
	return _u
}

// SetNillableHoldsActive sets the "holds_active" field if the given value is not nil.
func (_u *ExposureStateUpdateOne) SetNillableHoldsActive(v *bool) *ExposureStateUpdateOne {
	if v != nil {
		_u.SetHoldsActive(*v)
	}
	return _u
}

// SetExposure sets the "exposure" field.
func (_u *ExposureStateUpdateOne) SetExposure(v string) *ExposureStateUpdateOne {
	_u.mutation.SetExposure(v)
	return _u
}

// SetNillableExposure sets the "exposure" field if the given value is not nil.
func (_u *ExposureStateUpdateOne) SetNillableExposure(v *string) *ExposureStateUpdateOne {
	if v != nil {
		_u.SetExposure(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ExposureStateUpdateOne) SetUpdatedAt(v time.Time) *ExposureStateUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the ExposureStateMutation object of the builder.
func (_u *ExposureStateUpdateOne) Mutation() *ExposureStateMutation {
	return _u.mutation
}

// Where appends a list predicates to the ExposureStateUpdate builder.
func (_u *ExposureStateUpdateOne) Where(ps ...predicate.ExposureState) *ExposureStateUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ExposureStateUpdateOne) Select(field string, fields ...string) *ExposureStateUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ExposureState entity.
func (_u *ExposureStateUpdateOne) Save(ctx context.Context) (*ExposureState, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ExposureStateUpdateOne) SaveX(ctx context.Context) *ExposureState {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ExposureStateUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ExposureStateUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ExposureStateUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := exposurestate.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ExposureStateUpdateOne) check() error {
	if v, ok := _u.mutation.Chain(); ok {
		if err := exposurestate.ChainValidator(v); err != nil {
			return &ValidationError{Name: "chain", err: fmt.Errorf(`ent: validator failed for field "ExposureState.chain": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Asset(); ok {
		if err := exposurestate.AssetValidator(v); err != nil {
			return &ValidationError{Name: "asset", err: fmt.Errorf(`ent: validator failed for field "ExposureState.asset": %w`, err)}
		}
	}
	return nil
}

func (_u *ExposureStateUpdateOne) sqlSave(ctx context.Context) (_node *ExposureState, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(exposurestate.Table, exposurestate.Columns, sqlgraph.NewFieldSpec(exposurestate.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ExposureState.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, exposurestate.FieldID)
		for _, f := range fields {
			if !exposurestate.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != exposurestate.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Chain(); ok {
		_spec.SetField(exposurestate.FieldChain, field.TypeString, value)
	}
	if value, ok := _u.mutation.Asset(); ok {
		_spec.SetField(exposurestate.FieldAsset, field.TypeString, value)
	}
	if value, ok := _u.mutation.HoldsActive(); ok {
		_spec.SetField(exposurestate.FieldHoldsActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Exposure(); ok {
		_spec.SetField(exposurestate.FieldExposure, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(exposurestate.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &ExposureState{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{exposurestate.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
