// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"deposit-crediting/internal/store/ent/exposurestate"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ExposureStateCreate is the builder for creating a ExposureState entity.
type ExposureStateCreate struct {
	config
	mutation *ExposureStateMutation
	hooks    []Hook
}

// SetChain sets the "chain" field.
func (_c *ExposureStateCreate) SetChain(v string) *ExposureStateCreate {
	_c.mutation.SetChain(v)
	return _c
}

// SetAsset sets the "asset" field.
func (_c *ExposureStateCreate) SetAsset(v string) *ExposureStateCreate {
	_c.mutation.SetAsset(v)
	return _c
}

// SetHoldsActive sets the "holds_active" field.
func (_c *ExposureStateCreate) SetHoldsActive(v bool) *ExposureStateCreate {
	_c.mutation.SetHoldsActive(v)
	return _c
}

// SetNillableHoldsActive sets the "holds_active" field if the given value is not nil.
func (_c *ExposureStateCreate) SetNillableHoldsActive(v *bool) *ExposureStateCreate {
	if v != nil {
		_c.SetHoldsActive(*v)
	}
	return _c
}

// SetExposure sets the "exposure" field.
func (_c *ExposureStateCreate) SetExposure(v string) *ExposureStateCreate {
	_c.mutation.SetExposure(v)
	return _c
}

// SetNillableExposure sets the "exposure" field if the given value is not nil.
func (_c *ExposureStateCreate) SetNillableExposure(v *string) *ExposureStateCreate {
	if v != nil {
		_c.SetExposure(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ExposureStateCreate) SetUpdatedAt(v time.Time) *ExposureStateCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ExposureStateCreate) SetNillableUpdatedAt(v *time.Time) *ExposureStateCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the ExposureStateMutation object of the builder.
func (_c *ExposureStateCreate) Mutation() *ExposureStateMutation {
	return _c.mutation
}

// Save creates the ExposureState in the database.
func (_c *ExposureStateCreate) Save(ctx context.Context) (*ExposureState, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ExposureStateCreate) SaveX(ctx context.Context) *ExposureState {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ExposureStateCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ExposureStateCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ExposureStateCreate) defaults() {
	if _, ok := _c.mutation.HoldsActive(); !ok {
		v := exposurestate.DefaultHoldsActive
		_c.mutation.SetHoldsActive(v)
	}
	if _, ok := _c.mutation.Exposure(); !ok {
		v := exposurestate.DefaultExposure
		_c.mutation.SetExposure(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := exposurestate.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ExposureStateCreate) check() error {
	if _, ok := _c.mutation.Chain(); !ok {
		return &ValidationError{Name: "chain", err: errors.New(`ent: missing required field "ExposureState.chain"`)}
	}
	if v, ok := _c.mutation.Chain(); ok {
		if err := exposurestate.ChainValidator(v); err != nil {
			return &ValidationError{Name: "chain", err: fmt.Errorf(`ent: validator failed for field "ExposureState.chain": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Asset(); !ok {
		return &ValidationError{Name: "asset", err: errors.New(`ent: missing required field "ExposureState.asset"`)}
	}
	if v, ok := _c.mutation.Asset(); ok {
		if err := exposurestate.AssetValidator(v); err != nil {
			return &ValidationError{Name: "asset", err: fmt.Errorf(`ent: validator failed for field "ExposureState.asset": %w`, err)}
		}
	}
	if _, ok := _c.mutation.HoldsActive(); !ok {
		return &ValidationError{Name: "holds_active", err: errors.New(`ent: missing required field "ExposureState.holds_active"`)}
	}
	if _, ok := _c.mutation.Exposure(); !ok {
		return &ValidationError{Name: "exposure", err: errors.New(`ent: missing required field "ExposureState.exposure"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ExposureState.updated_at"`)}
	}
	return nil
}

func (_c *ExposureStateCreate) sqlSave(ctx context.Context) (*ExposureState, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ExposureStateCreate) createSpec() (*ExposureState, *sqlgraph.CreateSpec) {
	var (
		_node = &ExposureState{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(exposurestate.Table, sqlgraph.NewFieldSpec(exposurestate.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Chain(); ok {
		_spec.SetField(exposurestate.FieldChain, field.TypeString, value)
		_node.Chain = value
	}
	if value, ok := _c.mutation.Asset(); ok {
		_spec.SetField(exposurestate.FieldAsset, field.TypeString, value)
		_node.Asset = value
	}
	if value, ok := _c.mutation.HoldsActive(); ok {
		_spec.SetField(exposurestate.FieldHoldsActive, field.TypeBool, value)
		_node.HoldsActive = value
	}
	if value, ok := _c.mutation.Exposure(); ok {
		_spec.SetField(exposurestate.FieldExposure, field.TypeString, value)
		_node.Exposure = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(exposurestate.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// ExposureStateCreateBulk is the builder for creating many ExposureState entities in bulk.
type ExposureStateCreateBulk struct {
	config
	err      error
	builders []*ExposureStateCreate
}

// Save creates the ExposureState entities in the database.
func (_c *ExposureStateCreateBulk) Save(ctx context.Context) ([]*ExposureState, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ExposureState, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ExposureStateMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ExposureStateCreateBulk) SaveX(ctx context.Context) []*ExposureState {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ExposureStateCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ExposureStateCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
