// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"deposit-crediting/internal/store/ent/ledgerentry"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// LedgerEntryCreate is the builder for creating a LedgerEntry entity.
type LedgerEntryCreate struct {
	config
	mutation *LedgerEntryMutation
	hooks    []Hook
}

// SetAccount sets the "account" field.
func (_c *LedgerEntryCreate) SetAccount(v string) *LedgerEntryCreate {
	_c.mutation.SetAccount(v)
	return _c
}

// SetAsset sets the "asset" field.
func (_c *LedgerEntryCreate) SetAsset(v string) *LedgerEntryCreate {
	_c.mutation.SetAsset(v)
	return _c
}

// SetType sets the "type" field.
func (_c *LedgerEntryCreate) SetType(v ledgerentry.Type) *LedgerEntryCreate {
	_c.mutation.SetType(v)
	return _c
}

// SetAmount sets the "amount" field.
func (_c *LedgerEntryCreate) SetAmount(v string) *LedgerEntryCreate {
	_c.mutation.SetAmount(v)
	return _c
}

// SetRef sets the "ref" field.
func (_c *LedgerEntryCreate) SetRef(v string) *LedgerEntryCreate {
	_c.mutation.SetRef(v)
	return _c
}

// SetReversesRef sets the "reverses_ref" field.
func (_c *LedgerEntryCreate) SetReversesRef(v string) *LedgerEntryCreate {
	_c.mutation.SetReversesRef(v)
	return _c
}

// SetNillableReversesRef sets the "reverses_ref" field if the given value is not nil.
func (_c *LedgerEntryCreate) SetNillableReversesRef(v *string) *LedgerEntryCreate {
	if v != nil {
		_c.SetReversesRef(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *LedgerEntryCreate) SetCreatedAt(v time.Time) *LedgerEntryCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *LedgerEntryCreate) SetNillableCreatedAt(v *time.Time) *LedgerEntryCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// Mutation returns the LedgerEntryMutation object of the builder.
func (_c *LedgerEntryCreate) Mutation() *LedgerEntryMutation {
	return _c.mutation
}

// Save creates the LedgerEntry in the database.
func (_c *LedgerEntryCreate) Save(ctx context.Context) (*LedgerEntry, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *LedgerEntryCreate) SaveX(ctx context.Context) *LedgerEntry {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LedgerEntryCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LedgerEntryCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *LedgerEntryCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := ledgerentry.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *LedgerEntryCreate) check() error {
	if _, ok := _c.mutation.Account(); !ok {
		return &ValidationError{Name: "account", err: errors.New(`ent: missing required field "LedgerEntry.account"`)}
	}
	if v, ok := _c.mutation.Account(); ok {
		if err := ledgerentry.AccountValidator(v); err != nil {
			return &ValidationError{Name: "account", err: fmt.Errorf(`ent: validator failed for field "LedgerEntry.account": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Asset(); !ok {
		return &ValidationError{Name: "asset", err: errors.New(`ent: missing required field "LedgerEntry.asset"`)}
	}
	if v, ok := _c.mutation.Asset(); ok {
		if err := ledgerentry.AssetValidator(v); err != nil {
			return &ValidationError{Name: "asset", err: fmt.Errorf(`ent: validator failed for field "LedgerEntry.asset": %w`, err)}
		}
	}
	if _, ok := _c.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "LedgerEntry.type"`)}
	}
	if v, ok := _c.mutation.GetType(); ok {
		if err := ledgerentry.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "LedgerEntry.type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Amount(); !ok {
		return &ValidationError{Name: "amount", err: errors.New(`ent: missing required field "LedgerEntry.amount"`)}
	}
	if _, ok := _c.mutation.Ref(); !ok {
		return &ValidationError{Name: "ref", err: errors.New(`ent: missing required field "LedgerEntry.ref"`)}
	}
	if v, ok := _c.mutation.Ref(); ok {
		if err := ledgerentry.RefValidator(v); err != nil {
			return &ValidationError{Name: "ref", err: fmt.Errorf(`ent: validator failed for field "LedgerEntry.ref": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "LedgerEntry.created_at"`)}
	}
	return nil
}

func (_c *LedgerEntryCreate) sqlSave(ctx context.Context) (*LedgerEntry, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *LedgerEntryCreate) createSpec() (*LedgerEntry, *sqlgraph.CreateSpec) {
	var (
		_node = &LedgerEntry{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(ledgerentry.Table, sqlgraph.NewFieldSpec(ledgerentry.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Account(); ok {
		_spec.SetField(ledgerentry.FieldAccount, field.TypeString, value)
		_node.Account = value
	}
	if value, ok := _c.mutation.Asset(); ok {
		_spec.SetField(ledgerentry.FieldAsset, field.TypeString, value)
		_node.Asset = value
	}
	if value, ok := _c.mutation.GetType(); ok {
		_spec.SetField(ledgerentry.FieldType, field.TypeEnum, value)
		_node.Type = value
	}
	if value, ok := _c.mutation.Amount(); ok {
		_spec.SetField(ledgerentry.FieldAmount, field.TypeString, value)
		_node.Amount = value
	}
	if value, ok := _c.mutation.Ref(); ok {
		_spec.SetField(ledgerentry.FieldRef, field.TypeString, value)
		_node.Ref = value
	}
	if value, ok := _c.mutation.ReversesRef(); ok {
		_spec.SetField(ledgerentry.FieldReversesRef, field.TypeString, value)
		_node.ReversesRef = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(ledgerentry.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// LedgerEntryCreateBulk is the builder for creating many LedgerEntry entities in bulk.
type LedgerEntryCreateBulk struct {
	config
	err      error
	builders []*LedgerEntryCreate
}

// Save creates the LedgerEntry entities in the database.
func (_c *LedgerEntryCreateBulk) Save(ctx context.Context) ([]*LedgerEntry, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*LedgerEntry, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*LedgerEntryMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *LedgerEntryCreateBulk) SaveX(ctx context.Context) []*LedgerEntry {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LedgerEntryCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LedgerEntryCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
