// Code generated by ent, DO NOT EDIT.

package ent

import (
	"deposit-crediting/internal/store/ent/accountbalance"
	"deposit-crediting/internal/store/ent/assetconfig"
	"deposit-crediting/internal/store/ent/canonicalblock"
	"deposit-crediting/internal/store/ent/chaincursor"
	"deposit-crediting/internal/store/ent/deposit"
	"deposit-crediting/internal/store/ent/depositaddress"
	"deposit-crediting/internal/store/ent/ledgerentry"
	"deposit-crediting/internal/store/ent/schema"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	accountbalanceFields := schema.AccountBalance{}.Fields()
	_ = accountbalanceFields
	// accountbalanceDescAccount is the schema descriptor for account field.
	accountbalanceDescAccount := accountbalanceFields[0].Descriptor()
	// accountbalance.AccountValidator is a validator for the "account" field. It is called by the builders before save.
	accountbalance.AccountValidator = accountbalanceDescAccount.Validators[0].(func(string) error)
	// accountbalanceDescAsset is the schema descriptor for asset field.
	accountbalanceDescAsset := accountbalanceFields[1].Descriptor()
	// accountbalance.AssetValidator is a validator for the "asset" field. It is called by the builders before save.
	accountbalance.AssetValidator = accountbalanceDescAsset.Validators[0].(func(string) error)
	// accountbalanceDescBalance is the schema descriptor for balance field.
	accountbalanceDescBalance := accountbalanceFields[2].Descriptor()
	// accountbalance.DefaultBalance holds the default value on creation for the balance field.
	accountbalance.DefaultBalance = accountbalanceDescBalance.Default.(string)
	// accountbalanceDescFlagged is the schema descriptor for flagged field.
	accountbalanceDescFlagged := accountbalanceFields[3].Descriptor()
	// accountbalance.DefaultFlagged holds the default value on creation for the flagged field.
	accountbalance.DefaultFlagged = accountbalanceDescFlagged.Default.(bool)
	// accountbalanceDescVersion is the schema descriptor for version field.
	accountbalanceDescVersion := accountbalanceFields[4].Descriptor()
	// accountbalance.DefaultVersion holds the default value on creation for the version field.
	accountbalance.DefaultVersion = accountbalanceDescVersion.Default.(int)
	assetconfigFields := schema.AssetConfig{}.Fields()
	_ = assetconfigFields
	// assetconfigDescChain is the schema descriptor for chain field.
	assetconfigDescChain := assetconfigFields[0].Descriptor()
	// assetconfig.ChainValidator is a validator for the "chain" field. It is called by the builders before save.
	assetconfig.ChainValidator = assetconfigDescChain.Validators[0].(func(string) error)
	// assetconfigDescAsset is the schema descriptor for asset field.
	assetconfigDescAsset := assetconfigFields[1].Descriptor()
	// assetconfig.AssetValidator is a validator for the "asset" field. It is called by the builders before save.
	assetconfig.AssetValidator = assetconfigDescAsset.Validators[0].(func(string) error)
	// assetconfigDescDecimals is the schema descriptor for decimals field.
	assetconfigDescDecimals := assetconfigFields[2].Descriptor()
	// assetconfig.DecimalsValidator is a validator for the "decimals" field. It is called by the builders before save.
	assetconfig.DecimalsValidator = assetconfigDescDecimals.Validators[0].(func(int) error)
	// assetconfigDescMinAmount is the schema descriptor for min_amount field.
	assetconfigDescMinAmount := assetconfigFields[4].Descriptor()
	// assetconfig.DefaultMinAmount holds the default value on creation for the min_amount field.
	assetconfig.DefaultMinAmount = assetconfigDescMinAmount.Default.(string)
	// assetconfigDescNCredit is the schema descriptor for n_credit field.
	assetconfigDescNCredit := assetconfigFields[5].Descriptor()
	// assetconfig.NCreditValidator is a validator for the "n_credit" field. It is called by the builders before save.
	assetconfig.NCreditValidator = assetconfigDescNCredit.Validators[0].(func(int) error)
	// assetconfigDescNFinalize is the schema descriptor for n_finalize field.
	assetconfigDescNFinalize := assetconfigFields[6].Descriptor()
	// assetconfig.NFinalizeValidator is a validator for the "n_finalize" field. It is called by the builders before save.
	assetconfig.NFinalizeValidator = assetconfigDescNFinalize.Validators[0].(func(int) error)
	// assetconfigDescReorgWindow is the schema descriptor for reorg_window field.
	assetconfigDescReorgWindow := assetconfigFields[7].Descriptor()
	// assetconfig.ReorgWindowValidator is a validator for the "reorg_window" field. It is called by the builders before save.
	assetconfig.ReorgWindowValidator = assetconfigDescReorgWindow.Validators[0].(func(int) error)
	canonicalblockFields := schema.CanonicalBlock{}.Fields()
	_ = canonicalblockFields
	// canonicalblockDescChain is the schema descriptor for chain field.
	canonicalblockDescChain := canonicalblockFields[0].Descriptor()
	// canonicalblock.ChainValidator is a validator for the "chain" field. It is called by the builders before save.
	canonicalblock.ChainValidator = canonicalblockDescChain.Validators[0].(func(string) error)
	// canonicalblockDescHeight is the schema descriptor for height field.
	canonicalblockDescHeight := canonicalblockFields[1].Descriptor()
	// canonicalblock.HeightValidator is a validator for the "height" field. It is called by the builders before save.
	canonicalblock.HeightValidator = canonicalblockDescHeight.Validators[0].(func(int64) error)
	// canonicalblockDescHash is the schema descriptor for hash field.
	canonicalblockDescHash := canonicalblockFields[2].Descriptor()
	// canonicalblock.HashValidator is a validator for the "hash" field. It is called by the builders before save.
	canonicalblock.HashValidator = canonicalblockDescHash.Validators[0].(func(string) error)
	chaincursorFields := schema.ChainCursor{}.Fields()
	_ = chaincursorFields
	// chaincursorDescChain is the schema descriptor for chain field.
	chaincursorDescChain := chaincursorFields[0].Descriptor()
	// chaincursor.ChainValidator is a validator for the "chain" field. It is called by the builders before save.
	chaincursor.ChainValidator = chaincursorDescChain.Validators[0].(func(string) error)
	// chaincursorDescHeight is the schema descriptor for height field.
	chaincursorDescHeight := chaincursorFields[1].Descriptor()
	// chaincursor.HeightValidator is a validator for the "height" field. It is called by the builders before save.
	chaincursor.HeightValidator = chaincursorDescHeight.Validators[0].(func(int64) error)
	// chaincursorDescHash is the schema descriptor for hash field.
	chaincursorDescHash := chaincursorFields[2].Descriptor()
	// chaincursor.HashValidator is a validator for the "hash" field. It is called by the builders before save.
	chaincursor.HashValidator = chaincursorDescHash.Validators[0].(func(string) error)
	depositFields := schema.Deposit{}.Fields()
	_ = depositFields
	// depositDescTransferID is the schema descriptor for transfer_id field.
	depositDescTransferID := depositFields[0].Descriptor()
	// deposit.TransferIDValidator is a validator for the "transfer_id" field. It is called by the builders before save.
	deposit.TransferIDValidator = depositDescTransferID.Validators[0].(func(string) error)
	// depositDescChain is the schema descriptor for chain field.
	depositDescChain := depositFields[1].Descriptor()
	// deposit.ChainValidator is a validator for the "chain" field. It is called by the builders before save.
	deposit.ChainValidator = depositDescChain.Validators[0].(func(string) error)
	// depositDescAsset is the schema descriptor for asset field.
	depositDescAsset := depositFields[2].Descriptor()
	// deposit.AssetValidator is a validator for the "asset" field. It is called by the builders before save.
	deposit.AssetValidator = depositDescAsset.Validators[0].(func(string) error)
	// depositDescAccount is the schema descriptor for account field.
	depositDescAccount := depositFields[3].Descriptor()
	// deposit.AccountValidator is a validator for the "account" field. It is called by the builders before save.
	deposit.AccountValidator = depositDescAccount.Validators[0].(func(string) error)
	// depositDescAddress is the schema descriptor for address field.
	depositDescAddress := depositFields[4].Descriptor()
	// deposit.AddressValidator is a validator for the "address" field. It is called by the builders before save.
	deposit.AddressValidator = depositDescAddress.Validators[0].(func(string) error)
	// depositDescCreditCycle is the schema descriptor for credit_cycle field.
	depositDescCreditCycle := depositFields[8].Descriptor()
	// deposit.DefaultCreditCycle holds the default value on creation for the credit_cycle field.
	deposit.DefaultCreditCycle = depositDescCreditCycle.Default.(int)
	// depositDescCreatedAt is the schema descriptor for created_at field.
	depositDescCreatedAt := depositFields[12].Descriptor()
	// deposit.DefaultCreatedAt holds the default value on creation for the created_at field.
	deposit.DefaultCreatedAt = depositDescCreatedAt.Default.(func() time.Time)
	// depositDescUpdatedAt is the schema descriptor for updated_at field.
	depositDescUpdatedAt := depositFields[13].Descriptor()
	// deposit.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	deposit.DefaultUpdatedAt = depositDescUpdatedAt.Default.(func() time.Time)
	// deposit.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	deposit.UpdateDefaultUpdatedAt = depositDescUpdatedAt.UpdateDefault.(func() time.Time)
	depositaddressFields := schema.DepositAddress{}.Fields()
	_ = depositaddressFields
	// depositaddressDescAccount is the schema descriptor for account field.
	depositaddressDescAccount := depositaddressFields[0].Descriptor()
	// depositaddress.AccountValidator is a validator for the "account" field. It is called by the builders before save.
	depositaddress.AccountValidator = depositaddressDescAccount.Validators[0].(func(string) error)
	// depositaddressDescChain is the schema descriptor for chain field.
	depositaddressDescChain := depositaddressFields[1].Descriptor()
	// depositaddress.ChainValidator is a validator for the "chain" field. It is called by the builders before save.
	depositaddress.ChainValidator = depositaddressDescChain.Validators[0].(func(string) error)
	// depositaddressDescAddress is the schema descriptor for address field.
	depositaddressDescAddress := depositaddressFields[2].Descriptor()
	// depositaddress.AddressValidator is a validator for the "address" field. It is called by the builders before save.
	depositaddress.AddressValidator = depositaddressDescAddress.Validators[0].(func(string) error)
	// depositaddressDescActive is the schema descriptor for active field.
	depositaddressDescActive := depositaddressFields[4].Descriptor()
	// depositaddress.DefaultActive holds the default value on creation for the active field.
	depositaddress.DefaultActive = depositaddressDescActive.Default.(bool)
	ledgerentryFields := schema.LedgerEntry{}.Fields()
	_ = ledgerentryFields
	// ledgerentryDescAccount is the schema descriptor for account field.
	ledgerentryDescAccount := ledgerentryFields[0].Descriptor()
	// ledgerentry.AccountValidator is a validator for the "account" field. It is called by the builders before save.
	ledgerentry.AccountValidator = ledgerentryDescAccount.Validators[0].(func(string) error)
	// ledgerentryDescAsset is the schema descriptor for asset field.
	ledgerentryDescAsset := ledgerentryFields[1].Descriptor()
	// ledgerentry.AssetValidator is a validator for the "asset" field. It is called by the builders before save.
	ledgerentry.AssetValidator = ledgerentryDescAsset.Validators[0].(func(string) error)
	// ledgerentryDescRef is the schema descriptor for ref field.
	ledgerentryDescRef := ledgerentryFields[4].Descriptor()
	// ledgerentry.RefValidator is a validator for the "ref" field. It is called by the builders before save.
	ledgerentry.RefValidator = ledgerentryDescRef.Validators[0].(func(string) error)
	// ledgerentryDescCreatedAt is the schema descriptor for created_at field.
	ledgerentryDescCreatedAt := ledgerentryFields[5].Descriptor()
	// ledgerentry.DefaultCreatedAt holds the default value on creation for the created_at field.
	ledgerentry.DefaultCreatedAt = ledgerentryDescCreatedAt.Default.(func() time.Time)
}
