// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"deposit-crediting/internal/store/ent/sourceevent"
	"encoding/json/jsontext"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SourceEventCreate is the builder for creating a SourceEvent entity.
type SourceEventCreate struct {
	config
	mutation *SourceEventMutation
	hooks    []Hook
}

// SetProvider sets the "provider" field.
func (_c *SourceEventCreate) SetProvider(v string) *SourceEventCreate {
	_c.mutation.SetProvider(v)
	return _c
}

// SetProviderEventID sets the "provider_event_id" field.
func (_c *SourceEventCreate) SetProviderEventID(v string) *SourceEventCreate {
	_c.mutation.SetProviderEventID(v)
	return _c
}

// SetPayload sets the "payload" field.
func (_c *SourceEventCreate) SetPayload(v jsontext.Value) *SourceEventCreate {
	_c.mutation.SetPayload(v)
	return _c
}

// SetReceivedAt sets the "received_at" field.
func (_c *SourceEventCreate) SetReceivedAt(v time.Time) *SourceEventCreate {
	_c.mutation.SetReceivedAt(v)
	return _c
}

// SetNillableReceivedAt sets the "received_at" field if the given value is not nil.
func (_c *SourceEventCreate) SetNillableReceivedAt(v *time.Time) *SourceEventCreate {
	if v != nil {
		_c.SetReceivedAt(*v)
	}
	return _c
}

// Mutation returns the SourceEventMutation object of the builder.
func (_c *SourceEventCreate) Mutation() *SourceEventMutation {
	return _c.mutation
}

// Save creates the SourceEvent in the database.
func (_c *SourceEventCreate) Save(ctx context.Context) (*SourceEvent, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SourceEventCreate) SaveX(ctx context.Context) *SourceEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SourceEventCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SourceEventCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SourceEventCreate) defaults() {
	if _, ok := _c.mutation.ReceivedAt(); !ok {
		v := sourceevent.DefaultReceivedAt()
		_c.mutation.SetReceivedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SourceEventCreate) check() error {
	if _, ok := _c.mutation.Provider(); !ok {
		return &ValidationError{Name: "provider", err: errors.New(`ent: missing required field "SourceEvent.provider"`)}
	}
	if v, ok := _c.mutation.Provider(); ok {
		if err := sourceevent.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "SourceEvent.provider": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ProviderEventID(); !ok {
		return &ValidationError{Name: "provider_event_id", err: errors.New(`ent: missing required field "SourceEvent.provider_event_id"`)}
	}
	if v, ok := _c.mutation.ProviderEventID(); ok {
		if err := sourceevent.ProviderEventIDValidator(v); err != nil {
			return &ValidationError{Name: "provider_event_id", err: fmt.Errorf(`ent: validator failed for field "SourceEvent.provider_event_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ReceivedAt(); !ok {
		return &ValidationError{Name: "received_at", err: errors.New(`ent: missing required field "SourceEvent.received_at"`)}
	}
	return nil
}

func (_c *SourceEventCreate) sqlSave(ctx context.Context) (*SourceEvent, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SourceEventCreate) createSpec() (*SourceEvent, *sqlgraph.CreateSpec) {
	var (
		_node = &SourceEvent{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(sourceevent.Table, sqlgraph.NewFieldSpec(sourceevent.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Provider(); ok {
		_spec.SetField(sourceevent.FieldProvider, field.TypeString, value)
		_node.Provider = value
	}
	if value, ok := _c.mutation.ProviderEventID(); ok {
		_spec.SetField(sourceevent.FieldProviderEventID, field.TypeString, value)
		_node.ProviderEventID = value
	}
	if value, ok := _c.mutation.Payload(); ok {
		_spec.SetField(sourceevent.FieldPayload, field.TypeJSON, value)
		_node.Payload = value
	}
	if value, ok := _c.mutation.ReceivedAt(); ok {
		_spec.SetField(sourceevent.FieldReceivedAt, field.TypeTime, value)
		_node.ReceivedAt = value
	}
	return _node, _spec
}

// SourceEventCreateBulk is the builder for creating many SourceEvent entities in bulk.
type SourceEventCreateBulk struct {
	config
	err      error
	builders []*SourceEventCreate
}

// Save creates the SourceEvent entities in the database.
func (_c *SourceEventCreateBulk) Save(ctx context.Context) ([]*SourceEvent, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SourceEvent, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SourceEventMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SourceEventCreateBulk) SaveX(ctx context.Context) []*SourceEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SourceEventCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SourceEventCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
