// Code generated by ent, DO NOT EDIT.

package ent

import (
	"deposit-crediting/internal/store/ent/sourceevent"
	"encoding/json"
	"encoding/json/jsontext"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// SourceEvent is the model entity for the SourceEvent schema.
type SourceEvent struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Provider holds the value of the "provider" field.
	Provider string `json:"provider,omitempty"`
	// ProviderEventID holds the value of the "provider_event_id" field.
	ProviderEventID string `json:"provider_event_id,omitempty"`
	// Payload holds the value of the "payload" field.
	Payload jsontext.Value `json:"payload,omitempty"`
	// ReceivedAt holds the value of the "received_at" field.
	ReceivedAt   time.Time `json:"received_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SourceEvent) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case sourceevent.FieldPayload:
			values[i] = new([]byte)
		case sourceevent.FieldID:
			values[i] = new(sql.NullInt64)
		case sourceevent.FieldProvider, sourceevent.FieldProviderEventID:
			values[i] = new(sql.NullString)
		case sourceevent.FieldReceivedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SourceEvent fields.
func (_m *SourceEvent) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case sourceevent.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case sourceevent.FieldProvider:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider", values[i])
			} else if value.Valid {
				_m.Provider = value.String
			}
		case sourceevent.FieldProviderEventID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider_event_id", values[i])
			} else if value.Valid {
				_m.ProviderEventID = value.String
			}
		case sourceevent.FieldPayload:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field payload", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Payload); err != nil {
					return fmt.Errorf("unmarshal field payload: %w", err)
				}
			}
		case sourceevent.FieldReceivedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field received_at", values[i])
			} else if value.Valid {
				_m.ReceivedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SourceEvent.
// This includes values selected through modifiers, order, etc.
func (_m *SourceEvent) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this SourceEvent.
// Note that you need to call SourceEvent.Unwrap() before calling this method if this SourceEvent
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *SourceEvent) Update() *SourceEventUpdateOne {
	return NewSourceEventClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the SourceEvent entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *SourceEvent) Unwrap() *SourceEvent {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: SourceEvent is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *SourceEvent) String() string {
	var builder strings.Builder
	builder.WriteString("SourceEvent(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("provider=")
	builder.WriteString(_m.Provider)
	builder.WriteString(", ")
	builder.WriteString("provider_event_id=")
	builder.WriteString(_m.ProviderEventID)
	builder.WriteString(", ")
	builder.WriteString("payload=")
	builder.WriteString(fmt.Sprintf("%v", _m.Payload))
	builder.WriteString(", ")
	builder.WriteString("received_at=")
	builder.WriteString(_m.ReceivedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// SourceEvents is a parsable slice of SourceEvent.
type SourceEvents []*SourceEvent
