// Code generated by ent, DO NOT EDIT.

package sourceevent

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the sourceevent type in the database.
	Label = "source_event"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldProvider holds the string denoting the provider field in the database.
	FieldProvider = "provider"
	// FieldProviderEventID holds the string denoting the provider_event_id field in the database.
	FieldProviderEventID = "provider_event_id"
	// FieldPayload holds the string denoting the payload field in the database.
	FieldPayload = "payload"
	// FieldReceivedAt holds the string denoting the received_at field in the database.
	FieldReceivedAt = "received_at"
	// Table holds the table name of the sourceevent in the database.
	Table = "source_events"
)

// Columns holds all SQL columns for sourceevent fields.
var Columns = []string{
	FieldID,
	FieldProvider,
	FieldProviderEventID,
	FieldPayload,
	FieldReceivedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// ProviderValidator is a validator for the "provider" field. It is called by the builders before save.
	ProviderValidator func(string) error
	// ProviderEventIDValidator is a validator for the "provider_event_id" field. It is called by the builders before save.
	ProviderEventIDValidator func(string) error
	// DefaultReceivedAt holds the default value on creation for the "received_at" field.
	DefaultReceivedAt func() time.Time
)

// OrderOption defines the ordering options for the SourceEvent queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByProvider orders the results by the provider field.
func ByProvider(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProvider, opts...).ToFunc()
}

// ByProviderEventID orders the results by the provider_event_id field.
func ByProviderEventID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProviderEventID, opts...).ToFunc()
}

// ByReceivedAt orders the results by the received_at field.
func ByReceivedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReceivedAt, opts...).ToFunc()
}
