// Code generated by ent, DO NOT EDIT.

package sourceevent

import (
	"deposit-crediting/internal/store/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.SourceEvent {
	return predicate.SourceEvent(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.SourceEvent {
	return predicate.SourceEvent(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.SourceEvent {
	return predicate.SourceEvent(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.SourceEvent {
	return predicate.SourceEvent(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.SourceEvent {
	return predicate.SourceEvent(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.SourceEvent {
	return predicate.SourceEvent(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.SourceEvent {
	return predicate.SourceEvent(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.SourceEvent {
	return predicate.SourceEvent(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.SourceEvent {
	return predicate.SourceEvent(sql.FieldLTE(FieldID, id))
}

// Provider applies equality check predicate on the "provider" field. It's identical to ProviderEQ.
func Provider(v string) predicate.SourceEvent {
	return predicate.SourceEvent(sql.FieldEQ(FieldProvider, v))
}

// ProviderEventID applies equality check predicate on the "provider_event_id" field. It's identical to ProviderEventIDEQ.
func ProviderEventID(v string) predicate.SourceEvent {
	return predicate.SourceEvent(sql.FieldEQ(FieldProviderEventID, v))
}

// ReceivedAt applies equality check predicate on the "received_at" field. It's identical to ReceivedAtEQ.
func ReceivedAt(v time.Time) predicate.SourceEvent {
	return predicate.SourceEvent(sql.FieldEQ(FieldReceivedAt, v))
}

// ProviderEQ applies the EQ predicate on the "provider" field.
func ProviderEQ(v string) predicate.SourceEvent {
	return predicate.SourceEvent(sql.FieldEQ(FieldProvider, v))
}

// ProviderNEQ applies the NEQ predicate on the "provider" field.
func ProviderNEQ(v string) predicate.SourceEvent {
	return predicate.SourceEvent(sql.FieldNEQ(FieldProvider, v))
}

// ProviderIn applies the In predicate on the "provider" field.
func ProviderIn(vs ...string) predicate.SourceEvent {
	return predicate.SourceEvent(sql.FieldIn(FieldProvider, vs...))
}

// ProviderNotIn applies the NotIn predicate on the "provider" field.
func ProviderNotIn(vs ...string) predicate.SourceEvent {
	return predicate.SourceEvent(sql.FieldNotIn(FieldProvider, vs...))
}

// ProviderGT applies the GT predicate on the "provider" field.
func ProviderGT(v string) predicate.SourceEvent {
	return predicate.SourceEvent(sql.FieldGT(FieldProvider, v))
}

// ProviderGTE applies the GTE predicate on the "provider" field.
func ProviderGTE(v string) predicate.SourceEvent {
	return predicate.SourceEvent(sql.FieldGTE(FieldProvider, v))
}

// ProviderLT applies the LT predicate on the "provider" field.
func ProviderLT(v string) predicate.SourceEvent {
	return predicate.SourceEvent(sql.FieldLT(FieldProvider, v))
}

// ProviderLTE applies the LTE predicate on the "provider" field.
func ProviderLTE(v string) predicate.SourceEvent {
	return predicate.SourceEvent(sql.FieldLTE(FieldProvider, v))
}

// ProviderContains applies the Contains predicate on the "provider" field.
func ProviderContains(v string) predicate.SourceEvent {
	return predicate.SourceEvent(sql.FieldContains(FieldProvider, v))
}

// ProviderHasPrefix applies the HasPrefix predicate on the "provider" field.
func ProviderHasPrefix(v string) predicate.SourceEvent {
	return predicate.SourceEvent(sql.FieldHasPrefix(FieldProvider, v))
}

// ProviderHasSuffix applies the HasSuffix predicate on the "provider" field.
func ProviderHasSuffix(v string) predicate.SourceEvent {
	return predicate.SourceEvent(sql.FieldHasSuffix(FieldProvider, v))
}

// ProviderEqualFold applies the EqualFold predicate on the "provider" field.
func ProviderEqualFold(v string) predicate.SourceEvent {
	return predicate.SourceEvent(sql.FieldEqualFold(FieldProvider, v))
}

// ProviderContainsFold applies the ContainsFold predicate on the "provider" field.
func ProviderContainsFold(v string) predicate.SourceEvent {
	return predicate.SourceEvent(sql.FieldContainsFold(FieldProvider, v))
}

// ProviderEventIDEQ applies the EQ predicate on the "provider_event_id" field.
func ProviderEventIDEQ(v string) predicate.SourceEvent {
	return predicate.SourceEvent(sql.FieldEQ(FieldProviderEventID, v))
}

// ProviderEventIDNEQ applies the NEQ predicate on the "provider_event_id" field.
func ProviderEventIDNEQ(v string) predicate.SourceEvent {
	return predicate.SourceEvent(sql.FieldNEQ(FieldProviderEventID, v))
}

// ProviderEventIDIn applies the In predicate on the "provider_event_id" field.
func ProviderEventIDIn(vs ...string) predicate.SourceEvent {
	return predicate.SourceEvent(sql.FieldIn(FieldProviderEventID, vs...))
}

// ProviderEventIDNotIn applies the NotIn predicate on the "provider_event_id" field.
func ProviderEventIDNotIn(vs ...string) predicate.SourceEvent {
	return predicate.SourceEvent(sql.FieldNotIn(FieldProviderEventID, vs...))
}

// ProviderEventIDGT applies the GT predicate on the "provider_event_id" field.
func ProviderEventIDGT(v string) predicate.SourceEvent {
	return predicate.SourceEvent(sql.FieldGT(FieldProviderEventID, v))
}

// ProviderEventIDGTE applies the GTE predicate on the "provider_event_id" field.
func ProviderEventIDGTE(v string) predicate.SourceEvent {
	return predicate.SourceEvent(sql.FieldGTE(FieldProviderEventID, v))
}

// ProviderEventIDLT applies the LT predicate on the "provider_event_id" field.
func ProviderEventIDLT(v string) predicate.SourceEvent {
	return predicate.SourceEvent(sql.FieldLT(FieldProviderEventID, v))
}

// ProviderEventIDLTE applies the LTE predicate on the "provider_event_id" field.
func ProviderEventIDLTE(v string) predicate.SourceEvent {
	return predicate.SourceEvent(sql.FieldLTE(FieldProviderEventID, v))
}

// ProviderEventIDContains applies the Contains predicate on the "provider_event_id" field.
func ProviderEventIDContains(v string) predicate.SourceEvent {
	return predicate.SourceEvent(sql.FieldContains(FieldProviderEventID, v))
}

// ProviderEventIDHasPrefix applies the HasPrefix predicate on the "provider_event_id" field.
func ProviderEventIDHasPrefix(v string) predicate.SourceEvent {
	return predicate.SourceEvent(sql.FieldHasPrefix(FieldProviderEventID, v))
}

// ProviderEventIDHasSuffix applies the HasSuffix predicate on the "provider_event_id" field.
func ProviderEventIDHasSuffix(v string) predicate.SourceEvent {
	return predicate.SourceEvent(sql.FieldHasSuffix(FieldProviderEventID, v))
}

// ProviderEventIDEqualFold applies the EqualFold predicate on the "provider_event_id" field.
func ProviderEventIDEqualFold(v string) predicate.SourceEvent {
	return predicate.SourceEvent(sql.FieldEqualFold(FieldProviderEventID, v))
}

// ProviderEventIDContainsFold applies the ContainsFold predicate on the "provider_event_id" field.
func ProviderEventIDContainsFold(v string) predicate.SourceEvent {
	return predicate.SourceEvent(sql.FieldContainsFold(FieldProviderEventID, v))
}

// PayloadIsNil applies the IsNil predicate on the "payload" field.
func PayloadIsNil() predicate.SourceEvent {
	return predicate.SourceEvent(sql.FieldIsNull(FieldPayload))
}

// PayloadNotNil applies the NotNil predicate on the "payload" field.
func PayloadNotNil() predicate.SourceEvent {
	return predicate.SourceEvent(sql.FieldNotNull(FieldPayload))
}

// ReceivedAtEQ applies the EQ predicate on the "received_at" field.
func ReceivedAtEQ(v time.Time) predicate.SourceEvent {
	return predicate.SourceEvent(sql.FieldEQ(FieldReceivedAt, v))
}

// ReceivedAtNEQ applies the NEQ predicate on the "received_at" field.
func ReceivedAtNEQ(v time.Time) predicate.SourceEvent {
	return predicate.SourceEvent(sql.FieldNEQ(FieldReceivedAt, v))
}

// ReceivedAtIn applies the In predicate on the "received_at" field.
func ReceivedAtIn(vs ...time.Time) predicate.SourceEvent {
	return predicate.SourceEvent(sql.FieldIn(FieldReceivedAt, vs...))
}

// ReceivedAtNotIn applies the NotIn predicate on the "received_at" field.
func ReceivedAtNotIn(vs ...time.Time) predicate.SourceEvent {
	return predicate.SourceEvent(sql.FieldNotIn(FieldReceivedAt, vs...))
}

// ReceivedAtGT applies the GT predicate on the "received_at" field.
func ReceivedAtGT(v time.Time) predicate.SourceEvent {
	return predicate.SourceEvent(sql.FieldGT(FieldReceivedAt, v))
}

// ReceivedAtGTE applies the GTE predicate on the "received_at" field.
func ReceivedAtGTE(v time.Time) predicate.SourceEvent {
	return predicate.SourceEvent(sql.FieldGTE(FieldReceivedAt, v))
}

// ReceivedAtLT applies the LT predicate on the "received_at" field.
func ReceivedAtLT(v time.Time) predicate.SourceEvent {
	return predicate.SourceEvent(sql.FieldLT(FieldReceivedAt, v))
}

// ReceivedAtLTE applies the LTE predicate on the "received_at" field.
func ReceivedAtLTE(v time.Time) predicate.SourceEvent {
	return predicate.SourceEvent(sql.FieldLTE(FieldReceivedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SourceEvent) predicate.SourceEvent {
	return predicate.SourceEvent(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SourceEvent) predicate.SourceEvent {
	return predicate.SourceEvent(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SourceEvent) predicate.SourceEvent {
	return predicate.SourceEvent(sql.NotPredicates(p))
}
