// Code generated by ent, DO NOT EDIT.

package exposurestate

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the exposurestate type in the database.
	Label = "exposure_state"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldChain holds the string denoting the chain field in the database.
	FieldChain = "chain"
	// FieldAsset holds the string denoting the asset field in the database.
	FieldAsset = "asset"
	// FieldHoldsActive holds the string denoting the holds_active field in the database.
	FieldHoldsActive = "holds_active"
	// FieldExposure holds the string denoting the exposure field in the database.
	FieldExposure = "exposure"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the exposurestate in the database.
	Table = "exposure_states"
)

// Columns holds all SQL columns for exposurestate fields.
var Columns = []string{
	FieldID,
	FieldChain,
	FieldAsset,
	FieldHoldsActive,
	FieldExposure,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// ChainValidator is a validator for the "chain" field. It is called by the builders before save.
	ChainValidator func(string) error
	// AssetValidator is a validator for the "asset" field. It is called by the builders before save.
	AssetValidator func(string) error
	// DefaultHoldsActive holds the default value on creation for the "holds_active" field.
	DefaultHoldsActive bool
	// DefaultExposure holds the default value on creation for the "exposure" field.
	DefaultExposure string
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the ExposureState queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByChain orders the results by the chain field.
func ByChain(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChain, opts...).ToFunc()
}

// ByAsset orders the results by the asset field.
func ByAsset(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAsset, opts...).ToFunc()
}

// ByHoldsActive orders the results by the holds_active field.
func ByHoldsActive(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHoldsActive, opts...).ToFunc()
}

// ByExposure orders the results by the exposure field.
func ByExposure(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExposure, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
