// Code generated by ent, DO NOT EDIT.

package exposurestate

import (
	"deposit-crediting/internal/store/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.ExposureState {
	return predicate.ExposureState(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.ExposureState {
	return predicate.ExposureState(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.ExposureState {
	return predicate.ExposureState(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.ExposureState {
	return predicate.ExposureState(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.ExposureState {
	return predicate.ExposureState(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.ExposureState {
	return predicate.ExposureState(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.ExposureState {
	return predicate.ExposureState(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.ExposureState {
	return predicate.ExposureState(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.ExposureState {
	return predicate.ExposureState(sql.FieldLTE(FieldID, id))
}

// Chain applies equality check predicate on the "chain" field. It's identical to ChainEQ.
func Chain(v string) predicate.ExposureState {
	return predicate.ExposureState(sql.FieldEQ(FieldChain, v))
}

// Asset applies equality check predicate on the "asset" field. It's identical to AssetEQ.
func Asset(v string) predicate.ExposureState {
	return predicate.ExposureState(sql.FieldEQ(FieldAsset, v))
}

// HoldsActive applies equality check predicate on the "holds_active" field. It's identical to HoldsActiveEQ.
func HoldsActive(v bool) predicate.ExposureState {
	return predicate.ExposureState(sql.FieldEQ(FieldHoldsActive, v))
}

// Exposure applies equality check predicate on the "exposure" field. It's identical to ExposureEQ.
func Exposure(v string) predicate.ExposureState {
	return predicate.ExposureState(sql.FieldEQ(FieldExposure, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ExposureState {
	return predicate.ExposureState(sql.FieldEQ(FieldUpdatedAt, v))
}

// ChainEQ applies the EQ predicate on the "chain" field.
func ChainEQ(v string) predicate.ExposureState {
	return predicate.ExposureState(sql.FieldEQ(FieldChain, v))
}

// ChainNEQ applies the NEQ predicate on the "chain" field.
func ChainNEQ(v string) predicate.ExposureState {
	return predicate.ExposureState(sql.FieldNEQ(FieldChain, v))
}

// ChainIn applies the In predicate on the "chain" field.
func ChainIn(vs ...string) predicate.ExposureState {
	return predicate.ExposureState(sql.FieldIn(FieldChain, vs...))
}

// ChainNotIn applies the NotIn predicate on the "chain" field.
func ChainNotIn(vs ...string) predicate.ExposureState {
	return predicate.ExposureState(sql.FieldNotIn(FieldChain, vs...))
}

// ChainGT applies the GT predicate on the "chain" field.
func ChainGT(v string) predicate.ExposureState {
	return predicate.ExposureState(sql.FieldGT(FieldChain, v))
}

// ChainGTE applies the GTE predicate on the "chain" field.
func ChainGTE(v string) predicate.ExposureState {
	return predicate.ExposureState(sql.FieldGTE(FieldChain, v))
}

// ChainLT applies the LT predicate on the "chain" field.
func ChainLT(v string) predicate.ExposureState {
	return predicate.ExposureState(sql.FieldLT(FieldChain, v))
}

// ChainLTE applies the LTE predicate on the "chain" field.
func ChainLTE(v string) predicate.ExposureState {
	return predicate.ExposureState(sql.FieldLTE(FieldChain, v))
}

// ChainContains applies the Contains predicate on the "chain" field.
func ChainContains(v string) predicate.ExposureState {
	return predicate.ExposureState(sql.FieldContains(FieldChain, v))
}

// ChainHasPrefix applies the HasPrefix predicate on the "chain" field.
func ChainHasPrefix(v string) predicate.ExposureState {
	return predicate.ExposureState(sql.FieldHasPrefix(FieldChain, v))
}

// ChainHasSuffix applies the HasSuffix predicate on the "chain" field.
func ChainHasSuffix(v string) predicate.ExposureState {
	return predicate.ExposureState(sql.FieldHasSuffix(FieldChain, v))
}

// ChainEqualFold applies the EqualFold predicate on the "chain" field.
func ChainEqualFold(v string) predicate.ExposureState {
	return predicate.ExposureState(sql.FieldEqualFold(FieldChain, v))
}

// ChainContainsFold applies the ContainsFold predicate on the "chain" field.
func ChainContainsFold(v string) predicate.ExposureState {
	return predicate.ExposureState(sql.FieldContainsFold(FieldChain, v))
}

// AssetEQ applies the EQ predicate on the "asset" field.
func AssetEQ(v string) predicate.ExposureState {
	return predicate.ExposureState(sql.FieldEQ(FieldAsset, v))
}

// AssetNEQ applies the NEQ predicate on the "asset" field.
func AssetNEQ(v string) predicate.ExposureState {
	return predicate.ExposureState(sql.FieldNEQ(FieldAsset, v))
}

// AssetIn applies the In predicate on the "asset" field.
func AssetIn(vs ...string) predicate.ExposureState {
	return predicate.ExposureState(sql.FieldIn(FieldAsset, vs...))
}

// AssetNotIn applies the NotIn predicate on the "asset" field.
func AssetNotIn(vs ...string) predicate.ExposureState {
	return predicate.ExposureState(sql.FieldNotIn(FieldAsset, vs...))
}

// AssetGT applies the GT predicate on the "asset" field.
func AssetGT(v string) predicate.ExposureState {
	return predicate.ExposureState(sql.FieldGT(FieldAsset, v))
}

// AssetGTE applies the GTE predicate on the "asset" field.
func AssetGTE(v string) predicate.ExposureState {
	return predicate.ExposureState(sql.FieldGTE(FieldAsset, v))
}

// AssetLT applies the LT predicate on the "asset" field.
func AssetLT(v string) predicate.ExposureState {
	return predicate.ExposureState(sql.FieldLT(FieldAsset, v))
}

// AssetLTE applies the LTE predicate on the "asset" field.
func AssetLTE(v string) predicate.ExposureState {
	return predicate.ExposureState(sql.FieldLTE(FieldAsset, v))
}

// AssetContains applies the Contains predicate on the "asset" field.
func AssetContains(v string) predicate.ExposureState {
	return predicate.ExposureState(sql.FieldContains(FieldAsset, v))
}

// AssetHasPrefix applies the HasPrefix predicate on the "asset" field.
func AssetHasPrefix(v string) predicate.ExposureState {
	return predicate.ExposureState(sql.FieldHasPrefix(FieldAsset, v))
}

// AssetHasSuffix applies the HasSuffix predicate on the "asset" field.
func AssetHasSuffix(v string) predicate.ExposureState {
	return predicate.ExposureState(sql.FieldHasSuffix(FieldAsset, v))
}

// AssetEqualFold applies the EqualFold predicate on the "asset" field.
func AssetEqualFold(v string) predicate.ExposureState {
	return predicate.ExposureState(sql.FieldEqualFold(FieldAsset, v))
}

// AssetContainsFold applies the ContainsFold predicate on the "asset" field.
func AssetContainsFold(v string) predicate.ExposureState {
	return predicate.ExposureState(sql.FieldContainsFold(FieldAsset, v))
}

// HoldsActiveEQ applies the EQ predicate on the "holds_active" field.
func HoldsActiveEQ(v bool) predicate.ExposureState {
	return predicate.ExposureState(sql.FieldEQ(FieldHoldsActive, v))
}

// HoldsActiveNEQ applies the NEQ predicate on the "holds_active" field.
func HoldsActiveNEQ(v bool) predicate.ExposureState {
	return predicate.ExposureState(sql.FieldNEQ(FieldHoldsActive, v))
}

// ExposureEQ applies the EQ predicate on the "exposure" field.
func ExposureEQ(v string) predicate.ExposureState {
	return predicate.ExposureState(sql.FieldEQ(FieldExposure, v))
}

// ExposureNEQ applies the NEQ predicate on the "exposure" field.
func ExposureNEQ(v string) predicate.ExposureState {
	return predicate.ExposureState(sql.FieldNEQ(FieldExposure, v))
}

// ExposureIn applies the In predicate on the "exposure" field.
func ExposureIn(vs ...string) predicate.ExposureState {
	return predicate.ExposureState(sql.FieldIn(FieldExposure, vs...))
}

// ExposureNotIn applies the NotIn predicate on the "exposure" field.
func ExposureNotIn(vs ...string) predicate.ExposureState {
	return predicate.ExposureState(sql.FieldNotIn(FieldExposure, vs...))
}

// ExposureGT applies the GT predicate on the "exposure" field.
func ExposureGT(v string) predicate.ExposureState {
	return predicate.ExposureState(sql.FieldGT(FieldExposure, v))
}

// ExposureGTE applies the GTE predicate on the "exposure" field.
func ExposureGTE(v string) predicate.ExposureState {
	return predicate.ExposureState(sql.FieldGTE(FieldExposure, v))
}

// ExposureLT applies the LT predicate on the "exposure" field.
func ExposureLT(v string) predicate.ExposureState {
	return predicate.ExposureState(sql.FieldLT(FieldExposure, v))
}

// ExposureLTE applies the LTE predicate on the "exposure" field.
func ExposureLTE(v string) predicate.ExposureState {
	return predicate.ExposureState(sql.FieldLTE(FieldExposure, v))
}

// ExposureContains applies the Contains predicate on the "exposure" field.
func ExposureContains(v string) predicate.ExposureState {
	return predicate.ExposureState(sql.FieldContains(FieldExposure, v))
}

// ExposureHasPrefix applies the HasPrefix predicate on the "exposure" field.
func ExposureHasPrefix(v string) predicate.ExposureState {
	return predicate.ExposureState(sql.FieldHasPrefix(FieldExposure, v))
}

// ExposureHasSuffix applies the HasSuffix predicate on the "exposure" field.
func ExposureHasSuffix(v string) predicate.ExposureState {
	return predicate.ExposureState(sql.FieldHasSuffix(FieldExposure, v))
}

// ExposureEqualFold applies the EqualFold predicate on the "exposure" field.
func ExposureEqualFold(v string) predicate.ExposureState {
	return predicate.ExposureState(sql.FieldEqualFold(FieldExposure, v))
}

// ExposureContainsFold applies the ContainsFold predicate on the "exposure" field.
func ExposureContainsFold(v string) predicate.ExposureState {
	return predicate.ExposureState(sql.FieldContainsFold(FieldExposure, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ExposureState {
	return predicate.ExposureState(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ExposureState {
	return predicate.ExposureState(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ExposureState {
	return predicate.ExposureState(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ExposureState {
	return predicate.ExposureState(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ExposureState {
	return predicate.ExposureState(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ExposureState {
	return predicate.ExposureState(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ExposureState {
	return predicate.ExposureState(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ExposureState {
	return predicate.ExposureState(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ExposureState) predicate.ExposureState {
	return predicate.ExposureState(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ExposureState) predicate.ExposureState {
	return predicate.ExposureState(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ExposureState) predicate.ExposureState {
	return predicate.ExposureState(sql.NotPredicates(p))
}
