// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"deposit-crediting/internal/credit"
	"deposit-crediting/internal/domain"
	"math/big"

	mock "github.com/stretchr/testify/mock"
)

// NewMockTx creates a new instance of MockTx. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTx(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTx {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockTx{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockTx is an autogenerated mock type for the Tx type
type MockTx struct {
	mock.Mock
}

type MockTx_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTx) EXPECT() *MockTx_Expecter {
	return &MockTx_Expecter{mock: &_m.Mock}
}

// BalanceForUpdate provides a mock function for the type MockTx
func (_mock *MockTx) BalanceForUpdate(ctx context.Context, account string, asset string) (credit.Balance, error) {
	ret := _mock.Called(ctx, account, asset)

	if len(ret) == 0 {
		panic("no return value specified for BalanceForUpdate")
	}

	var r0 credit.Balance
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (credit.Balance, error)); ok {
		return returnFunc(ctx, account, asset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) credit.Balance); ok {
		r0 = returnFunc(ctx, account, asset)
	} else {
		r0 = ret.Get(0).(credit.Balance)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, account, asset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTx_BalanceForUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BalanceForUpdate'
type MockTx_BalanceForUpdate_Call struct {
	*mock.Call
}

// BalanceForUpdate is a helper method to define mock.On call
//   - ctx context.Context
//   - account string
//   - asset string
func (_e *MockTx_Expecter) BalanceForUpdate(ctx any, account any, asset any) *MockTx_BalanceForUpdate_Call {
	return &MockTx_BalanceForUpdate_Call{Call: _e.mock.On("BalanceForUpdate", ctx, account, asset)}
}

func (_c *MockTx_BalanceForUpdate_Call) Run(run func(ctx context.Context, account string, asset string)) *MockTx_BalanceForUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTx_BalanceForUpdate_Call) Return(balance credit.Balance, err error) *MockTx_BalanceForUpdate_Call {
	_c.Call.Return(balance, err)
	return _c
}

func (_c *MockTx_BalanceForUpdate_Call) RunAndReturn(run func(ctx context.Context, account string, asset string) (credit.Balance, error)) *MockTx_BalanceForUpdate_Call {
	_c.Call.Return(run)
	return _c
}

// ClearHeld provides a mock function for the type MockTx
func (_mock *MockTx) ClearHeld(ctx context.Context, transferID string, account string, asset string, amount *big.Int) error {
	ret := _mock.Called(ctx, transferID, account, asset, amount)

	if len(ret) == 0 {
		panic("no return value specified for ClearHeld")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, *big.Int) error); ok {
		r0 = returnFunc(ctx, transferID, account, asset, amount)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTx_ClearHeld_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClearHeld'
type MockTx_ClearHeld_Call struct {
	*mock.Call
}

// ClearHeld is a helper method to define mock.On call
//   - ctx context.Context
//   - transferID string
//   - account string
//   - asset string
//   - amount *big.Int
func (_e *MockTx_Expecter) ClearHeld(ctx any, transferID any, account any, asset any, amount any) *MockTx_ClearHeld_Call {
	return &MockTx_ClearHeld_Call{Call: _e.mock.On("ClearHeld", ctx, transferID, account, asset, amount)}
}

func (_c *MockTx_ClearHeld_Call) Run(run func(ctx context.Context, transferID string, account string, asset string, amount *big.Int)) *MockTx_ClearHeld_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 *big.Int
		if args[4] != nil {
			arg4 = args[4].(*big.Int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockTx_ClearHeld_Call) Return(err error) *MockTx_ClearHeld_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTx_ClearHeld_Call) RunAndReturn(run func(ctx context.Context, transferID string, account string, asset string, amount *big.Int) error) *MockTx_ClearHeld_Call {
	_c.Call.Return(run)
	return _c
}

// DepositForUpdate provides a mock function for the type MockTx
func (_mock *MockTx) DepositForUpdate(ctx context.Context, transferID string) (credit.View, error) {
	ret := _mock.Called(ctx, transferID)

	if len(ret) == 0 {
		panic("no return value specified for DepositForUpdate")
	}

	var r0 credit.View
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (credit.View, error)); ok {
		return returnFunc(ctx, transferID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) credit.View); ok {
		r0 = returnFunc(ctx, transferID)
	} else {
		r0 = ret.Get(0).(credit.View)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, transferID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTx_DepositForUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DepositForUpdate'
type MockTx_DepositForUpdate_Call struct {
	*mock.Call
}

// DepositForUpdate is a helper method to define mock.On call
//   - ctx context.Context
//   - transferID string
func (_e *MockTx_Expecter) DepositForUpdate(ctx any, transferID any) *MockTx_DepositForUpdate_Call {
	return &MockTx_DepositForUpdate_Call{Call: _e.mock.On("DepositForUpdate", ctx, transferID)}
}

func (_c *MockTx_DepositForUpdate_Call) Run(run func(ctx context.Context, transferID string)) *MockTx_DepositForUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTx_DepositForUpdate_Call) Return(view credit.View, err error) *MockTx_DepositForUpdate_Call {
	_c.Call.Return(view, err)
	return _c
}

func (_c *MockTx_DepositForUpdate_Call) RunAndReturn(run func(ctx context.Context, transferID string) (credit.View, error)) *MockTx_DepositForUpdate_Call {
	_c.Call.Return(run)
	return _c
}

// HasEntry provides a mock function for the type MockTx
func (_mock *MockTx) HasEntry(ctx context.Context, ref string) (bool, error) {
	ret := _mock.Called(ctx, ref)

	if len(ret) == 0 {
		panic("no return value specified for HasEntry")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(ctx, ref)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, ref)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, ref)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTx_HasEntry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasEntry'
type MockTx_HasEntry_Call struct {
	*mock.Call
}

// HasEntry is a helper method to define mock.On call
//   - ctx context.Context
//   - ref string
func (_e *MockTx_Expecter) HasEntry(ctx any, ref any) *MockTx_HasEntry_Call {
	return &MockTx_HasEntry_Call{Call: _e.mock.On("HasEntry", ctx, ref)}
}

func (_c *MockTx_HasEntry_Call) Run(run func(ctx context.Context, ref string)) *MockTx_HasEntry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTx_HasEntry_Call) Return(b bool, err error) *MockTx_HasEntry_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockTx_HasEntry_Call) RunAndReturn(run func(ctx context.Context, ref string) (bool, error)) *MockTx_HasEntry_Call {
	_c.Call.Return(run)
	return _c
}

// HoldsActive provides a mock function for the type MockTx
func (_mock *MockTx) HoldsActive(ctx context.Context, chain string, asset string) (bool, *big.Int, error) {
	ret := _mock.Called(ctx, chain, asset)

	if len(ret) == 0 {
		panic("no return value specified for HoldsActive")
	}

	var r0 bool
	var r1 *big.Int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (bool, *big.Int, error)); ok {
		return returnFunc(ctx, chain, asset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = returnFunc(ctx, chain, asset)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) *big.Int); ok {
		r1 = returnFunc(ctx, chain, asset)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*big.Int)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, string) error); ok {
		r2 = returnFunc(ctx, chain, asset)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockTx_HoldsActive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HoldsActive'
type MockTx_HoldsActive_Call struct {
	*mock.Call
}

// HoldsActive is a helper method to define mock.On call
//   - ctx context.Context
//   - chain string
//   - asset string
func (_e *MockTx_Expecter) HoldsActive(ctx any, chain any, asset any) *MockTx_HoldsActive_Call {
	return &MockTx_HoldsActive_Call{Call: _e.mock.On("HoldsActive", ctx, chain, asset)}
}

func (_c *MockTx_HoldsActive_Call) Run(run func(ctx context.Context, chain string, asset string)) *MockTx_HoldsActive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTx_HoldsActive_Call) Return(active bool, tier *big.Int, err error) *MockTx_HoldsActive_Call {
	_c.Call.Return(active, tier, err)
	return _c
}

func (_c *MockTx_HoldsActive_Call) RunAndReturn(run func(ctx context.Context, chain string, asset string) (bool, *big.Int, error)) *MockTx_HoldsActive_Call {
	_c.Call.Return(run)
	return _c
}

// InsertEntry provides a mock function for the type MockTx
func (_mock *MockTx) InsertEntry(ctx context.Context, e credit.Entry) error {
	ret := _mock.Called(ctx, e)

	if len(ret) == 0 {
		panic("no return value specified for InsertEntry")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, credit.Entry) error); ok {
		r0 = returnFunc(ctx, e)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTx_InsertEntry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertEntry'
type MockTx_InsertEntry_Call struct {
	*mock.Call
}

// InsertEntry is a helper method to define mock.On call
//   - ctx context.Context
//   - e credit.Entry
func (_e *MockTx_Expecter) InsertEntry(ctx any, e any) *MockTx_InsertEntry_Call {
	return &MockTx_InsertEntry_Call{Call: _e.mock.On("InsertEntry", ctx, e)}
}

func (_c *MockTx_InsertEntry_Call) Run(run func(ctx context.Context, e credit.Entry)) *MockTx_InsertEntry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 credit.Entry
		if args[1] != nil {
			arg1 = args[1].(credit.Entry)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTx_InsertEntry_Call) Return(err error) *MockTx_InsertEntry_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTx_InsertEntry_Call) RunAndReturn(run func(ctx context.Context, e credit.Entry) error) *MockTx_InsertEntry_Call {
	_c.Call.Return(run)
	return _c
}

// ReversalOf provides a mock function for the type MockTx
func (_mock *MockTx) ReversalOf(ctx context.Context, ref string) (bool, error) {
	ret := _mock.Called(ctx, ref)

	if len(ret) == 0 {
		panic("no return value specified for ReversalOf")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(ctx, ref)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, ref)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, ref)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTx_ReversalOf_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReversalOf'
type MockTx_ReversalOf_Call struct {
	*mock.Call
}

// ReversalOf is a helper method to define mock.On call
//   - ctx context.Context
//   - ref string
func (_e *MockTx_Expecter) ReversalOf(ctx any, ref any) *MockTx_ReversalOf_Call {
	return &MockTx_ReversalOf_Call{Call: _e.mock.On("ReversalOf", ctx, ref)}
}

func (_c *MockTx_ReversalOf_Call) Run(run func(ctx context.Context, ref string)) *MockTx_ReversalOf_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTx_ReversalOf_Call) Return(b bool, err error) *MockTx_ReversalOf_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockTx_ReversalOf_Call) RunAndReturn(run func(ctx context.Context, ref string) (bool, error)) *MockTx_ReversalOf_Call {
	_c.Call.Return(run)
	return _c
}

// SetBalance provides a mock function for the type MockTx
func (_mock *MockTx) SetBalance(ctx context.Context, account string, asset string, balance *big.Int) error {
	ret := _mock.Called(ctx, account, asset, balance)

	if len(ret) == 0 {
		panic("no return value specified for SetBalance")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, *big.Int) error); ok {
		r0 = returnFunc(ctx, account, asset, balance)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTx_SetBalance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetBalance'
type MockTx_SetBalance_Call struct {
	*mock.Call
}

// SetBalance is a helper method to define mock.On call
//   - ctx context.Context
//   - account string
//   - asset string
//   - balance *big.Int
func (_e *MockTx_Expecter) SetBalance(ctx any, account any, asset any, balance any) *MockTx_SetBalance_Call {
	return &MockTx_SetBalance_Call{Call: _e.mock.On("SetBalance", ctx, account, asset, balance)}
}

func (_c *MockTx_SetBalance_Call) Run(run func(ctx context.Context, account string, asset string, balance *big.Int)) *MockTx_SetBalance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 *big.Int
		if args[3] != nil {
			arg3 = args[3].(*big.Int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockTx_SetBalance_Call) Return(err error) *MockTx_SetBalance_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTx_SetBalance_Call) RunAndReturn(run func(ctx context.Context, account string, asset string, balance *big.Int) error) *MockTx_SetBalance_Call {
	_c.Call.Return(run)
	return _c
}

// SetBalanceOptimistic provides a mock function for the type MockTx
func (_mock *MockTx) SetBalanceOptimistic(ctx context.Context, account string, asset string, balance *big.Int, expectedVersion int) (bool, error) {
	ret := _mock.Called(ctx, account, asset, balance, expectedVersion)

	if len(ret) == 0 {
		panic("no return value specified for SetBalanceOptimistic")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, *big.Int, int) (bool, error)); ok {
		return returnFunc(ctx, account, asset, balance, expectedVersion)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, *big.Int, int) bool); ok {
		r0 = returnFunc(ctx, account, asset, balance, expectedVersion)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, *big.Int, int) error); ok {
		r1 = returnFunc(ctx, account, asset, balance, expectedVersion)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTx_SetBalanceOptimistic_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetBalanceOptimistic'
type MockTx_SetBalanceOptimistic_Call struct {
	*mock.Call
}

// SetBalanceOptimistic is a helper method to define mock.On call
//   - ctx context.Context
//   - account string
//   - asset string
//   - balance *big.Int
//   - expectedVersion int
func (_e *MockTx_Expecter) SetBalanceOptimistic(ctx any, account any, asset any, balance any, expectedVersion any) *MockTx_SetBalanceOptimistic_Call {
	return &MockTx_SetBalanceOptimistic_Call{Call: _e.mock.On("SetBalanceOptimistic", ctx, account, asset, balance, expectedVersion)}
}

func (_c *MockTx_SetBalanceOptimistic_Call) Run(run func(ctx context.Context, account string, asset string, balance *big.Int, expectedVersion int)) *MockTx_SetBalanceOptimistic_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 *big.Int
		if args[3] != nil {
			arg3 = args[3].(*big.Int)
		}
		var arg4 int
		if args[4] != nil {
			arg4 = args[4].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockTx_SetBalanceOptimistic_Call) Return(b bool, err error) *MockTx_SetBalanceOptimistic_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockTx_SetBalanceOptimistic_Call) RunAndReturn(run func(ctx context.Context, account string, asset string, balance *big.Int, expectedVersion int) (bool, error)) *MockTx_SetBalanceOptimistic_Call {
	_c.Call.Return(run)
	return _c
}

// SetCreditCycle provides a mock function for the type MockTx
func (_mock *MockTx) SetCreditCycle(ctx context.Context, transferID string, cycle int) error {
	ret := _mock.Called(ctx, transferID, cycle)

	if len(ret) == 0 {
		panic("no return value specified for SetCreditCycle")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int) error); ok {
		r0 = returnFunc(ctx, transferID, cycle)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTx_SetCreditCycle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetCreditCycle'
type MockTx_SetCreditCycle_Call struct {
	*mock.Call
}

// SetCreditCycle is a helper method to define mock.On call
//   - ctx context.Context
//   - transferID string
//   - cycle int
func (_e *MockTx_Expecter) SetCreditCycle(ctx any, transferID any, cycle any) *MockTx_SetCreditCycle_Call {
	return &MockTx_SetCreditCycle_Call{Call: _e.mock.On("SetCreditCycle", ctx, transferID, cycle)}
}

func (_c *MockTx_SetCreditCycle_Call) Run(run func(ctx context.Context, transferID string, cycle int)) *MockTx_SetCreditCycle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTx_SetCreditCycle_Call) Return(err error) *MockTx_SetCreditCycle_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTx_SetCreditCycle_Call) RunAndReturn(run func(ctx context.Context, transferID string, cycle int) error) *MockTx_SetCreditCycle_Call {
	_c.Call.Return(run)
	return _c
}

// SetDepositState provides a mock function for the type MockTx
func (_mock *MockTx) SetDepositState(ctx context.Context, transferID string, state domain.State) error {
	ret := _mock.Called(ctx, transferID, state)

	if len(ret) == 0 {
		panic("no return value specified for SetDepositState")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, domain.State) error); ok {
		r0 = returnFunc(ctx, transferID, state)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTx_SetDepositState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetDepositState'
type MockTx_SetDepositState_Call struct {
	*mock.Call
}

// SetDepositState is a helper method to define mock.On call
//   - ctx context.Context
//   - transferID string
//   - state domain.State
func (_e *MockTx_Expecter) SetDepositState(ctx any, transferID any, state any) *MockTx_SetDepositState_Call {
	return &MockTx_SetDepositState_Call{Call: _e.mock.On("SetDepositState", ctx, transferID, state)}
}

func (_c *MockTx_SetDepositState_Call) Run(run func(ctx context.Context, transferID string, state domain.State)) *MockTx_SetDepositState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 domain.State
		if args[2] != nil {
			arg2 = args[2].(domain.State)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTx_SetDepositState_Call) Return(err error) *MockTx_SetDepositState_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTx_SetDepositState_Call) RunAndReturn(run func(ctx context.Context, transferID string, state domain.State) error) *MockTx_SetDepositState_Call {
	_c.Call.Return(run)
	return _c
}

// SetHeld provides a mock function for the type MockTx
func (_mock *MockTx) SetHeld(ctx context.Context, transferID string, account string, asset string, amount *big.Int) error {
	ret := _mock.Called(ctx, transferID, account, asset, amount)

	if len(ret) == 0 {
		panic("no return value specified for SetHeld")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, *big.Int) error); ok {
		r0 = returnFunc(ctx, transferID, account, asset, amount)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTx_SetHeld_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetHeld'
type MockTx_SetHeld_Call struct {
	*mock.Call
}

// SetHeld is a helper method to define mock.On call
//   - ctx context.Context
//   - transferID string
//   - account string
//   - asset string
//   - amount *big.Int
func (_e *MockTx_Expecter) SetHeld(ctx any, transferID any, account any, asset any, amount any) *MockTx_SetHeld_Call {
	return &MockTx_SetHeld_Call{Call: _e.mock.On("SetHeld", ctx, transferID, account, asset, amount)}
}

func (_c *MockTx_SetHeld_Call) Run(run func(ctx context.Context, transferID string, account string, asset string, amount *big.Int)) *MockTx_SetHeld_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 *big.Int
		if args[4] != nil {
			arg4 = args[4].(*big.Int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockTx_SetHeld_Call) Return(err error) *MockTx_SetHeld_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTx_SetHeld_Call) RunAndReturn(run func(ctx context.Context, transferID string, account string, asset string, amount *big.Int) error) *MockTx_SetHeld_Call {
	_c.Call.Return(run)
	return _c
}

// SetReorgedHeight provides a mock function for the type MockTx
func (_mock *MockTx) SetReorgedHeight(ctx context.Context, transferID string, height uint64) error {
	ret := _mock.Called(ctx, transferID, height)

	if len(ret) == 0 {
		panic("no return value specified for SetReorgedHeight")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, uint64) error); ok {
		r0 = returnFunc(ctx, transferID, height)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTx_SetReorgedHeight_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetReorgedHeight'
type MockTx_SetReorgedHeight_Call struct {
	*mock.Call
}

// SetReorgedHeight is a helper method to define mock.On call
//   - ctx context.Context
//   - transferID string
//   - height uint64
func (_e *MockTx_Expecter) SetReorgedHeight(ctx any, transferID any, height any) *MockTx_SetReorgedHeight_Call {
	return &MockTx_SetReorgedHeight_Call{Call: _e.mock.On("SetReorgedHeight", ctx, transferID, height)}
}

func (_c *MockTx_SetReorgedHeight_Call) Run(run func(ctx context.Context, transferID string, height uint64)) *MockTx_SetReorgedHeight_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 uint64
		if args[2] != nil {
			arg2 = args[2].(uint64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTx_SetReorgedHeight_Call) Return(err error) *MockTx_SetReorgedHeight_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTx_SetReorgedHeight_Call) RunAndReturn(run func(ctx context.Context, transferID string, height uint64) error) *MockTx_SetReorgedHeight_Call {
	_c.Call.Return(run)
	return _c
}
