// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// AccountBalance is the predicate function for accountbalance builders.
type AccountBalance func(*sql.Selector)

// AssetConfig is the predicate function for assetconfig builders.
type AssetConfig func(*sql.Selector)

// CanonicalBlock is the predicate function for canonicalblock builders.
type CanonicalBlock func(*sql.Selector)

// ChainCursor is the predicate function for chaincursor builders.
type ChainCursor func(*sql.Selector)

// Deposit is the predicate function for deposit builders.
type Deposit func(*sql.Selector)

// DepositAddress is the predicate function for depositaddress builders.
type DepositAddress func(*sql.Selector)

// LedgerEntry is the predicate function for ledgerentry builders.
type LedgerEntry func(*sql.Selector)
