// Code generated by ent, DO NOT EDIT.

package accountbalance

import (
	"deposit-crediting/internal/store/ent/predicate"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.AccountBalance {
	return predicate.AccountBalance(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.AccountBalance {
	return predicate.AccountBalance(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.AccountBalance {
	return predicate.AccountBalance(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.AccountBalance {
	return predicate.AccountBalance(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.AccountBalance {
	return predicate.AccountBalance(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.AccountBalance {
	return predicate.AccountBalance(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.AccountBalance {
	return predicate.AccountBalance(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.AccountBalance {
	return predicate.AccountBalance(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.AccountBalance {
	return predicate.AccountBalance(sql.FieldLTE(FieldID, id))
}

// Account applies equality check predicate on the "account" field. It's identical to AccountEQ.
func Account(v string) predicate.AccountBalance {
	return predicate.AccountBalance(sql.FieldEQ(FieldAccount, v))
}

// Asset applies equality check predicate on the "asset" field. It's identical to AssetEQ.
func Asset(v string) predicate.AccountBalance {
	return predicate.AccountBalance(sql.FieldEQ(FieldAsset, v))
}

// Balance applies equality check predicate on the "balance" field. It's identical to BalanceEQ.
func Balance(v string) predicate.AccountBalance {
	return predicate.AccountBalance(sql.FieldEQ(FieldBalance, v))
}

// Held applies equality check predicate on the "held" field. It's identical to HeldEQ.
func Held(v string) predicate.AccountBalance {
	return predicate.AccountBalance(sql.FieldEQ(FieldHeld, v))
}

// Flagged applies equality check predicate on the "flagged" field. It's identical to FlaggedEQ.
func Flagged(v bool) predicate.AccountBalance {
	return predicate.AccountBalance(sql.FieldEQ(FieldFlagged, v))
}

// Version applies equality check predicate on the "version" field. It's identical to VersionEQ.
func Version(v int) predicate.AccountBalance {
	return predicate.AccountBalance(sql.FieldEQ(FieldVersion, v))
}

// AccountEQ applies the EQ predicate on the "account" field.
func AccountEQ(v string) predicate.AccountBalance {
	return predicate.AccountBalance(sql.FieldEQ(FieldAccount, v))
}

// AccountNEQ applies the NEQ predicate on the "account" field.
func AccountNEQ(v string) predicate.AccountBalance {
	return predicate.AccountBalance(sql.FieldNEQ(FieldAccount, v))
}

// AccountIn applies the In predicate on the "account" field.
func AccountIn(vs ...string) predicate.AccountBalance {
	return predicate.AccountBalance(sql.FieldIn(FieldAccount, vs...))
}

// AccountNotIn applies the NotIn predicate on the "account" field.
func AccountNotIn(vs ...string) predicate.AccountBalance {
	return predicate.AccountBalance(sql.FieldNotIn(FieldAccount, vs...))
}

// AccountGT applies the GT predicate on the "account" field.
func AccountGT(v string) predicate.AccountBalance {
	return predicate.AccountBalance(sql.FieldGT(FieldAccount, v))
}

// AccountGTE applies the GTE predicate on the "account" field.
func AccountGTE(v string) predicate.AccountBalance {
	return predicate.AccountBalance(sql.FieldGTE(FieldAccount, v))
}

// AccountLT applies the LT predicate on the "account" field.
func AccountLT(v string) predicate.AccountBalance {
	return predicate.AccountBalance(sql.FieldLT(FieldAccount, v))
}

// AccountLTE applies the LTE predicate on the "account" field.
func AccountLTE(v string) predicate.AccountBalance {
	return predicate.AccountBalance(sql.FieldLTE(FieldAccount, v))
}

// AccountContains applies the Contains predicate on the "account" field.
func AccountContains(v string) predicate.AccountBalance {
	return predicate.AccountBalance(sql.FieldContains(FieldAccount, v))
}

// AccountHasPrefix applies the HasPrefix predicate on the "account" field.
func AccountHasPrefix(v string) predicate.AccountBalance {
	return predicate.AccountBalance(sql.FieldHasPrefix(FieldAccount, v))
}

// AccountHasSuffix applies the HasSuffix predicate on the "account" field.
func AccountHasSuffix(v string) predicate.AccountBalance {
	return predicate.AccountBalance(sql.FieldHasSuffix(FieldAccount, v))
}

// AccountEqualFold applies the EqualFold predicate on the "account" field.
func AccountEqualFold(v string) predicate.AccountBalance {
	return predicate.AccountBalance(sql.FieldEqualFold(FieldAccount, v))
}

// AccountContainsFold applies the ContainsFold predicate on the "account" field.
func AccountContainsFold(v string) predicate.AccountBalance {
	return predicate.AccountBalance(sql.FieldContainsFold(FieldAccount, v))
}

// AssetEQ applies the EQ predicate on the "asset" field.
func AssetEQ(v string) predicate.AccountBalance {
	return predicate.AccountBalance(sql.FieldEQ(FieldAsset, v))
}

// AssetNEQ applies the NEQ predicate on the "asset" field.
func AssetNEQ(v string) predicate.AccountBalance {
	return predicate.AccountBalance(sql.FieldNEQ(FieldAsset, v))
}

// AssetIn applies the In predicate on the "asset" field.
func AssetIn(vs ...string) predicate.AccountBalance {
	return predicate.AccountBalance(sql.FieldIn(FieldAsset, vs...))
}

// AssetNotIn applies the NotIn predicate on the "asset" field.
func AssetNotIn(vs ...string) predicate.AccountBalance {
	return predicate.AccountBalance(sql.FieldNotIn(FieldAsset, vs...))
}

// AssetGT applies the GT predicate on the "asset" field.
func AssetGT(v string) predicate.AccountBalance {
	return predicate.AccountBalance(sql.FieldGT(FieldAsset, v))
}

// AssetGTE applies the GTE predicate on the "asset" field.
func AssetGTE(v string) predicate.AccountBalance {
	return predicate.AccountBalance(sql.FieldGTE(FieldAsset, v))
}

// AssetLT applies the LT predicate on the "asset" field.
func AssetLT(v string) predicate.AccountBalance {
	return predicate.AccountBalance(sql.FieldLT(FieldAsset, v))
}

// AssetLTE applies the LTE predicate on the "asset" field.
func AssetLTE(v string) predicate.AccountBalance {
	return predicate.AccountBalance(sql.FieldLTE(FieldAsset, v))
}

// AssetContains applies the Contains predicate on the "asset" field.
func AssetContains(v string) predicate.AccountBalance {
	return predicate.AccountBalance(sql.FieldContains(FieldAsset, v))
}

// AssetHasPrefix applies the HasPrefix predicate on the "asset" field.
func AssetHasPrefix(v string) predicate.AccountBalance {
	return predicate.AccountBalance(sql.FieldHasPrefix(FieldAsset, v))
}

// AssetHasSuffix applies the HasSuffix predicate on the "asset" field.
func AssetHasSuffix(v string) predicate.AccountBalance {
	return predicate.AccountBalance(sql.FieldHasSuffix(FieldAsset, v))
}

// AssetEqualFold applies the EqualFold predicate on the "asset" field.
func AssetEqualFold(v string) predicate.AccountBalance {
	return predicate.AccountBalance(sql.FieldEqualFold(FieldAsset, v))
}

// AssetContainsFold applies the ContainsFold predicate on the "asset" field.
func AssetContainsFold(v string) predicate.AccountBalance {
	return predicate.AccountBalance(sql.FieldContainsFold(FieldAsset, v))
}

// BalanceEQ applies the EQ predicate on the "balance" field.
func BalanceEQ(v string) predicate.AccountBalance {
	return predicate.AccountBalance(sql.FieldEQ(FieldBalance, v))
}

// BalanceNEQ applies the NEQ predicate on the "balance" field.
func BalanceNEQ(v string) predicate.AccountBalance {
	return predicate.AccountBalance(sql.FieldNEQ(FieldBalance, v))
}

// BalanceIn applies the In predicate on the "balance" field.
func BalanceIn(vs ...string) predicate.AccountBalance {
	return predicate.AccountBalance(sql.FieldIn(FieldBalance, vs...))
}

// BalanceNotIn applies the NotIn predicate on the "balance" field.
func BalanceNotIn(vs ...string) predicate.AccountBalance {
	return predicate.AccountBalance(sql.FieldNotIn(FieldBalance, vs...))
}

// BalanceGT applies the GT predicate on the "balance" field.
func BalanceGT(v string) predicate.AccountBalance {
	return predicate.AccountBalance(sql.FieldGT(FieldBalance, v))
}

// BalanceGTE applies the GTE predicate on the "balance" field.
func BalanceGTE(v string) predicate.AccountBalance {
	return predicate.AccountBalance(sql.FieldGTE(FieldBalance, v))
}

// BalanceLT applies the LT predicate on the "balance" field.
func BalanceLT(v string) predicate.AccountBalance {
	return predicate.AccountBalance(sql.FieldLT(FieldBalance, v))
}

// BalanceLTE applies the LTE predicate on the "balance" field.
func BalanceLTE(v string) predicate.AccountBalance {
	return predicate.AccountBalance(sql.FieldLTE(FieldBalance, v))
}

// BalanceContains applies the Contains predicate on the "balance" field.
func BalanceContains(v string) predicate.AccountBalance {
	return predicate.AccountBalance(sql.FieldContains(FieldBalance, v))
}

// BalanceHasPrefix applies the HasPrefix predicate on the "balance" field.
func BalanceHasPrefix(v string) predicate.AccountBalance {
	return predicate.AccountBalance(sql.FieldHasPrefix(FieldBalance, v))
}

// BalanceHasSuffix applies the HasSuffix predicate on the "balance" field.
func BalanceHasSuffix(v string) predicate.AccountBalance {
	return predicate.AccountBalance(sql.FieldHasSuffix(FieldBalance, v))
}

// BalanceEqualFold applies the EqualFold predicate on the "balance" field.
func BalanceEqualFold(v string) predicate.AccountBalance {
	return predicate.AccountBalance(sql.FieldEqualFold(FieldBalance, v))
}

// BalanceContainsFold applies the ContainsFold predicate on the "balance" field.
func BalanceContainsFold(v string) predicate.AccountBalance {
	return predicate.AccountBalance(sql.FieldContainsFold(FieldBalance, v))
}

// HeldEQ applies the EQ predicate on the "held" field.
func HeldEQ(v string) predicate.AccountBalance {
	return predicate.AccountBalance(sql.FieldEQ(FieldHeld, v))
}

// HeldNEQ applies the NEQ predicate on the "held" field.
func HeldNEQ(v string) predicate.AccountBalance {
	return predicate.AccountBalance(sql.FieldNEQ(FieldHeld, v))
}

// HeldIn applies the In predicate on the "held" field.
func HeldIn(vs ...string) predicate.AccountBalance {
	return predicate.AccountBalance(sql.FieldIn(FieldHeld, vs...))
}

// HeldNotIn applies the NotIn predicate on the "held" field.
func HeldNotIn(vs ...string) predicate.AccountBalance {
	return predicate.AccountBalance(sql.FieldNotIn(FieldHeld, vs...))
}

// HeldGT applies the GT predicate on the "held" field.
func HeldGT(v string) predicate.AccountBalance {
	return predicate.AccountBalance(sql.FieldGT(FieldHeld, v))
}

// HeldGTE applies the GTE predicate on the "held" field.
func HeldGTE(v string) predicate.AccountBalance {
	return predicate.AccountBalance(sql.FieldGTE(FieldHeld, v))
}

// HeldLT applies the LT predicate on the "held" field.
func HeldLT(v string) predicate.AccountBalance {
	return predicate.AccountBalance(sql.FieldLT(FieldHeld, v))
}

// HeldLTE applies the LTE predicate on the "held" field.
func HeldLTE(v string) predicate.AccountBalance {
	return predicate.AccountBalance(sql.FieldLTE(FieldHeld, v))
}

// HeldContains applies the Contains predicate on the "held" field.
func HeldContains(v string) predicate.AccountBalance {
	return predicate.AccountBalance(sql.FieldContains(FieldHeld, v))
}

// HeldHasPrefix applies the HasPrefix predicate on the "held" field.
func HeldHasPrefix(v string) predicate.AccountBalance {
	return predicate.AccountBalance(sql.FieldHasPrefix(FieldHeld, v))
}

// HeldHasSuffix applies the HasSuffix predicate on the "held" field.
func HeldHasSuffix(v string) predicate.AccountBalance {
	return predicate.AccountBalance(sql.FieldHasSuffix(FieldHeld, v))
}

// HeldEqualFold applies the EqualFold predicate on the "held" field.
func HeldEqualFold(v string) predicate.AccountBalance {
	return predicate.AccountBalance(sql.FieldEqualFold(FieldHeld, v))
}

// HeldContainsFold applies the ContainsFold predicate on the "held" field.
func HeldContainsFold(v string) predicate.AccountBalance {
	return predicate.AccountBalance(sql.FieldContainsFold(FieldHeld, v))
}

// FlaggedEQ applies the EQ predicate on the "flagged" field.
func FlaggedEQ(v bool) predicate.AccountBalance {
	return predicate.AccountBalance(sql.FieldEQ(FieldFlagged, v))
}

// FlaggedNEQ applies the NEQ predicate on the "flagged" field.
func FlaggedNEQ(v bool) predicate.AccountBalance {
	return predicate.AccountBalance(sql.FieldNEQ(FieldFlagged, v))
}

// VersionEQ applies the EQ predicate on the "version" field.
func VersionEQ(v int) predicate.AccountBalance {
	return predicate.AccountBalance(sql.FieldEQ(FieldVersion, v))
}

// VersionNEQ applies the NEQ predicate on the "version" field.
func VersionNEQ(v int) predicate.AccountBalance {
	return predicate.AccountBalance(sql.FieldNEQ(FieldVersion, v))
}

// VersionIn applies the In predicate on the "version" field.
func VersionIn(vs ...int) predicate.AccountBalance {
	return predicate.AccountBalance(sql.FieldIn(FieldVersion, vs...))
}

// VersionNotIn applies the NotIn predicate on the "version" field.
func VersionNotIn(vs ...int) predicate.AccountBalance {
	return predicate.AccountBalance(sql.FieldNotIn(FieldVersion, vs...))
}

// VersionGT applies the GT predicate on the "version" field.
func VersionGT(v int) predicate.AccountBalance {
	return predicate.AccountBalance(sql.FieldGT(FieldVersion, v))
}

// VersionGTE applies the GTE predicate on the "version" field.
func VersionGTE(v int) predicate.AccountBalance {
	return predicate.AccountBalance(sql.FieldGTE(FieldVersion, v))
}

// VersionLT applies the LT predicate on the "version" field.
func VersionLT(v int) predicate.AccountBalance {
	return predicate.AccountBalance(sql.FieldLT(FieldVersion, v))
}

// VersionLTE applies the LTE predicate on the "version" field.
func VersionLTE(v int) predicate.AccountBalance {
	return predicate.AccountBalance(sql.FieldLTE(FieldVersion, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AccountBalance) predicate.AccountBalance {
	return predicate.AccountBalance(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AccountBalance) predicate.AccountBalance {
	return predicate.AccountBalance(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AccountBalance) predicate.AccountBalance {
	return predicate.AccountBalance(sql.NotPredicates(p))
}
